
; https://autohotkey.com/docs/static/source/data_index.js
commandList:=object()
commandList.push(["#AllowSameLineComments","commands/_AllowSameLineComments.htm"])
commandList.push(["#ClipboardTimeout","commands/_ClipboardTimeout.htm"])
commandList.push(["#CommentFlag","commands/_CommentFlag.htm"])
commandList.push(["#Delimiter","commands/_EscapeChar.htm#Delimiter"])
commandList.push(["#DerefChar","commands/_EscapeChar.htm#DerefChar"])
commandList.push(["#ErrorStdOut","commands/_ErrorStdOut.htm"])
commandList.push(["#EscapeChar","commands/_EscapeChar.htm"])
commandList.push(["#HotkeyInterval","commands/_HotkeyInterval.htm"])
commandList.push(["#HotkeyModifierTimeout","commands/_HotkeyModifierTimeout.htm"])
commandList.push(["#Hotstring","commands/_Hotstring.htm"])
commandList.push(["#If","commands/_If.htm"])
commandList.push(["#IfTimeout","commands/_IfTimeout.htm"])
commandList.push(["#IfWinActive","commands/_IfWinActive.htm"])
commandList.push(["#IfWinExist","commands/_IfWinActive.htm"])
commandList.push(["#IfWinNotActive","commands/_IfWinActive.htm"])
commandList.push(["#IfWinNotExist","commands/_IfWinActive.htm"])
commandList.push(["#Include","commands/_Include.htm"])
commandList.push(["#IncludeAgain","commands/_Include.htm"])
commandList.push(["#InputLevel","commands/_InputLevel.htm"])
commandList.push(["#InstallKeybdHook","commands/_InstallKeybdHook.htm"])
commandList.push(["#InstallMouseHook","commands/_InstallMouseHook.htm"])
commandList.push(["#KeyHistory","commands/_KeyHistory.htm"])
commandList.push(["#LTrim","Scripts.htm#LTrim"])
commandList.push(["#MaxHotkeysPerInterval","commands/_MaxHotkeysPerInterval.htm"])
commandList.push(["#MaxMem","commands/_MaxMem.htm"])
commandList.push(["#MaxThreads","commands/_MaxThreads.htm"])
commandList.push(["#MaxThreadsBuffer","commands/_MaxThreadsBuffer.htm"])
commandList.push(["#MaxThreadsPerHotkey","commands/_MaxThreadsPerHotkey.htm"])
commandList.push(["#MenuMaskKey","commands/_MenuMaskKey.htm"])
commandList.push(["#NoEnv","commands/_NoEnv.htm"])
commandList.push(["#NoTrayIcon","commands/_NoTrayIcon.htm"])
commandList.push(["#Persistent","commands/_Persistent.htm"])
commandList.push(["#SingleInstance","commands/_SingleInstance.htm"])
commandList.push(["#UseHook","commands/_UseHook.htm"])
commandList.push(["#Warn","commands/_Warn.htm"])
commandList.push(["#WinActivateForce","commands/_WinActivateForce.htm"])
commandList.push([":=","commands/SetExpression.htm"])
commandList.push(["A_AhkPath","Variables.htm#AhkPath"])
commandList.push(["A_AhkVersion","Variables.htm#AhkVersion"])
commandList.push(["A_AppData","Variables.htm#AppData"])
commandList.push(["A_AppDataCommon","Variables.htm#AppDataCommon"])
commandList.push(["A_AutoTrim","Variables.htm#AutoTrim"])
commandList.push(["A_BatchLines","Variables.htm#BatchLines"])
commandList.push(["A_CaretX","Variables.htm#Caret"])
commandList.push(["A_CaretY","Variables.htm#Caret"])
commandList.push(["A_ComputerName","Variables.htm#ComputerName"])
commandList.push(["A_ControlDelay","Variables.htm#ControlDelay"])
commandList.push(["A_CoordMode...","Variables.htm#CoordMode"])
commandList.push(["A_Cursor","Variables.htm#Cursor"])
commandList.push(["A_DD","Variables.htm#DD"])
commandList.push(["A_DDD","Variables.htm#DDDD"])
commandList.push(["A_DDDD","Variables.htm#DDDD"])
commandList.push(["A_DefaultGui","Variables.htm#DefaultGui"])
commandList.push(["A_DefaultListView","Variables.htm#DefaultListView"])
commandList.push(["A_DefaultMouseSpeed","Variables.htm#DefaultMouseSpeed"])
commandList.push(["A_DefaultTreeView","Variables.htm#DefaultTreeView"])
commandList.push(["A_Desktop","Variables.htm#Desktop"])
commandList.push(["A_DesktopCommon","Variables.htm#DesktopCommon"])
commandList.push(["A_DetectHiddenText","Variables.htm#DetectHiddenText"])
commandList.push(["A_DetectHiddenWindows","Variables.htm#DetectHiddenWindows"])
commandList.push(["A_EndChar","Variables.htm#EndChar"])
commandList.push(["A_EventInfo","Variables.htm#EventInfo"])
commandList.push(["A_ExitReason","Variables.htm#ExitReason"])
commandList.push(["A_FileEncoding","Variables.htm#FileEncoding"])
commandList.push(["A_FormatFloat","Variables.htm#FormatFloat"])
commandList.push(["A_FormatInteger","Variables.htm#FormatInteger"])
commandList.push(["A_Gui","Variables.htm#Gui"])
commandList.push(["A_GuiControl","Variables.htm#GuiControl"])
commandList.push(["A_GuiControlEvent","Variables.htm#GuiControlEvent"])
commandList.push(["A_GuiEvent","Variables.htm#GuiEvent"])
commandList.push(["A_GuiHeight","Variables.htm#GuiWidth"])
commandList.push(["A_GuiWidth","Variables.htm#GuiWidth"])
commandList.push(["A_GuiX","Variables.htm#GuiX"])
commandList.push(["A_GuiY","Variables.htm#GuiY"])
commandList.push(["A_Hour","Variables.htm#Hour"])
commandList.push(["A_IconFile","Variables.htm#IconFile"])
commandList.push(["A_IconHidden","Variables.htm#IconHidden"])
commandList.push(["A_IconNumber","Variables.htm#IconNumber"])
commandList.push(["A_IconTip","Variables.htm#IconTip"])
commandList.push(["A_Index","commands/Loop.htm"])
commandList.push(["A_IPAddress1 through 4","Variables.htm#IPAddress"])
commandList.push(["A_Is64bitOS","Variables.htm#Is64bitOS"])
commandList.push(["A_IsAdmin","Variables.htm#IsAdmin"])
commandList.push(["A_IsCompiled","Variables.htm#IsCompiled"])
commandList.push(["A_IsCritical","Variables.htm#IsCritical"])
commandList.push(["A_IsPaused","Variables.htm#IsPaused"])
commandList.push(["A_IsSuspended","Variables.htm#IsSuspended"])
commandList.push(["A_IsUnicode","Variables.htm#IsUnicode"])
commandList.push(["A_KeyDelay","Variables.htm#KeyDelay"])
commandList.push(["A_KeyDelayPlay","Variables.htm#KeyDelayPlay"])
commandList.push(["A_KeyDuration","Variables.htm#KeyDelay"])
commandList.push(["A_KeyDurationPlay","Variables.htm#KeyDelayPlay"])
commandList.push(["A_Language","Variables.htm#Language"])
commandList.push(["A_Language Values","misc/Languages.htm"])
commandList.push(["A_LastError","Variables.htm#LastError"])
commandList.push(["A_LineFile","Variables.htm#LineFile"])
commandList.push(["A_LineNumber","Variables.htm#LineNumber"])
commandList.push(["A_LoopField","commands/LoopParse.htm#LoopField"])
commandList.push(["A_LoopFileAttrib","commands/LoopFile.htm#LoopFileAttrib"])
commandList.push(["A_LoopFileDir","commands/LoopFile.htm#LoopFileDir"])
commandList.push(["A_LoopFileExt","commands/LoopFile.htm#LoopFileExt"])
commandList.push(["A_LoopFileFullPath","commands/LoopFile.htm#LoopFileFullPath"])
commandList.push(["A_LoopFileLongPath","commands/LoopFile.htm#LoopFileLongPath"])
commandList.push(["A_LoopFileName","commands/LoopFile.htm#LoopFileName"])
commandList.push(["A_LoopFileShortName","commands/LoopFile.htm#LoopFileShortName"])
commandList.push(["A_LoopFileShortPath","commands/LoopFile.htm#LoopFileShortPath"])
commandList.push(["A_LoopFileSize","commands/LoopFile.htm#LoopFileSize"])
commandList.push(["A_LoopFileSizeKB","commands/LoopFile.htm#LoopFileSizeKB"])
commandList.push(["A_LoopFileSizeMB","commands/LoopFile.htm#LoopFileSizeMB"])
commandList.push(["A_LoopFileTimeAccessed","commands/LoopFile.htm#LoopFileTimeAccessed"])
commandList.push(["A_LoopFileTimeCreated","commands/LoopFile.htm#LoopFileTimeCreated"])
commandList.push(["A_LoopFileTimeModified","commands/LoopFile.htm#LoopFileTimeModified"])
commandList.push(["A_LoopReadLine","commands/LoopReadFile.htm#LoopReadLine"])
commandList.push(["A_LoopRegKey","commands/LoopReg.htm#vars"])
commandList.push(["A_LoopRegName","commands/LoopReg.htm#vars"])
commandList.push(["A_LoopRegSubKey","commands/LoopReg.htm#vars"])
commandList.push(["A_LoopRegTimeModified","commands/LoopReg.htm#vars"])
commandList.push(["A_LoopRegType","commands/LoopReg.htm#vars"])
commandList.push(["A_MDay","Variables.htm#DD"])
commandList.push(["A_Min","Variables.htm#Min"])
commandList.push(["A_MM","Variables.htm#MM"])
commandList.push(["A_MMM","Variables.htm#MMM"])
commandList.push(["A_MMMM","Variables.htm#MMMM"])
commandList.push(["A_Mon","Variables.htm#MM"])
commandList.push(["A_MouseDelay","Variables.htm#MouseDelay"])
commandList.push(["A_MouseDelayPlay","Variables.htm#MouseDelay"])
commandList.push(["A_MSec","Variables.htm#MSec"])
commandList.push(["A_MyDocuments","Variables.htm#MyDocuments"])
commandList.push(["A_Now","Variables.htm#Now"])
commandList.push(["A_NowUTC","Variables.htm#NowUTC"])
commandList.push(["A_NumBatchLines","Variables.htm#BatchLines"])
commandList.push(["A_OSType","Variables.htm#OSType"])
commandList.push(["A_OSVersion","Variables.htm#OSVersion"])
commandList.push(["A_PriorHotkey","Variables.htm#PriorHotkey"])
commandList.push(["A_PriorKey","Variables.htm#PriorKey"])
commandList.push(["A_ProgramFiles","Variables.htm#ProgramFiles"])
commandList.push(["A_Programs","Variables.htm#Programs"])
commandList.push(["A_ProgramsCommon","Variables.htm#ProgramsCommon"])
commandList.push(["A_PtrSize","Variables.htm#PtrSize"])
commandList.push(["A_RegView","Variables.htm#RegView"])
commandList.push(["A_ScreenDPI","Variables.htm#ScreenDPI"])
commandList.push(["A_ScreenHeight","Variables.htm#Screen"])
commandList.push(["A_ScreenWidth","Variables.htm#Screen"])
commandList.push(["A_ScriptDir","Variables.htm#ScriptDir"])
commandList.push(["A_ScriptFullPath","Variables.htm#ScriptFullPath"])
commandList.push(["A_ScriptHwnd","Variables.htm#ScriptHwnd"])
commandList.push(["A_ScriptName","Variables.htm#ScriptName"])
commandList.push(["A_Sec","Variables.htm#Sec"])
commandList.push(["A_SendLevel","Variables.htm#SendLevel"])
commandList.push(["A_SendMode","Variables.htm#SendMode"])
commandList.push(["A_Space","Variables.htm#Space"])
commandList.push(["A_StartMenu","Variables.htm#StartMenu"])
commandList.push(["A_StartMenuCommon","Variables.htm#StartMenuCommon"])
commandList.push(["A_Startup","Variables.htm#Startup"])
commandList.push(["A_StartupCommon","Variables.htm#StartupCommon"])
commandList.push(["A_StoreCapslockMode","Variables.htm#StoreCapslockMode"])
commandList.push(["A_StringCaseSense","Variables.htm#StringCaseSense"])
commandList.push(["A_Tab","Variables.htm#Tab"])
commandList.push(["A_Temp","Variables.htm#Temp"])
commandList.push(["A_ThisFunc","Variables.htm#ThisFunc"])
commandList.push(["A_ThisHotkey","Variables.htm#ThisHotkey"])
commandList.push(["A_ThisLabel","Variables.htm#ThisLabel"])
commandList.push(["A_ThisMenu","Variables.htm#ThisMenu"])
commandList.push(["A_ThisMenuItem","Variables.htm#ThisMenuItem"])
commandList.push(["A_ThisMenuItemPos","Variables.htm#ThisMenuItemPos"])
commandList.push(["A_TickCount","Variables.htm#TickCount"])
commandList.push(["A_TimeIdle","Variables.htm#TimeIdle"])
commandList.push(["A_TimeIdlePhysical","Variables.htm#TimeIdlePhysical"])
commandList.push(["A_TimeSincePriorHotkey","Variables.htm#TimeSincePriorHotkey"])
commandList.push(["A_TimeSinceThisHotkey","Variables.htm#TimeSinceThisHotkey"])
commandList.push(["A_TitleMatchMode","Variables.htm#TitleMatchMode"])
commandList.push(["A_TitleMatchModeSpeed","Variables.htm#TitleMatchModeSpeed"])
commandList.push(["A_UserName","Variables.htm#UserName"])
commandList.push(["A_WDay","Variables.htm#WDay"])
commandList.push(["A_WinDelay","Variables.htm#WinDelay"])
commandList.push(["A_WinDir","Variables.htm#WinDir"])
commandList.push(["A_WorkingDir","Variables.htm#WorkingDir"])
commandList.push(["A_YDay","Variables.htm#YDay"])
commandList.push(["A_Year","Variables.htm#YYYY"])
commandList.push(["A_YWeek","Variables.htm#YWeek"])
commandList.push(["A_YYYY","Variables.htm#YYYY"])
commandList.push(["abbreviation expansion","Hotstrings.htm"])
commandList.push(["Abs()","commands/Math.htm#Abs"])
commandList.push(["absolute value, abs()","commands/Math.htm#Abs"])
commandList.push(["Acknowledgements","misc/Acknowledgements.htm"])
commandList.push(["ACos()","commands/Math.htm#ACos"])
commandList.push(["activate a window","commands/WinActivate.htm"])
commandList.push(["ActiveX controls (GUI)","commands/GuiControls.htm#ActiveX"])
commandList.push(["add","commands/EnvAdd.htm"])
commandList.push(["Address of a variable","Variables.htm#amp"])
commandList.push(["administrator privileges for scripts","Variables.htm#RequireAdmin"])
commandList.push(["ahk2exe","Scripts.htm#ahk2exe"])
commandList.push(["ahk_class","misc/WinTitle.htm#ahk_class"])
commandList.push(["ahk_exe","misc/WinTitle.htm#ahk_exe"])
commandList.push(["ahk_group","misc/WinTitle.htm#ahk_group"])
commandList.push(["ahk_id","misc/WinTitle.htm#ahk_id"])
commandList.push(["ahk_pid","misc/WinTitle.htm#ahk_pid"])
commandList.push(["AllowSameLineComments","commands/_AllowSameLineComments.htm"])
commandList.push(["alnum","commands/IfIs.htm"])
commandList.push(["alpha","commands/IfIs.htm"])
commandList.push(["AltGr","Hotkeys.htm#AltGr"])
commandList.push(["AltTab","Hotkeys.htm#alttab"])
commandList.push(["AlwaysOnTop (WinSet)","commands/WinSet.htm"])
commandList.push(["append to file","commands/FileAppend.htm"])
commandList.push(["Arrays","misc/Arrays.htm"])
commandList.push(["Asc()","Functions.htm#Asc"])
commandList.push(["ASCII conversion","commands/Transform.htm"])
commandList.push(["ASin()","commands/Math.htm#ASin"])
commandList.push(["assigning values to variables","Variables.htm#AssignOp"])
commandList.push(["ATan()","commands/Math.htm#ATan"])
commandList.push(["attributes of files and folders","commands/FileGetAttrib.htm"])
commandList.push(["auto-execute section","Scripts.htm"])
commandList.push(["auto-replace text as you type it","Hotstrings.htm"])
commandList.push(["AutoIt v2 compatibility","misc/AutoIt2Compat.htm"])
commandList.push(["AutoTrim","commands/AutoTrim.htm"])
commandList.push(["balloon tip","commands/TrayTip.htm"])
commandList.push(["base (Objects)","Objects.htm#Custom_Objects"])
commandList.push(["beep the PC speaker","commands/SoundBeep.htm"])
commandList.push(["between (check if var between two values)","commands/IfBetween.htm"])
commandList.push(["Bind method (Func object)","objects/Func.htm#Bind"])
commandList.push(["bitwise operations","Variables.htm#bitwise"])
commandList.push(["blind-mode Send","commands/Send.htm#blind"])
commandList.push(["BlockInput","commands/BlockInput.htm"])
commandList.push(["blocks (lines enclosed in braces)","commands/Block.htm"])
commandList.push(["BoundFunc object","objects/Functor.htm#BoundFunc"])
commandList.push(["Break","commands/Break.htm"])
commandList.push(["buffering","commands/_MaxThreadsBuffer.htm"])
commandList.push(["built-in functions","Functions.htm#BuiltIn"])
commandList.push(["built-in variables","Variables.htm#BuiltIn"])
commandList.push(["Button controls (GUI)","commands/GuiControls.htm#Button"])
commandList.push(["button list (mouse and joystick)","KeyList.htm"])
commandList.push(["button state","commands/GetKeyState.htm"])
commandList.push(["ByRef","Functions.htm#ByRef"])
commandList.push(["Call method (Func object)","objects/Func.htm#Call"])
commandList.push(["callbacks","commands/RegisterCallback.htm"])
commandList.push(["case sensitive strings","commands/StringCaseSense.htm"])
commandList.push(["Catch","commands/Catch.htm"])
commandList.push(["Ceil()","commands/Math.htm#Ceil"])
commandList.push(["Changelog","AHKL_ChangeLog.htm"])
commandList.push(["Checkbox controls (GUI)","commands/GuiControls.htm#Checkbox"])
commandList.push(["choose file","commands/FileSelectFile.htm"])
commandList.push(["choose folder","commands/FileSelectFolder.htm"])
commandList.push(["Chr()","Functions.htm#Chr"])
commandList.push(["class (Objects)","Objects.htm#Custom_Classes"])
commandList.push(["class name of a window","commands/WinGetClass.htm"])
commandList.push(["Click a mouse button","commands/Click.htm"])
commandList.push(["Clipboard","misc/Clipboard.htm"])
commandList.push(["ClipboardAll","misc/Clipboard.htm#ClipboardAll"])
commandList.push(["ClipWait","commands/ClipWait.htm"])
commandList.push(["Clone method (Object)","objects/Object.htm#Clone"])
commandList.push(["close a window","commands/WinClose.htm"])
commandList.push(["CLSID List (My Computer, etc.)","misc/CLSID-List.htm"])
commandList.push(["color names, RGB/HTML","commands/Progress.htm#colors"])
commandList.push(["color of pixels","commands/PixelSearch.htm"])
commandList.push(["COM","commands/ComObjCreate.htm"])
commandList.push(["ComboBox controls (GUI)","commands/GuiControls.htm#ComboBox"])
commandList.push(["comma operator (multi-statement)","Variables.htm#comma"])
commandList.push(["command line parameters","Scripts.htm#cmd"])
commandList.push(["commands, alphabetical list","commands/index.htm"])
commandList.push(["CommentFlag","commands/_CommentFlag.htm"])
commandList.push(["comments in scripts","Scripts.htm#Comments"])
commandList.push(["ComObj...()","commands/ComObjActive.htm"])
commandList.push(["ComObjActive()","commands/ComObjActive.htm"])
commandList.push(["ComObjArray()","commands/ComObjArray.htm"])
commandList.push(["ComObjConnect()","commands/ComObjConnect.htm"])
commandList.push(["ComObjCreate()","commands/ComObjCreate.htm"])
commandList.push(["ComObjError()","commands/ComObjError.htm"])
commandList.push(["ComObjFlags()","commands/ComObjFlags.htm"])
commandList.push(["ComObjGet()","commands/ComObjGet.htm"])
commandList.push(["ComObjQuery()","commands/ComObjQuery.htm"])
commandList.push(["ComObjType()","commands/ComObjType.htm"])
commandList.push(["ComObjValue()","commands/ComObjValue.htm"])
commandList.push(["Compatibility","Compat.htm"])
commandList.push(["compile a script","Scripts.htm#ahk2exe"])
commandList.push(["ComSpec","Variables.htm#ComSpec"])
commandList.push(["concatenate, in expressions","Variables.htm#concat"])
commandList.push(["concatenate, script lines","Scripts.htm#continuation"])
commandList.push(["context menu (GUI)","commands/Gui.htm#GuiContextMenu"])
commandList.push(["continuation sections","Scripts.htm#continuation"])
commandList.push(["Continue","commands/Continue.htm"])
commandList.push(["Control","commands/Control.htm"])
commandList.push(["ControlClick","commands/ControlClick.htm"])
commandList.push(["ControlFocus","commands/ControlFocus.htm"])
commandList.push(["ControlGet","commands/ControlGet.htm"])
commandList.push(["ControlGetFocus","commands/ControlGetFocus.htm"])
commandList.push(["ControlGetPos","commands/ControlGetPos.htm"])
commandList.push(["ControlGetText","commands/ControlGetText.htm"])
commandList.push(["ControlMove","commands/ControlMove.htm"])
commandList.push(["ControlSend","commands/ControlSend.htm"])
commandList.push(["ControlSendRaw","commands/ControlSend.htm"])
commandList.push(["ControlSetText","commands/ControlSetText.htm"])
commandList.push(["convert a script to an EXE","Scripts.htm#ahk2exe"])
commandList.push(["coordinates","commands/CoordMode.htm"])
commandList.push(["CoordMode","commands/CoordMode.htm"])
commandList.push(["copy file","commands/FileCopy.htm"])
commandList.push(["copy folder/directory","commands/FileCopyDir.htm"])
commandList.push(["Cos()","commands/Math.htm#Cos"])
commandList.push(["create file","commands/FileAppend.htm"])
commandList.push(["create folder/directory","commands/FileCreateDir.htm"])
commandList.push(["Critical","commands/Critical.htm"])
commandList.push(["current directory","commands/SetWorkingDir.htm"])
commandList.push(["current thread","misc/Threads.htm"])
commandList.push(["cursor shape","Variables.htm#Cursor"])
commandList.push(["custom combination hotkeys","Hotkeys.htm#Features"])
commandList.push(["Custom controls (GUI)","commands/GuiControls.htm#Custom"])
commandList.push(["dates and times (compare)","commands/EnvSub.htm"])
commandList.push(["dates and times (math)","commands/EnvAdd.htm"])
commandList.push(["dates and times (of files)","commands/FileSetTime.htm"])
commandList.push(["DateTime controls (GUI)","commands/GuiControls.htm#DateTime"])
commandList.push(["debugger","commands/OutputDebug.htm"])
commandList.push(["debugging a script","Scripts.htm#debug"])
commandList.push(["decimal places","commands/SetFormat.htm"])
commandList.push(["delete files","commands/FileDelete.htm"])
commandList.push(["delete folder/directory","commands/FileRemoveDir.htm"])
commandList.push(["Delete method (Object)","objects/Object.htm#Delete"])
commandList.push(["Delimiter","commands/_EscapeChar.htm"])
commandList.push(["DerefChar","commands/_EscapeChar.htm"])
commandList.push(["DetectHiddenText","commands/DetectHiddenText.htm"])
commandList.push(["DetectHiddenWindows","commands/DetectHiddenWindows.htm"])
commandList.push(["dialog FileSelectFile","commands/FileSelectFile.htm"])
commandList.push(["dialog FileSelectFolder","commands/FileSelectFolder.htm"])
commandList.push(["dialog InputBox","commands/InputBox.htm"])
commandList.push(["dialog MsgBox","commands/MsgBox.htm"])
commandList.push(["digit","commands/IfIs.htm"])
commandList.push(["disk space","commands/DriveSpaceFree.htm"])
commandList.push(["divide (math)","Variables.htm#divide"])
commandList.push(["DllCall()","commands/DllCall.htm"])
commandList.push(["download a file","commands/URLDownloadToFile.htm"])
commandList.push(["DPI scaling","commands/Gui.htm#DPIScale"])
commandList.push(["drag and drop (GUI windows)","commands/Gui.htm#GuiDropFiles"])
commandList.push(["drag the mouse","commands/MouseClickDrag.htm"])
commandList.push(["Drive","commands/Drive.htm"])
commandList.push(["DriveGet","commands/DriveGet.htm"])
commandList.push(["DriveSpaceFree","commands/DriveSpaceFree.htm"])
commandList.push(["DropDownList controls (GUI)","commands/GuiControls.htm#DropDownList"])
commandList.push(["Dynamic function calls","Functions.htm#DynCall"])
commandList.push(["Edit","commands/Edit.htm"])
commandList.push(["Edit controls (GUI)","commands/GuiControls.htm#Edit"])
commandList.push(["Else","commands/Else.htm"])
commandList.push(["Enumerator object","objects/Enumerator.htm"])
commandList.push(["EnvAdd","commands/EnvAdd.htm"])
commandList.push(["EnvDiv","commands/EnvDiv.htm"])
commandList.push(["EnvGet","commands/EnvGet.htm"])
commandList.push(["environment variables","Variables.htm#env"])
commandList.push(["environment variables (change them)","commands/EnvSet.htm"])
commandList.push(["EnvMult","commands/EnvMult.htm"])
commandList.push(["EnvSet","commands/EnvSet.htm"])
commandList.push(["EnvSub","commands/EnvSub.htm"])
commandList.push(["EnvUpdate","commands/EnvUpdate.htm"])
commandList.push(["ErrorLevel","misc/ErrorLevel.htm"])
commandList.push(["ErrorStdOut","commands/_ErrorStdOut.htm"])
commandList.push(["escape sequence","commands/_EscapeChar.htm"])
commandList.push(["EscapeChar","commands/_EscapeChar.htm"])
commandList.push(["Exception()","commands/Throw.htm#Exception"])
commandList.push(["Exit","commands/Exit.htm"])
commandList.push(["ExitApp","commands/ExitApp.htm"])
commandList.push(["Exp()","commands/Math.htm#Exp"])
commandList.push(["expressions","Variables.htm#Expressions"])
commandList.push(["ExtractInteger -> NumGet()","commands/NumGet.htm"])
commandList.push(["False","Variables.htm#Boolean"])
commandList.push(["FAQ (Frequently Asked Questions)","FAQ.htm"])
commandList.push(["file attributes","commands/FileSetAttrib.htm"])
commandList.push(["File object","objects/File.htm"])
commandList.push(["file or folder (does it exist)","commands/IfExist.htm"])
commandList.push(["file pattern","commands/LoopFile.htm"])
commandList.push(["file, creating","commands/FileAppend.htm"])
commandList.push(["file, reading","commands/LoopReadFile.htm"])
commandList.push(["file, writing/appending","commands/FileAppend.htm"])
commandList.push(["FileAppend","commands/FileAppend.htm"])
commandList.push(["FileCopy","commands/FileCopy.htm"])
commandList.push(["FileCopyDir","commands/FileCopyDir.htm"])
commandList.push(["FileCreateDir","commands/FileCreateDir.htm"])
commandList.push(["FileCreateShortcut","commands/FileCreateShortcut.htm"])
commandList.push(["FileDelete","commands/FileDelete.htm"])
commandList.push(["FileEncoding","commands/FileEncoding.htm"])
commandList.push(["FileExist()","Functions.htm#FileExist"])
commandList.push(["FileGetAttrib","commands/FileGetAttrib.htm"])
commandList.push(["FileGetShortcut","commands/FileGetShortcut.htm"])
commandList.push(["FileGetSize","commands/FileGetSize.htm"])
commandList.push(["FileGetTime","commands/FileGetTime.htm"])
commandList.push(["FileGetVersion","commands/FileGetVersion.htm"])
commandList.push(["FileInstall","commands/FileInstall.htm"])
commandList.push(["FileMove","commands/FileMove.htm"])
commandList.push(["FileMoveDir","commands/FileMoveDir.htm"])
commandList.push(["FileOpen","commands/FileOpen.htm"])
commandList.push(["FileRead","commands/FileRead.htm"])
commandList.push(["FileReadLine","commands/FileReadLine.htm"])
commandList.push(["FileRecycle","commands/FileRecycle.htm"])
commandList.push(["FileRecycleEmpty","commands/FileRecycleEmpty.htm"])
commandList.push(["FileRemoveDir","commands/FileRemoveDir.htm"])
commandList.push(["FileSelectFile","commands/FileSelectFile.htm"])
commandList.push(["FileSelectFolder","commands/FileSelectFolder.htm"])
commandList.push(["FileSetAttrib","commands/FileSetAttrib.htm"])
commandList.push(["FileSetTime","commands/FileSetTime.htm"])
commandList.push(["Finally","commands/Finally.htm"])
commandList.push(["find a file","commands/IfExist.htm"])
commandList.push(["find a string","commands/StringGetPos.htm"])
commandList.push(["find a window","commands/WinExist.htm"])
commandList.push(["floating point (check if it is one)","commands/IfIs.htm"])
commandList.push(["floating point (SetFormat)","commands/SetFormat.htm"])
commandList.push(["Floor()","commands/Math.htm#Floor"])
commandList.push(["focus","commands/ControlFocus.htm"])
commandList.push(["folder/directory copy","commands/FileCopyDir.htm"])
commandList.push(["folder/directory create","commands/FileCreateDir.htm"])
commandList.push(["folder/directory move","commands/FileMoveDir.htm"])
commandList.push(["folder/directory remove","commands/FileRemoveDir.htm"])
commandList.push(["folder/directory select","commands/FileSelectFolder.htm"])
commandList.push(["Fonts","misc/FontsStandard.htm"])
commandList.push(["For-loop","commands/For.htm"])
commandList.push(["Format()","commands/Format.htm"])
commandList.push(["format (defaults)","commands/SetFormat.htm"])
commandList.push(["FormatTime","commands/FormatTime.htm"])
commandList.push(["free space","commands/DriveSpaceFree.htm"])
commandList.push(["FTP uploading example","commands/FileAppend.htm#FTP"])
commandList.push(["functions (defining and calling)","Functions.htm"])
commandList.push(["functions (libraries)","Functions.htm#lib"])
commandList.push(["function objects","objects/Functor.htm"])
commandList.push(["Func object","objects/Func.htm"])
commandList.push(["Func()","Objects.htm#Function_References"])
commandList.push(["g-label (responding to GUI events)","commands/Gui.htm#label"])
commandList.push(["game automation","commands/PixelSearch.htm"])
commandList.push(["GetAddress method (Object)","objects/Object.htm#GetAddress"])
commandList.push(["GetCapacity method (Object)","objects/Object.htm#GetCapacity"])
commandList.push(["GetKeyName()","Functions.htm#GetKeyName"])
commandList.push(["GetKeySC()","Functions.htm#GetKeyName"])
commandList.push(["GetKeyState","commands/GetKeyState.htm"])
commandList.push(["GetKeyState()","Functions.htm#GetKeyState"])
commandList.push(["GetKeyVK()","Functions.htm#GetKeyName"])
commandList.push(["global variables in functions","Functions.htm#Global"])
commandList.push(["Gosub","commands/Gosub.htm"])
commandList.push(["Goto","commands/Goto.htm"])
commandList.push(["GroupActivate","commands/GroupActivate.htm"])
commandList.push(["GroupAdd","commands/GroupAdd.htm"])
commandList.push(["GroupBox controls (GUI)","commands/GuiControls.htm#GroupBox"])
commandList.push(["GroupClose","commands/GroupClose.htm"])
commandList.push(["GroupDeactivate","commands/GroupDeactivate.htm"])
commandList.push(["Gui","commands/Gui.htm"])
commandList.push(["Gui control types","commands/GuiControls.htm"])
commandList.push(["Gui styles reference","misc/Styles.htm"])
commandList.push(["GuiClose (label)","commands/Gui.htm#GuiClose"])
commandList.push(["GuiContextMenu (label)","commands/Gui.htm#GuiContextMenu"])
commandList.push(["GuiControl","commands/GuiControl.htm"])
commandList.push(["GuiControlGet","commands/GuiControlGet.htm"])
commandList.push(["GuiDropFiles (label)","commands/Gui.htm#GuiDropFiles"])
commandList.push(["GuiEscape (label)","commands/Gui.htm#GuiEscape"])
commandList.push(["GuiSize (label)","commands/Gui.htm#GuiSize"])
commandList.push(["HasKey method (Object)","objects/Object.htm#HasKey"])
commandList.push(["HBITMAP:","misc/ImageHandles.htm"])
commandList.push(["hexadecimal format","commands/SetFormat.htm"])
commandList.push(["hibernate or suspend","commands/Shutdown.htm#Suspend"])
commandList.push(["HICON:","misc/ImageHandles.htm"])
commandList.push(["hidden text","commands/DetectHiddenText.htm"])
commandList.push(["hidden windows","commands/DetectHiddenWindows.htm"])
commandList.push(["HKEY_CLASSES_ROOT","commands/RegRead.htm"])
commandList.push(["HKEY_CURRENT_CONFIG","commands/RegRead.htm"])
commandList.push(["HKEY_CURRENT_USER","commands/RegRead.htm"])
commandList.push(["HKEY_LOCAL_MACHINE","commands/RegRead.htm"])
commandList.push(["HKEY_USERS","commands/RegRead.htm"])
commandList.push(["hook","commands/_InstallKeybdHook.htm"])
commandList.push(["Hotkey","Hotkeys.htm"])
commandList.push(["Hotkey command","commands/Hotkey.htm"])
commandList.push(["Hotkey controls (GUI)","commands/GuiControls.htm#Hotkey"])
commandList.push(["Hotkey, ListHotkeys","commands/ListHotkeys.htm"])
commandList.push(["Hotkey, other features","HotkeyFeatures.htm"])
commandList.push(["HotkeyInterval","commands/_HotkeyInterval.htm"])
commandList.push(["HotkeyModifierTimeout","commands/_HotkeyModifierTimeout.htm"])
commandList.push(["hotstrings and auto-replace","Hotstrings.htm"])
commandList.push(["HTML color names","commands/Progress.htm#colors"])
commandList.push(["HWND (of a control)","commands/ControlGet.htm#Hwnd"])
commandList.push(["HWND (of a window)","misc/WinTitle.htm#ahk_id"])
commandList.push(["icon, changing","commands/Menu.htm#Icon"])
commandList.push(["ID number for a window","commands/WinGet.htm"])
commandList.push(["If","commands/IfEqual.htm"])
commandList.push(["If (expression)","commands/IfExpression.htm"])
commandList.push(["If var ,[not] between Low and High","commands/IfBetween.htm"])
commandList.push(["If var ,[not] in/contains MatchList","commands/IfIn.htm"])
commandList.push(["If var is ,[not] type","commands/IfIs.htm"])
commandList.push(["IfEqual","commands/IfEqual.htm"])
commandList.push(["IfExist","commands/IfExist.htm"])
commandList.push(["IfGreater","commands/IfEqual.htm"])
commandList.push(["IfGreaterOrEqual","commands/IfEqual.htm"])
commandList.push(["IfInString","commands/IfInString.htm"])
commandList.push(["IfLess","commands/IfEqual.htm"])
commandList.push(["IfLessOrEqual","commands/IfEqual.htm"])
commandList.push(["IfMsgBox","commands/IfMsgBox.htm"])
commandList.push(["IfNotEqual","commands/IfEqual.htm"])
commandList.push(["IfNotExist","commands/IfExist.htm"])
commandList.push(["IfNotInString","commands/IfInString.htm"])
commandList.push(["IfWinActive","commands/WinActive.htm"])
commandList.push(["IfWinExist","commands/WinExist.htm"])
commandList.push(["IfWinNotActive","commands/WinActive.htm"])
commandList.push(["IfWinNotExist","commands/WinExist.htm"])
commandList.push(["IL_Add()","commands/ListView.htm#IL_Add"])
commandList.push(["IL_Create()","commands/ListView.htm#IL_Create"])
commandList.push(["IL_Destroy()","commands/ListView.htm#IL_Destroy"])
commandList.push(["Image Lists (GUI)","commands/ListView.htm#IL"])
commandList.push(["ImageSearch","commands/ImageSearch.htm"])
commandList.push(["Include","commands/_Include.htm"])
commandList.push(["infrared remote controls","scripts/WinLIRC.htm"])
commandList.push(["IniDelete","commands/IniDelete.htm"])
commandList.push(["IniRead","commands/IniRead.htm"])
commandList.push(["IniWrite","commands/IniWrite.htm"])
commandList.push(["Input","commands/Input.htm"])
commandList.push(["InputBox","commands/InputBox.htm"])
commandList.push(["Insert method (Object)","objects/Object.htm#Insert"])
commandList.push(["InsertAt method (Object)","objects/Object.htm#InsertAt"])
commandList.push(["InsertInteger -> NumPut()","commands/NumPut.htm"])
commandList.push(["Install","commands/FileInstall.htm"])
commandList.push(["Installer Options","Scripts.htm#install"])
commandList.push(["InstallKeybdHook","commands/_InstallKeybdHook.htm"])
commandList.push(["InstallMouseHook","commands/_InstallMouseHook.htm"])
commandList.push(["InStr()","commands/InStr.htm"])
commandList.push(["integer (check if it is one)","commands/IfIs.htm"])
commandList.push(["integer (SetFormat)","commands/SetFormat.htm"])
commandList.push(["Interrupt","commands/Thread.htm"])
commandList.push(["IsByRef()","Functions.htm#IsByRef"])
commandList.push(["IsFunc()","Functions.htm#IsFunc"])
commandList.push(["IsLabel()","Functions.htm#IsLabel"])
commandList.push(["IsObject()","Objects.htm"])
commandList.push(["Join (continuation sections)","Scripts.htm#Join"])
commandList.push(["Joystick","KeyList.htm#Joystick"])
commandList.push(["JScript, embedded/inline","commands/DllCall.htm#COM"])
commandList.push(["key list (keyboard, mouse, joystick)","KeyList.htm"])
commandList.push(["key state","commands/GetKeyState.htm"])
commandList.push(["keyboard hook","commands/_InstallKeybdHook.htm"])
commandList.push(["KeyHistory","commands/KeyHistory.htm"])
commandList.push(["keystrokes, sending","commands/Send.htm"])
commandList.push(["KeyWait","commands/KeyWait.htm"])
commandList.push(["labels","misc/Labels.htm"])
commandList.push(["last found window","misc/WinTitle.htm#LastFoundWindow"])
commandList.push(["length of a string","commands/StringLen.htm"])
commandList.push(["Length method (Object)","objects/Object.htm#Length"])
commandList.push(["Length method (File object)","objects/File.htm#Length"])
commandList.push(["libraries of functions","Functions.htm#lib"])
commandList.push(["license","license.htm"])
commandList.push(["line continuation","Scripts.htm#continuation"])
commandList.push(["ListBox controls (GUI)","commands/GuiControls.htm#ListBox"])
commandList.push(["ListHotkeys","commands/ListHotkeys.htm"])
commandList.push(["ListLines","commands/ListLines.htm"])
commandList.push(["ListVars","commands/ListVars.htm"])
commandList.push(["ListView controls (GUI)","commands/ListView.htm"])
commandList.push(["ListView, getting text from","commands/ControlGet.htm#List"])
commandList.push(["Ln()","commands/Math.htm#Ln"])
commandList.push(["lnk (link/shortcut) file","commands/FileCreateShortcut.htm"])
commandList.push(["LoadPicture","commands/LoadPicture.htm"])
commandList.push(["local variables","Functions.htm#Locals"])
commandList.push(["Locale","commands/StringCaseSense.htm#Locale"])
commandList.push(["Log()","commands/Math.htm#Log"])
commandList.push(["logarithm, log()","commands/Math.htm#Log"])
commandList.push(["logoff","commands/Shutdown.htm"])
commandList.push(["long file name (converting to)","commands/LoopFile.htm#LoopFileLongPath"])
commandList.push(["Loop","commands/Loop.htm"])
commandList.push(["Loop (until)","commands/Until.htm"])
commandList.push(["Loop (while)","commands/While.htm"])
commandList.push(["Loop, Reg (registry)","commands/LoopReg.htm"])
commandList.push(["Loop, Files and folders","commands/LoopFile.htm"])
commandList.push(["Loop, Parse a string","commands/LoopParse.htm"])
commandList.push(["Loop, Read file contents","commands/LoopReadFile.htm"])
commandList.push(["lParam","commands/PostMessage.htm"])
commandList.push(["LTrim (continuation sections)","Scripts.htm#LTrim"])
commandList.push(["LTrim()","commands/Trim.htm"])
commandList.push(["LV_Add()","commands/ListView.htm#LV_Add"])
commandList.push(["LV_Delete()","commands/ListView.htm#LV_Delete"])
commandList.push(["LV_DeleteCol()","commands/ListView.htm#LV_DeleteCol"])
commandList.push(["LV_GetCount()","commands/ListView.htm#LV_GetCount"])
commandList.push(["LV_GetNext()","commands/ListView.htm#LV_GetNext"])
commandList.push(["LV_GetText()","commands/ListView.htm#LV_GetText"])
commandList.push(["LV_Insert()","commands/ListView.htm#LV_Insert"])
commandList.push(["LV_InsertCol()","commands/ListView.htm#LV_InsertCol"])
commandList.push(["LV_Modify()","commands/ListView.htm#LV_Modify"])
commandList.push(["LV_ModifyCol()","commands/ListView.htm#LV_ModifyCol"])
commandList.push(["LV_SetImageList()","commands/ListView.htm#LV_SetImageList"])
commandList.push(["macro","misc/Macros.htm"])
commandList.push(["math operations (expressions)","Variables.htm#Expressions"])
commandList.push(["MaxHotkeysPerInterval","commands/_MaxHotkeysPerInterval.htm"])
commandList.push(["MaxIndex()","objects/Object.htm#MinMaxIndex"])
commandList.push(["MaxThreads","commands/_MaxThreads.htm"])
commandList.push(["MaxThreadsBuffer","commands/_MaxThreadsBuffer.htm"])
commandList.push(["MaxThreadsPerHotkey","commands/_MaxThreadsPerHotkey.htm"])
commandList.push(["Menu","commands/Menu.htm"])
commandList.push(["MenuGetHandle","commands/MenuGetHandle.htm"])
commandList.push(["MenuGetName","commands/MenuGetName.htm"])
commandList.push(["Menu Bar (GUI)","commands/Gui.htm#Menu"])
commandList.push(["Menu Icon","commands/Menu.htm#MenuIcon"])
commandList.push(["message list (WM_*)","misc/SendMessageList.htm"])
commandList.push(["messages, receiving","commands/OnMessage.htm"])
commandList.push(["messages, sending","commands/PostMessage.htm"])
commandList.push(["meta-functions (Objects)","Objects.htm#Meta_Functions"])
commandList.push(["MinIndex()","objects/Object.htm#MinMaxIndex"])
commandList.push(["Mod()","commands/Math.htm#Mod"])
commandList.push(["modal (always on top)","commands/MsgBox.htm"])
commandList.push(["modulo, mod()","commands/Math.htm#Mod"])
commandList.push(["MonthCal controls (GUI)","commands/GuiControls.htm#MonthCal"])
commandList.push(["mouse hook","commands/_InstallMouseHook.htm"])
commandList.push(["mouse speed","commands/SetDefaultMouseSpeed.htm"])
commandList.push(["mouse wheel","commands/Click.htm"])
commandList.push(["MouseClick","commands/MouseClick.htm"])
commandList.push(["MouseClickDrag","commands/MouseClickDrag.htm"])
commandList.push(["MouseGetPos","commands/MouseGetPos.htm"])
commandList.push(["MouseMove","commands/MouseMove.htm"])
commandList.push(["move a window","commands/WinMove.htm"])
commandList.push(["move file","commands/FileMove.htm"])
commandList.push(["move folder/directory","commands/FileMoveDir.htm"])
commandList.push(["MsgBox","commands/MsgBox.htm"])
commandList.push(["multiply","commands/EnvMult.htm"])
commandList.push(["mute (changing it)","commands/SoundSet.htm"])
commandList.push(["NewEnum method (Object)","objects/Object.htm#NewEnum"])
commandList.push(["NoTimers","commands/Thread.htm"])
commandList.push(["NoTrayIcon","commands/_NoTrayIcon.htm"])
commandList.push(["number","commands/IfIs.htm"])
commandList.push(["number format","commands/SetFormat.htm"])
commandList.push(["NumGet","commands/NumGet.htm"])
commandList.push(["NumPut","commands/NumPut.htm"])
commandList.push(["Objects (general information)","Objects.htm"])
commandList.push(["Object functions and methods","objects/Object.htm"])
commandList.push(["ObjAddRef()","commands/ObjAddRef.htm"])
commandList.push(["ObjBindMethod()","commands/ObjBindMethod.htm"])
commandList.push(["ObjClone()","objects/Object.htm#Clone"])
commandList.push(["ObjDelete()","objects/Object.htm#Delete"])
commandList.push(["ObjGetAddress()","objects/Object.htm#GetAddress"])
commandList.push(["ObjGetCapacity()","objects/Object.htm#GetCapacity"])
commandList.push(["ObjHasKey()","objects/Object.htm#HasKey"])
commandList.push(["ObjInsert()","objects/Object.htm#Insert"])
commandList.push(["ObjInsertAt()","objects/Object.htm#InsertAt"])
commandList.push(["ObjLength()","objects/Object.htm#Length"])
commandList.push(["ObjMaxIndex()","objects/Object.htm#MinMaxIndex"])
commandList.push(["ObjMinIndex()","objects/Object.htm#MinMaxIndex"])
commandList.push(["ObjNewEnum()","objects/Object.htm#NewEnum"])
commandList.push(["ObjPop()","objects/Object.htm#Pop"])
commandList.push(["ObjPush()","objects/Object.htm#Push"])
commandList.push(["ObjRawSet()","objects/Object.htm#RawSet"])
commandList.push(["ObjRelease()","commands/ObjAddRef.htm"])
commandList.push(["ObjRemove()","objects/Object.htm#Remove"])
commandList.push(["ObjRemoveAt()","objects/Object.htm#RemoveAt"])
commandList.push(["ObjSetCapacity()","objects/Object.htm#SetCapacity"])
commandList.push(["OnClipboardChange","commands/OnClipboardChange.htm"])
commandList.push(["OnExit","commands/OnExit.htm"])
commandList.push(["OnMessage()","commands/OnMessage.htm"])
commandList.push(["open file","commands/FileOpen.htm"])
commandList.push(["operators in expressions","Variables.htm#Operators"])
commandList.push(["Ord()","Functions.htm#Ord"])
commandList.push(["OutputDebug","commands/OutputDebug.htm"])
commandList.push(["OwnDialogs (GUI)","commands/Gui.htm#OwnDialogs"])
commandList.push(["Owner of a GUI window","commands/Gui.htm#Owner"])
commandList.push(["parameters passed into a script","Scripts.htm#cmd"])
commandList.push(["parse a string (Loop)","commands/LoopParse.htm"])
commandList.push(["parse a string (StringSplit)","commands/StringSplit.htm"])
commandList.push(["Pause","commands/Pause.htm"])
commandList.push(["performance of scripts","misc/Performance.htm"])
commandList.push(["Picture controls (GUI)","commands/GuiControls.htm#Picture"])
commandList.push(["PID (Process ID)","commands/Process.htm"])
commandList.push(["PixelGetColor","commands/PixelGetColor.htm"])
commandList.push(["PixelSearch","commands/PixelSearch.htm"])
commandList.push(["play a sound or video file","commands/SoundPlay.htm"])
commandList.push(["Pop method (Object)","objects/Object.htm#Pop"])
commandList.push(["PostMessage","commands/PostMessage.htm"])
commandList.push(["power (exponentiation)","Variables.htm#pow"])
commandList.push(["prefix and suffix keys","Hotkeys.htm"])
commandList.push(["print a file","commands/Run.htm"])
commandList.push(["priority of a process","commands/Process.htm"])
commandList.push(["priority of a thread","commands/Thread.htm"])
commandList.push(["Process","commands/Process.htm"])
commandList.push(["ProgramFiles","Variables.htm#ProgramFiles"])
commandList.push(["Progress","commands/Progress.htm"])
commandList.push(["Progress controls (GUI)","commands/GuiControls.htm#Progress"])
commandList.push(["properties (Objects)","Objects.htm#Custom_Classes_property"])
commandList.push(["properties of a file or folder","commands/Run.htm"])
commandList.push(["Push method (Object)","objects/Object.htm#Push"])
commandList.push(["quit script","commands/ExitApp.htm"])
commandList.push(["Radio controls (GUI)","commands/GuiControls.htm#Radio"])
commandList.push(["Random","commands/Random.htm"])
commandList.push(["RawRead method (File object)","objects/File.htm#RawRead"])
commandList.push(["RawWrite method (File object)","objects/File.htm#RawWrite"])
commandList.push(["read file","commands/FileRead.htm"])
commandList.push(["Read method (File object)","objects/File.htm#Read"])
commandList.push(["READONLY","commands/FileGetAttrib.htm"])
commandList.push(["reboot","commands/Shutdown.htm"])
commandList.push(["Reference-Counting","Objects.htm#Refs"])
commandList.push(["REG_BINARY","commands/RegRead.htm"])
commandList.push(["REG_DWORD","commands/RegRead.htm"])
commandList.push(["REG_EXPAND_SZ","commands/RegRead.htm"])
commandList.push(["REG_MULTI_SZ","commands/RegRead.htm"])
commandList.push(["REG_SZ","commands/RegRead.htm"])
commandList.push(["RegDelete","commands/RegDelete.htm"])
commandList.push(["RegEx: Quick Reference","misc/RegEx-QuickRef.htm"])
commandList.push(["RegEx: Callouts","misc/RegExCallout.htm"])
commandList.push(["RegEx: SetTitleMatchMode RegEx","commands/SetTitleMatchMode.htm#RegEx"])
commandList.push(["RegExMatch()","commands/RegExMatch.htm"])
commandList.push(["RegExReplace()","commands/RegExReplace.htm"])
commandList.push(["RegisterCallback()","commands/RegisterCallback.htm"])
commandList.push(["registry loop","commands/LoopReg.htm"])
commandList.push(["RegRead","commands/RegRead.htm"])
commandList.push(["Regular Expression Callouts","misc/RegExCallout.htm"])
commandList.push(["regular expressions: Quick Reference","misc/RegEx-QuickRef.htm"])
commandList.push(["regular expressions: RegExMatch()","commands/RegExMatch.htm"])
commandList.push(["regular expressions: RegExReplace()","commands/RegExReplace.htm"])
commandList.push(["regular expressions: SetTitleMatchMode RegEx","commands/SetTitleMatchMode.htm#RegEx"])
commandList.push(["RegWrite","commands/RegWrite.htm"])
commandList.push(["Reload","commands/Reload.htm"])
commandList.push(["remap joystick","misc/RemapJoystick.htm"])
commandList.push(["remap keys or mouse buttons","misc/Remap.htm"])
commandList.push(["remote controls, hand-held","scripts/WinLIRC.htm"])
commandList.push(["remove folder/directory","commands/FileRemoveDir.htm"])
commandList.push(["Remove method (Object)","objects/Object.htm#Remove"])
commandList.push(["RemoveAt method (Object)","objects/Object.htm#RemoveAt"])
commandList.push(["rename file","commands/FileMove.htm"])
commandList.push(["resize a window","commands/WinMove.htm"])
commandList.push(["restart the computer","commands/Shutdown.htm"])
commandList.push(["Return","commands/Return.htm"])
commandList.push(["RGB color names","commands/Progress.htm#colors"])
commandList.push(["RGB colors","commands/PixelGetColor.htm"])
commandList.push(["Round()","commands/Math.htm#Round"])
commandList.push(["rounding a number","commands/Math.htm#Round"])
commandList.push(["RTrim()","commands/Trim.htm"])
commandList.push(["Run","commands/Run.htm"])
commandList.push(["RunAs","commands/RunAs.htm"])
commandList.push(["RunWait","commands/Run.htm"])
commandList.push(["SB_SetIcon()","commands/GuiControls.htm#SB_SetIcon"])
commandList.push(["SB_SetParts()","commands/GuiControls.htm#SB_SetParts"])
commandList.push(["SB_SetText()","commands/GuiControls.htm#SB_SetText"])
commandList.push(["scan code","commands/Send.htm#vk"])
commandList.push(["scientific notation","commands/SetFormat.htm#sci"])
commandList.push(["Script Showcase","scripts/index.htm"])
commandList.push(["Scripts","Scripts.htm"])
commandList.push(["select file","commands/FileSelectFile.htm"])
commandList.push(["select folder","commands/FileSelectFolder.htm"])
commandList.push(["Send","commands/Send.htm"])
commandList.push(["SendEvent","commands/Send.htm#SendEvent"])
commandList.push(["sending data between scripts","commands/OnMessage.htm#SendString"])
commandList.push(["SendInput","commands/Send.htm#SendInputDetail"])
commandList.push(["SendLevel","commands/SendLevel.htm"])
commandList.push(["SendMessage","commands/PostMessage.htm"])
commandList.push(["SendMode","commands/SendMode.htm"])
commandList.push(["SendPlay","commands/Send.htm#SendPlayDetail"])
commandList.push(["SendRaw","commands/Send.htm"])
commandList.push(["SetBatchLines","commands/SetBatchLines.htm"])
commandList.push(["SetCapacity method (Object)","objects/Object.htm#SetCapacity"])
commandList.push(["SetCapsLockState","commands/SetNumScrollCapsLockState.htm"])
commandList.push(["SetControlDelay","commands/SetControlDelay.htm"])
commandList.push(["SetDefaultMouseSpeed","commands/SetDefaultMouseSpeed.htm"])
commandList.push(["SetEnv","commands/SetEnv.htm"])
commandList.push(["SetFormat","commands/SetFormat.htm"])
commandList.push(["SetKeyDelay","commands/SetKeyDelay.htm"])
commandList.push(["SetMouseDelay","commands/SetMouseDelay.htm"])
commandList.push(["SetNumLockState","commands/SetNumScrollCapsLockState.htm"])
commandList.push(["SetRegView","commands/SetRegView.htm"])
commandList.push(["SetScrollLockState","commands/SetNumScrollCapsLockState.htm"])
commandList.push(["SetStoreCapslockMode","commands/SetStoreCapslockMode.htm"])
commandList.push(["SetTimer","commands/SetTimer.htm"])
commandList.push(["SetTitleMatchMode","commands/SetTitleMatchMode.htm"])
commandList.push(["SetWinDelay","commands/SetWinDelay.htm"])
commandList.push(["SetWorkingDir","commands/SetWorkingDir.htm"])
commandList.push(["short file name (8.3 format)","commands/LoopFile.htm#LoopFileShortPath"])
commandList.push(["short-circuit boolean evaluation","Functions.htm#ShortCircuit"])
commandList.push(["shortcut file","commands/FileCreateShortcut.htm"])
commandList.push(["Shutdown","commands/Shutdown.htm"])
commandList.push(["Silent Install/Uninstall","Scripts.htm#install"])
commandList.push(["Sin()","commands/Math.htm#Sin"])
commandList.push(["SingleInstance","commands/_SingleInstance.htm"])
commandList.push(["size of a file/folder","commands/FileGetSize.htm"])
commandList.push(["size of a window","commands/WinGetPos.htm"])
commandList.push(["Sleep","commands/Sleep.htm"])
commandList.push(["Slider controls (GUI)","commands/GuiControls.htm#Slider"])
commandList.push(["Sort","commands/Sort.htm"])
commandList.push(["SoundBeep","commands/SoundBeep.htm"])
commandList.push(["SoundGet","commands/SoundGet.htm"])
commandList.push(["SoundGetWaveVolume","commands/SoundGetWaveVolume.htm"])
commandList.push(["SoundPlay","commands/SoundPlay.htm"])
commandList.push(["SoundSet","commands/SoundSet.htm"])
commandList.push(["SoundSetWaveVolume","commands/SoundSetWaveVolume.htm"])
commandList.push(["space","commands/IfIs.htm"])
commandList.push(["speed of a script","commands/SetBatchLines.htm"])
commandList.push(["spinner control (GUI)","commands/GuiControls.htm#UpDown"])
commandList.push(["SplashImage","commands/Progress.htm"])
commandList.push(["SplashTextOff","commands/SplashTextOn.htm"])
commandList.push(["SplashTextOn","commands/SplashTextOn.htm"])
commandList.push(["SplitPath","commands/SplitPath.htm"])
commandList.push(["splitting long lines","Scripts.htm#continuation"])
commandList.push(["Sqrt()","commands/Math.htm#Sqrt"])
commandList.push(["standard library","Functions.htm#lib"])
commandList.push(["standard output (stdout)","commands/FileAppend.htm"])
commandList.push(["static variables","Functions.htm#static"])
commandList.push(["StatusBar controls (GUI)","commands/GuiControls.htm#StatusBar"])
commandList.push(["StatusBarGetText","commands/StatusBarGetText.htm"])
commandList.push(["StatusBarWait","commands/StatusBarWait.htm"])
commandList.push(["StrGet()","commands/StrPutGet.htm"])
commandList.push(["string (search for)","commands/InStr.htm"])
commandList.push(["string: InStr()","commands/InStr.htm"])
commandList.push(["string: SubStr()","commands/SubStr.htm"])
commandList.push(["StringCaseSense","commands/StringCaseSense.htm"])
commandList.push(["StringGetPos","commands/StringGetPos.htm"])
commandList.push(["StringLeft","commands/StringLeft.htm"])
commandList.push(["StringLen","commands/StringLen.htm"])
commandList.push(["StringLower","commands/StringLower.htm"])
commandList.push(["StringMid","commands/StringMid.htm"])
commandList.push(["StringReplace","commands/StringReplace.htm"])
commandList.push(["StringRight","commands/StringLeft.htm"])
commandList.push(["StringSplit","commands/StringSplit.htm"])
commandList.push(["StringTrimLeft","commands/StringTrimLeft.htm"])
commandList.push(["StringTrimRight","commands/StringTrimLeft.htm"])
commandList.push(["StringUpper","commands/StringLower.htm"])
commandList.push(["StrLen()","commands/StringLen.htm"])
commandList.push(["StrPut()","commands/StrPutGet.htm"])
commandList.push(["StrReplace()","commands/StringReplace.htm"])
commandList.push(["StrSplit()","commands/StringSplit.htm"])
commandList.push(["structures, via DllCall","commands/DllCall.htm#struct"])
commandList.push(["styles for GUI command","misc/Styles.htm"])
commandList.push(["SubStr()","commands/SubStr.htm"])
commandList.push(["subtract","commands/EnvSub.htm"])
commandList.push(["Super-global variables","Functions.htm#SuperGlobal"])
commandList.push(["Suspend","commands/Suspend.htm"])
commandList.push(["suspend or hibernate","commands/Shutdown.htm#Suspend"])
commandList.push(["SysGet","commands/SysGet.htm"])
commandList.push(["Tab controls (GUI)","commands/GuiControls.htm#Tab"])
commandList.push(["Tan()","commands/Math.htm#Tan"])
commandList.push(["terminate a window","commands/WinKill.htm"])
commandList.push(["terminate script","commands/ExitApp.htm"])
commandList.push(["ternary operator (?:)","Variables.htm#ternary"])
commandList.push(["Text controls (GUI)","commands/GuiControls.htm#Text"])
commandList.push(["Thread","commands/Thread.htm"])
commandList.push(["threads","misc/Threads.htm"])
commandList.push(["Throw","commands/Throw.htm"])
commandList.push(["time","commands/IfIs.htm"])
commandList.push(["Timer (timed subroutines)","commands/SetTimer.htm"])
commandList.push(["times and dates (compare)","commands/EnvSub.htm"])
commandList.push(["times and dates (math)","commands/EnvAdd.htm"])
commandList.push(["times and dates (of files)","commands/FileSetTime.htm"])
commandList.push(["title of a window","commands/WinSetTitle.htm"])
commandList.push(["ToolTip","commands/ToolTip.htm"])
commandList.push(["Transform","commands/Transform.htm"])
commandList.push(["transparency of a window","commands/WinSet.htm#trans"])
commandList.push(["tray icon","commands/_NoTrayIcon.htm"])
commandList.push(["tray menu (customizing)","commands/Menu.htm"])
commandList.push(["TrayTip","commands/TrayTip.htm"])
commandList.push(["TreeView controls (GUI)","commands/TreeView.htm"])
commandList.push(["Trim","commands/AutoTrim.htm"])
commandList.push(["Trim()","commands/Trim.htm"])
commandList.push(["True","Variables.htm#Boolean"])
commandList.push(["Try","commands/Try.htm"])
commandList.push(["Tutorial","Tutorial.htm"])
commandList.push(["TV_Add()","commands/TreeView.htm#TV_Add"])
commandList.push(["TV_Delete()","commands/TreeView.htm#TV_Delete"])
commandList.push(["TV_Get()","commands/TreeView.htm#TV_Get"])
commandList.push(["TV_GetChild()","commands/TreeView.htm#TV_GetChild"])
commandList.push(["TV_GetCount()","commands/TreeView.htm#TV_GetCount"])
commandList.push(["TV_GetNext()","commands/TreeView.htm#TV_GetNext"])
commandList.push(["TV_GetParent()","commands/TreeView.htm#TV_GetParent"])
commandList.push(["TV_GetPrev()","commands/TreeView.htm#TV_GetPrev"])
commandList.push(["TV_GetSelection()","commands/TreeView.htm#TV_GetSelection"])
commandList.push(["TV_GetText()","commands/TreeView.htm#TV_GetText"])
commandList.push(["TV_Modify()","commands/TreeView.htm#TV_Modify"])
commandList.push(["TV_SetImageList()","commands/TreeView.htm#TV_SetImageList"])
commandList.push(["Unicode text and clipboard","commands/Transform.htm"])
commandList.push(["Until","commands/Until.htm"])
commandList.push(["UpDown controls (GUI)","commands/GuiControls.htm#UpDown"])
commandList.push(["URLDownloadToFile","commands/URLDownloadToFile.htm"])
commandList.push(["UseHook","commands/_UseHook.htm"])
commandList.push(["user (run as a different user)","commands/RunAs.htm"])
commandList.push(["user library","Functions.htm#lib"])
commandList.push(["variables, assigning to","commands/SetEnv.htm"])
commandList.push(["variables, built-in","Variables.htm#BuiltIn"])
commandList.push(["variables, comparing them","commands/IfEqual.htm"])
commandList.push(["variables, ListVars","commands/ListVars.htm"])
commandList.push(["variables, MAIN","Variables.htm"])
commandList.push(["variables, type of data","commands/IfIs.htm"])
commandList.push(["variadic functions","Functions.htm#Variadic"])
commandList.push(["variants (duplicate hotkeys and hotstrings)","commands/_IfWinActive.htm#variant"])
commandList.push(["VarSetCapacity()","commands/VarSetCapacity.htm"])
commandList.push(["VBScript, embedded/inline","commands/DllCall.htm#COM"])
commandList.push(["version of a file","commands/FileGetVersion.htm"])
commandList.push(["virtual key","commands/Send.htm#vk"])
commandList.push(["volume (changing it)","commands/SoundSet.htm"])
commandList.push(["wait (sleep)","commands/Sleep.htm"])
commandList.push(["wait for a key to be released or pressed","commands/KeyWait.htm"])
commandList.push(["Wheel hotkeys for mouse","Hotkeys.htm#Wheel"])
commandList.push(["Wheel, simulating rotation","commands/Click.htm"])
commandList.push(["While-loop","commands/While.htm"])
commandList.push(["whitespace","commands/AutoTrim.htm"])
commandList.push(["wildcards (for files & folders)","commands/LoopFile.htm"])
commandList.push(["WinActivate","commands/WinActivate.htm"])
commandList.push(["WinActivateBottom","commands/WinActivateBottom.htm"])
commandList.push(["WinActivateForce","commands/_WinActivateForce.htm"])
commandList.push(["WinActive()","commands/WinActive.htm"])
commandList.push(["Winamp automation","misc/Winamp.htm"])
commandList.push(["WinClose","commands/WinClose.htm"])
commandList.push(["window group","misc/WinTitle.htm#ahk_group"])
commandList.push(["window messages","misc/SendMessageList.htm"])
commandList.push(["WinExist()","commands/WinExist.htm"])
commandList.push(["WinGet","commands/WinGet.htm"])
commandList.push(["WinGetActiveStats","commands/WinGetActiveStats.htm"])
commandList.push(["WinGetActiveTitle","commands/WinGetActiveTitle.htm"])
commandList.push(["WinGetClass","commands/WinGetClass.htm"])
commandList.push(["WinGetPos","commands/WinGetPos.htm"])
commandList.push(["WinGetText","commands/WinGetText.htm"])
commandList.push(["WinGetTitle","commands/WinGetTitle.htm"])
commandList.push(["WinHide","commands/WinHide.htm"])
commandList.push(["WinKill","commands/WinKill.htm"])
commandList.push(["WinLIRC, connecting to","scripts/WinLIRC.htm"])
commandList.push(["WinMaximize","commands/WinMaximize.htm"])
commandList.push(["WinMenuSelectItem","commands/WinMenuSelectItem.htm"])
commandList.push(["WinMinimize","commands/WinMinimize.htm"])
commandList.push(["WinMinimizeAll","commands/WinMinimizeAll.htm"])
commandList.push(["WinMinimizeAllUndo","commands/WinMinimizeAll.htm"])
commandList.push(["WinMove","commands/WinMove.htm"])
commandList.push(["WinRestore","commands/WinRestore.htm"])
commandList.push(["WinSet","commands/WinSet.htm"])
commandList.push(["WinSetTitle","commands/WinSetTitle.htm"])
commandList.push(["WinShow","commands/WinShow.htm"])
commandList.push(["WinSize (via WinMove)","commands/WinMove.htm"])
commandList.push(["WinTitle","misc/WinTitle.htm"])
commandList.push(["WinWait","commands/WinWait.htm"])
commandList.push(["WinWaitActive","commands/WinWaitActive.htm"])
commandList.push(["WinWaitClose","commands/WinWaitClose.htm"])
commandList.push(["WinWaitNotActive","commands/WinWaitActive.htm"])
commandList.push(["WM_* (Windows messages)","misc/SendMessageList.htm"])
commandList.push(["WM_COPYDATA","commands/OnMessage.htm#SendString"])
commandList.push(["working directory","commands/SetWorkingDir.htm"])
commandList.push(["wParam","commands/PostMessage.htm"])
commandList.push(["write file","commands/FileAppend.htm"])
commandList.push(["Write method (File object)","objects/File.htm#Write"])
commandList.push(["WS_* (GUI styles)","misc/Styles.htm"])
commandList.push(["XButton","commands/Click.htm"])
commandList.push(["YYYYMMDDHH24MISS","commands/FileSetTime.htm#YYYYMMDD"])
commandList.push(["{Blind}","commands/Send.htm#blind"])
