;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global D3D11 := {}
D3D11.IID_ID3D11DeviceChild := "{1841e5c8-16b0-489b-bcc8-44cfb0d5deae}"
D3D11.IID_ID3D11DepthStencilState := "{03823efb-8d8f-4e1c-9aa2-f64bb2cbfdf1}"
D3D11.IID_ID3D11BlendState := "{75b68faa-347d-4159-8f45-a0640f01cd9a}"
D3D11.IID_ID3D11RasterizerState := "{9bb4ab81-ab1a-4d8f-b506-fc04200b6ee7}"
D3D11.IID_ID3D11Resource := "{dc8e63f3-d12b-4952-b47b-5e45026a862d}"
D3D11.IID_ID3D11Buffer := "{48570b85-d1ee-4fcd-a250-eb350722b037}"
D3D11.IID_ID3D11Texture1D := "{f8fb5c27-c6b3-4f75-a4c8-439af2ef564c}"
D3D11.IID_ID3D11Texture2D := "{6f15aaf2-d208-4e89-9ab4-489535d34f9c}"
D3D11.IID_ID3D11Texture3D := "{037e866e-f56d-4357-a8af-9dabbe6e250e}"
D3D11.IID_ID3D11View := "{839d1216-bb2e-412b-b7f4-a9dbebe08ed1}"
D3D11.IID_ID3D11ShaderResourceView := "{b0e06fe0-8192-4e1a-b1ca-36d7414710b2}"
D3D11.IID_ID3D11RenderTargetView := "{dfdba067-0b8d-4865-875b-d7b4516cc164}"
D3D11.IID_ID3D11DepthStencilView := "{9fdac92a-1876-48c3-afad-25b94f84a9b6}"
D3D11.IID_ID3D11UnorderedAccessView := "{28acf509-7f5c-48f6-8611-f316010a6380}"
D3D11.IID_ID3D11VertexShader := "{3b301d64-d678-4289-8897-22f8928b72f3}"
D3D11.IID_ID3D11HullShader := "{8e5c6061-628a-4c8e-8264-bbe45cb3d5dd}"
D3D11.IID_ID3D11DomainShader := "{f582c508-0f36-490c-9977-31eece268cfa}"
D3D11.IID_ID3D11GeometryShader := "{38325b96-effb-4022-ba02-2e795b70275c}"
D3D11.IID_ID3D11PixelShader := "{ea82e40d-51dc-4f33-93d4-db7c9125ae8c}"
D3D11.IID_ID3D11ComputeShader := "{4f5b196e-c2bd-495e-bd01-1fded38e4969}"
D3D11.IID_ID3D11InputLayout := "{e4819ddc-4cf0-4025-bd26-5de82a3e07b7}"
D3D11.IID_ID3D11SamplerState := "{da6fea51-564c-4487-9810-f0d0f9b4e3a5}"
D3D11.IID_ID3D11Asynchronous := "{4b35d0cd-1e15-4258-9c98-1b1333f6dd3b}"
D3D11.IID_ID3D11Query := "{d6c00747-87b7-425e-b84d-44d108560afd}"
D3D11.IID_ID3D11Predicate := "{9eb576dd-9f77-4d86-81aa-8bab5fe490e2}"
D3D11.IID_ID3D11Counter := "{6e8c49fb-a371-4770-b440-29086022b741}"
D3D11.IID_ID3D11ClassInstance := "{a6cd7faa-b0b7-4a2f-9436-8662a65797cb}"
D3D11.IID_ID3D11ClassLinkage := "{ddf57cba-9543-46e4-a12b-f207a0fe7fed}"
D3D11.IID_ID3D11CommandList := "{a24bc4d1-769e-43f7-8013-98ff566c18e2}"
D3D11.IID_ID3D11DeviceContext := "{c0bfa96c-e089-44fb-8eaf-26f8796190da}"
D3D11.IID_ID3D11Device := "{db6f6ddb-ac77-4e88-8253-819df9bbf140}"

D3D11.ID3D11Asynchronous:= {}
D3D11.ID3D11Asynchronous.name := "ID3D11Asynchronous"
D3D11.ID3D11Asynchronous.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDataSize)(This)
"
)

D3D11.ID3D11BlendState:= {}
D3D11.ID3D11BlendState.name := "ID3D11BlendState"
D3D11.ID3D11BlendState.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11Buffer:= {}
D3D11.ID3D11Buffer.name := "ID3D11Buffer"
D3D11.ID3D11Buffer.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,pResourceDimension)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11ClassInstance:= {}
D3D11.ID3D11ClassInstance.name := "ID3D11ClassInstance"
D3D11.ID3D11ClassInstance.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetClassLinkage)(This,ppLinkage)
STDMETHOD(GetDesc)(This,pDesc)
STDMETHOD(GetInstanceName)(This,pInstanceName,pBufferLength)
STDMETHOD(GetTypeName)(This,pTypeName,pBufferLength)
"
)

D3D11.ID3D11ClassLinkage:= {}
D3D11.ID3D11ClassLinkage.name := "ID3D11ClassLinkage"
D3D11.ID3D11ClassLinkage.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetClassInstance)(This,pClassInstanceName,InstanceIndex,ppInstance)
STDMETHOD(CreateClassInstance)(This,pClassTypeName,ConstantBufferOffset,ConstantVectorOffset,TextureOffset,SamplerOffset,ppInstance)
"
)

D3D11.ID3D11CommandList:= {}
D3D11.ID3D11CommandList.name := "ID3D11CommandList"
D3D11.ID3D11CommandList.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetContextFlags)(This)
"
)

D3D11.ID3D11ComputeShader:= {}
D3D11.ID3D11ComputeShader.name := "ID3D11ComputeShader"
D3D11.ID3D11ComputeShader.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D11.ID3D11Counter:= {}
D3D11.ID3D11Counter.name := "ID3D11Counter"
D3D11.ID3D11Counter.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDataSize)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11DepthStencilState:= {}
D3D11.ID3D11DepthStencilState.name := "ID3D11DepthStencilState"
D3D11.ID3D11DepthStencilState.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11DepthStencilView:= {}
D3D11.ID3D11DepthStencilView.name := "ID3D11DepthStencilView"
D3D11.ID3D11DepthStencilView.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetResource)(This,ppResource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11Device:= {}
D3D11.ID3D11Device.name := "ID3D11Device"
D3D11.ID3D11Device.def :=
( 
"
STDMETHOD(QueryInterface) (This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(CreateBuffer)(This,pDesc,pInitialData,ppBuffer)
STDMETHOD(CreateTexture1D)(This,pDesc,pInitialData,ppTexture1D)
STDMETHOD(CreateTexture2D)(This,pDesc,pInitialData,ppTexture2D)
STDMETHOD(CreateTexture3D)(This,pDesc,pInitialData,ppTexture3D)
STDMETHOD(CreateShaderResourceView)(This,pResource,pDesc,ppSRView)
STDMETHOD(CreateUnorderedAccessView)(This,pResource,pDesc,ppUAView)
STDMETHOD(CreateRenderTargetView)(This,pResource,pDesc,ppRTView)
STDMETHOD(CreateDepthStencilView)(This,pResource,pDesc,ppDepthStencilView)
STDMETHOD(CreateInputLayout)(This,pInputElementDescs,NumElements,pShaderBytecodeWithInputSignature,BytecodeLength,ppInputLayout)
STDMETHOD(CreateVertexShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppVertexShader)
STDMETHOD(CreateGeometryShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppGeometryShader)
STDMETHOD(CreateGeometryShaderWithStreamOutput)(This,pShaderBytecode,BytecodeLength,pSODeclaration,NumEntries,pBufferStrides,NumStrides,RasterizedStream,pClassLinkage,ppGeometryShader)
STDMETHOD(CreatePixelShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppPixelShader)
STDMETHOD(CreateHullShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppHullShader)
STDMETHOD(CreateDomainShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppDomainShader)
STDMETHOD(CreateComputeShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppComputeShader)
STDMETHOD(CreateClassLinkage)(This,ppLinkage)
STDMETHOD(CreateBlendState)(This,pBlendStateDesc,ppBlendState)
STDMETHOD(CreateDepthStencilState)(This,pDepthStencilDesc,ppDepthStencilState)
STDMETHOD(CreateRasterizerState)(This,pRasterizerDesc,ppRasterizerState)
STDMETHOD(CreateSamplerState)(This,pSamplerDesc,ppSamplerState)
STDMETHOD(CreateQuery)(This,pQueryDesc,ppQuery)
STDMETHOD(CreatePredicate)(This,pPredicateDesc,ppPredicate)
STDMETHOD(CreateCounter)(This,pCounterDesc,ppCounter)
STDMETHOD(CreateDeferredContext)(This,ContextFlags,ppDeferredContext)
STDMETHOD(OpenSharedResource)(This,hResource,ReturnedInterface,ppResource)
STDMETHOD(CheckFormatSupport)(This,Format,pFormatSupport)
STDMETHOD(CheckMultisampleQualityLevels)(This,Format,SampleCount,pNumQualityLevels)
STDMETHOD(CheckCounterInfo)(This,pCounterInfo)
STDMETHOD(CheckCounter)(This,pDesc,pType,pActiveCounters,szName,pNameLength,szUnits,pUnitsLength,szDescription,pDescriptionLength)
STDMETHOD(CheckFeatureSupport)(This,Feature,pFeatureSupportData,FeatureSupportDataSize)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetFeatureLevel)(This)
STDMETHOD(GetCreationFlags)(This)
STDMETHOD(GetDeviceRemovedReason)(This)
STDMETHOD(GetImmediateContext)(This,ppImmediateContext)
STDMETHOD(SetExceptionMode)(This,RaiseFlags)
STDMETHOD(GetExceptionMode)(This)
"
)

D3D11.ID3D11DeviceChild:= {}
D3D11.ID3D11DeviceChild.name := "ID3D11DeviceChild"
D3D11.ID3D11DeviceChild.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D11.ID3D11DeviceContext:= {}
D3D11.ID3D11DeviceContext.name := "ID3D11DeviceContext"
D3D11.ID3D11DeviceContext.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(VSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(PSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(PSSetShader)(This,pPixelShader,ppClassInstances,NumClassInstances)
STDMETHOD(PSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(VSSetShader)(This,pVertexShader,ppClassInstances,NumClassInstances)
STDMETHOD(DrawIndexed)(This,IndexCount,StartIndexLocation,BaseVertexLocation)
STDMETHOD(Draw)(This,VertexCount,StartVertexLocation)
STDMETHOD(Map)(This,pResource,Subresource,MapType,MapFlags,pMappedResource)
STDMETHOD(Unmap)(This,pResource,Subresource)
STDMETHOD(PSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(IASetInputLayout)(This,pInputLayout)
STDMETHOD(IASetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)
STDMETHOD(IASetIndexBuffer)(This,pIndexBuffer,Format,Offset)
STDMETHOD(DrawIndexedInstanced)(This,IndexCountPerInstance,InstanceCount,StartIndexLocation,BaseVertexLocation,StartInstanceLocation)
STDMETHOD(DrawInstanced)(This,VertexCountPerInstance,InstanceCount,StartVertexLocation,StartInstanceLocation)
STDMETHOD(GSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(GSSetShader)(This,pShader,ppClassInstances,NumClassInstances)
STDMETHOD(IASetPrimitiveTopology)(This,Topology)
STDMETHOD(VSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(VSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(Begin)(This,pAsync)
STDMETHOD(End)(This,pAsync)
STDMETHOD(GetData)(This,pAsync,pData,DataSize,GetDataFlags)
STDMETHOD(SetPredication)(This,pPredicate,PredicateValue)
STDMETHOD(GSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(GSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(OMSetRenderTargets)(This,NumViews,ppRenderTargetViews,pDepthStencilView)
STDMETHOD(OMSetRenderTargetsAndUnorderedAccessViews)(This,NumRTVs,ppRenderTargetViews,pDepthStencilView,UAVStartSlot,NumUAVs,ppUnorderedAccessViews,pUAVInitialCounts)
STDMETHOD(OMSetBlendState)(This,pBlendState,BlendFactor,SampleMask)
STDMETHOD(OMSetDepthStencilState)(This,pDepthStencilState,StencilRef)
STDMETHOD(SOSetTargets)(This,NumBuffers,ppSOTargets,pOffsets)
STDMETHOD(DrawAuto)(This)
STDMETHOD(DrawIndexedInstancedIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)
STDMETHOD(DrawInstancedIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)
STDMETHOD(Dispatch)(This,ThreadGroupCountX,ThreadGroupCountY,ThreadGroupCountZ)
STDMETHOD(DispatchIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)
STDMETHOD(RSSetState)(This,pRasterizerState)
STDMETHOD(RSSetViewports)(This,NumViewports,pViewports)
STDMETHOD(RSSetScissorRects)(This,NumRects,pRects)
STDMETHOD(CopySubresourceRegion)(This,pDstResource,DstSubresource,DstX,DstY,DstZ,pSrcResource,SrcSubresource,pSrcBox)
STDMETHOD(CopyResource)(This,pDstResource,pSrcResource)
STDMETHOD(UpdateSubresource)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch)
STDMETHOD(CopyStructureCount)(This,pDstBuffer,DstAlignedByteOffset,pSrcView)
STDMETHOD(ClearRenderTargetView)(This,pRenderTargetView,ColorRGBA)
STDMETHOD(ClearUnorderedAccessViewUint)(This,pUnorderedAccessView,Values)
STDMETHOD(ClearUnorderedAccessViewFloat)(This,pUnorderedAccessView,Values)
STDMETHOD(ClearDepthStencilView)(This,pDepthStencilView,ClearFlags,Depth,Stencil)
STDMETHOD(GenerateMips)(This,pShaderResourceView)
STDMETHOD(SetResourceMinLOD)(This,pResource,MinLOD)
STDMETHOD(GetResourceMinLOD)(This,pResource)
STDMETHOD(ResolveSubresource)(This,pDstResource,DstSubresource,pSrcResource,SrcSubresource,Format)
STDMETHOD(ExecuteCommandList)(This,pCommandList,RestoreContextState)
STDMETHOD(HSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(HSSetShader)(This,pHullShader,ppClassInstances,NumClassInstances)
STDMETHOD(HSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(HSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(DSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(DSSetShader)(This,pDomainShader,ppClassInstances,NumClassInstances)
STDMETHOD(DSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(DSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(CSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(CSSetUnorderedAccessViews)(This,StartSlot,NumUAVs,ppUnorderedAccessViews,pUAVInitialCounts)
STDMETHOD(CSSetShader)(This,pComputeShader,ppClassInstances,NumClassInstances)
STDMETHOD(CSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(CSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(VSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(PSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(PSGetShader)(This,ppPixelShader,ppClassInstances,pNumClassInstances)
STDMETHOD(PSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(VSGetShader)(This,ppVertexShader,ppClassInstances,pNumClassInstances)
STDMETHOD(PSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(IAGetInputLayout)(This,ppInputLayout)
STDMETHOD(IAGetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)
STDMETHOD(IAGetIndexBuffer)(This,pIndexBuffer,Format,Offset)
STDMETHOD(GSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(GSGetShader)(This,ppGeometryShader,ppClassInstances,pNumClassInstances)
STDMETHOD(IAGetPrimitiveTopology)(This,pTopology)
STDMETHOD(VSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(VSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(GetPredication)(This,ppPredicate,pPredicateValue)
STDMETHOD(GSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(GSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(OMGetRenderTargets)(This,NumViews,ppRenderTargetViews,ppDepthStencilView)
STDMETHOD(OMGetRenderTargetsAndUnorderedAccessViews)(This,NumRTVs,ppRenderTargetViews,ppDepthStencilView,UAVStartSlot,NumUAVs,ppUnorderedAccessViews)
STDMETHOD(OMGetBlendState)(This,ppBlendState,BlendFactor,pSampleMask)
STDMETHOD(OMGetDepthStencilState)(This,ppDepthStencilState,pStencilRef)
STDMETHOD(SOGetTargets)(This,NumBuffers,ppSOTargets)
STDMETHOD(RSGetState)(This,ppRasterizerState)
STDMETHOD(RSGetViewports)(This,pNumViewports,pViewports)
STDMETHOD(RSGetScissorRects)(This,pNumRects,pRects)
STDMETHOD(HSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(HSGetShader)(This,ppHullShader,ppClassInstances,pNumClassInstances)
STDMETHOD(HSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(HSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(DSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(DSGetShader)(This,ppDomainShader,ppClassInstances,pNumClassInstances)
STDMETHOD(DSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(DSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(CSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(CSGetUnorderedAccessViews)(This,StartSlot,NumUAVs,ppUnorderedAccessViews)
STDMETHOD(CSGetShader)(This,ppComputeShader,ppClassInstances,pNumClassInstances)
STDMETHOD(CSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(CSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(ClearState)(This)
STDMETHOD(Flush)(This)
STDMETHOD(GetType)(This)
STDMETHOD(GetContextFlags)(This)
STDMETHOD(FinishCommandList)(This,RestoreDeferredContextState,ppCommandList)
"
)

D3D11.ID3D11DomainShader:= {}
D3D11.ID3D11DomainShader.name := "ID3D11DomainShader"
D3D11.ID3D11DomainShader.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D11.ID3D11GeometryShader:= {}
D3D11.ID3D11GeometryShader.name := "ID3D11GeometryShader"
D3D11.ID3D11GeometryShader.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D11.ID3D11HullShader:= {}
D3D11.ID3D11HullShader.name := "ID3D11HullShader"
D3D11.ID3D11HullShader.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D11.ID3D11InputLayout:= {}
D3D11.ID3D11InputLayout.name := "ID3D11InputLayout"
D3D11.ID3D11InputLayout.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D11.ID3D11PixelShader:= {}
D3D11.ID3D11PixelShader.name := "ID3D11PixelShader"
D3D11.ID3D11PixelShader.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D11.ID3D11Predicate:= {}
D3D11.ID3D11Predicate.name := "ID3D11Predicate"
D3D11.ID3D11Predicate.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDataSize)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11Query:= {}
D3D11.ID3D11Query.name := "ID3D11Query"
D3D11.ID3D11Query.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDataSize)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11RasterizerState:= {}
D3D11.ID3D11RasterizerState.name := "ID3D11RasterizerState"
D3D11.ID3D11RasterizerState.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11RenderTargetView:= {}
D3D11.ID3D11RenderTargetView.name := "ID3D11RenderTargetView"
D3D11.ID3D11RenderTargetView.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetResource)(This,ppResource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11Resource:= {}
D3D11.ID3D11Resource.name := "ID3D11Resource"
D3D11.ID3D11Resource.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,pResourceDimension)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
"
)

D3D11.ID3D11SamplerState:= {}
D3D11.ID3D11SamplerState.name := "ID3D11SamplerState"
D3D11.ID3D11SamplerState.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11ShaderResourceView:= {}
D3D11.ID3D11ShaderResourceView.name := "ID3D11ShaderResourceView"
D3D11.ID3D11ShaderResourceView.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetResource)(This,ppResource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11Texture1D:= {}
D3D11.ID3D11Texture1D.name := "ID3D11Texture1D"
D3D11.ID3D11Texture1D.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,pResourceDimension)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11Texture2D:= {}
D3D11.ID3D11Texture2D.name := "ID3D11Texture2D"
D3D11.ID3D11Texture2D.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,pResourceDimension)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11Texture3D:= {}
D3D11.ID3D11Texture3D.name := "ID3D11Texture3D"
D3D11.ID3D11Texture3D.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,pResourceDimension)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11UnorderedAccessView:= {}
D3D11.ID3D11UnorderedAccessView.name := "ID3D11UnorderedAccessView"
D3D11.ID3D11UnorderedAccessView.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetResource)(This,ppResource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D11.ID3D11VertexShader:= {}
D3D11.ID3D11VertexShader.name := "ID3D11VertexShader"
D3D11.ID3D11VertexShader.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D11.ID3D11View:= {}
D3D11.ID3D11View.name := "ID3D11View"
D3D11.ID3D11View.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetResource)(This,ppResource)
"
)

D3D11.constant := {}
D3D11.constant[2172 . ""] := "_FACD3D11"
D3D11.constant[65535 . ""] := "D3D11_16BIT_INDEX_STRIP_CUT_VALUE"
D3D11.constant[4294967295 . ""] := "D3D11_32BIT_INDEX_STRIP_CUT_VALUE"
D3D11.constant[255 . ""] := "D3D11_8BIT_INDEX_STRIP_CUT_VALUE"
D3D11.constant[64 . ""] := "D3D11_ANISOTROPIC_FILTERING_BIT"
D3D11.constant[4294967295 . ""] := "D3D11_APPEND_ALIGNED_ELEMENT"
D3D11.constant[9 . ""] := "D3D11_ARRAY_AXIS_ADDRESS_RANGE_BIT_COUNT"
D3D11.constant[8 . ""] := "D3D11_CLIP_OR_CULL_DISTANCE_COUNT"
D3D11.constant[2 . ""] := "D3D11_CLIP_OR_CULL_DISTANCE_ELEMENT_COUNT"
D3D11.constant[14 . ""] := "D3D11_COMMONSHADER_CONSTANT_BUFFER_API_SLOT_COUNT"
D3D11.constant[32 . ""] := "D3D11_COMMONSHADER_CONSTANT_BUFFER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_COMMONSHADER_CONSTANT_BUFFER_COMPONENTS"
D3D11.constant[15 . ""] := "D3D11_COMMONSHADER_CONSTANT_BUFFER_HW_SLOT_COUNT"
D3D11.constant[4 . ""] := "D3D11_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COMPONENTS"
D3D11.constant[15 . ""] := "D3D11_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READ_PORTS"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READS_PER_INST"
D3D11.constant[64 . ""] := "D3D11_COMMONSHADER_FLOWCONTROL_NESTING_LIMIT"
D3D11.constant[4 . ""] := "D3D11_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READ_PORTS"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_COMMONSHADER_IMMEDIATE_VALUE_COMPONENT_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_INPUT_RESOURCE_REGISTER_COMPONENTS"
D3D11.constant[128 . ""] := "D3D11_COMMONSHADER_INPUT_RESOURCE_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_INPUT_RESOURCE_REGISTER_READ_PORTS"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_INPUT_RESOURCE_REGISTER_READS_PER_INST"
D3D11.constant[128 . ""] := "D3D11_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_SAMPLER_REGISTER_COMPONENTS"
D3D11.constant[16 . ""] := "D3D11_COMMONSHADER_SAMPLER_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_SAMPLER_REGISTER_READ_PORTS"
D3D11.constant[1 . ""] := "D3D11_COMMONSHADER_SAMPLER_REGISTER_READS_PER_INST"
D3D11.constant[16 . ""] := "D3D11_COMMONSHADER_SAMPLER_SLOT_COUNT"
D3D11.constant[32 . ""] := "D3D11_COMMONSHADER_SUBROUTINE_NESTING_LIMIT"
D3D11.constant[32 . ""] := "D3D11_COMMONSHADER_TEMP_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_COMMONSHADER_TEMP_REGISTER_COMPONENTS"
D3D11.constant[4096 . ""] := "D3D11_COMMONSHADER_TEMP_REGISTER_COUNT"
D3D11.constant[3 . ""] := "D3D11_COMMONSHADER_TEMP_REGISTER_READ_PORTS"
D3D11.constant[3 . ""] := "D3D11_COMMONSHADER_TEMP_REGISTER_READS_PER_INST"
D3D11.constant[10 . ""] := "D3D11_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MAX"
D3D11.constant[-10 . ""] := "D3D11_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MIN"
D3D11.constant[-8 . ""] := "D3D11_COMMONSHADER_TEXEL_OFFSET_MAX_NEGATIVE"
D3D11.constant[7 . ""] := "D3D11_COMMONSHADER_TEXEL_OFFSET_MAX_POSITIVE"
D3D11.constant[128 . ""] := "D3D11_COMPARISON_FILTERING_BIT"
D3D11.constant[256 . ""] := "D3D11_CS_4_X_BUCKET00_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[64 . ""] := "D3D11_CS_4_X_BUCKET00_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[240 . ""] := "D3D11_CS_4_X_BUCKET01_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[68 . ""] := "D3D11_CS_4_X_BUCKET01_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[224 . ""] := "D3D11_CS_4_X_BUCKET02_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[72 . ""] := "D3D11_CS_4_X_BUCKET02_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[208 . ""] := "D3D11_CS_4_X_BUCKET03_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[76 . ""] := "D3D11_CS_4_X_BUCKET03_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[192 . ""] := "D3D11_CS_4_X_BUCKET04_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[84 . ""] := "D3D11_CS_4_X_BUCKET04_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[176 . ""] := "D3D11_CS_4_X_BUCKET05_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[92 . ""] := "D3D11_CS_4_X_BUCKET05_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[160 . ""] := "D3D11_CS_4_X_BUCKET06_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[100 . ""] := "D3D11_CS_4_X_BUCKET06_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[144 . ""] := "D3D11_CS_4_X_BUCKET07_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[112 . ""] := "D3D11_CS_4_X_BUCKET07_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[128 . ""] := "D3D11_CS_4_X_BUCKET08_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[128 . ""] := "D3D11_CS_4_X_BUCKET08_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[112 . ""] := "D3D11_CS_4_X_BUCKET09_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[144 . ""] := "D3D11_CS_4_X_BUCKET09_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[96 . ""] := "D3D11_CS_4_X_BUCKET10_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[168 . ""] := "D3D11_CS_4_X_BUCKET10_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[80 . ""] := "D3D11_CS_4_X_BUCKET11_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[204 . ""] := "D3D11_CS_4_X_BUCKET11_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[64 . ""] := "D3D11_CS_4_X_BUCKET12_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[256 . ""] := "D3D11_CS_4_X_BUCKET12_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[48 . ""] := "D3D11_CS_4_X_BUCKET13_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[340 . ""] := "D3D11_CS_4_X_BUCKET13_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[32 . ""] := "D3D11_CS_4_X_BUCKET14_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[512 . ""] := "D3D11_CS_4_X_BUCKET14_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[16 . ""] := "D3D11_CS_4_X_BUCKET15_MAX_BYTES_TGSM_WRITABLE_PER_THREAD"
D3D11.constant[768 . ""] := "D3D11_CS_4_X_BUCKET15_MAX_NUM_THREADS_PER_GROUP"
D3D11.constant[1 . ""] := "D3D11_CS_4_X_DISPATCH_MAX_THREAD_GROUPS_IN_Z_DIMENSION"
D3D11.constant[256 . ""] := "D3D11_CS_4_X_RAW_UAV_BYTE_ALIGNMENT"
D3D11.constant[768 . ""] := "D3D11_CS_4_X_THREAD_GROUP_MAX_THREADS_PER_GROUP"
D3D11.constant[768 . ""] := "D3D11_CS_4_X_THREAD_GROUP_MAX_X"
D3D11.constant[768 . ""] := "D3D11_CS_4_X_THREAD_GROUP_MAX_Y"
D3D11.constant[1 . ""] := "D3D11_CS_4_X_UAV_REGISTER_COUNT"
D3D11.constant[65535 . ""] := "D3D11_CS_DISPATCH_MAX_THREAD_GROUPS_PER_DIMENSION"
D3D11.constant[8192 . ""] := "D3D11_CS_TGSM_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_CS_TGSM_REGISTER_READS_PER_INST"
D3D11.constant[1 . ""] := "D3D11_CS_TGSM_RESOURCE_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_CS_TGSM_RESOURCE_REGISTER_READ_PORTS"
D3D11.constant[1024 . ""] := "D3D11_CS_THREAD_GROUP_MAX_THREADS_PER_GROUP"
D3D11.constant[1024 . ""] := "D3D11_CS_THREAD_GROUP_MAX_X"
D3D11.constant[1024 . ""] := "D3D11_CS_THREAD_GROUP_MAX_Y"
D3D11.constant[64 . ""] := "D3D11_CS_THREAD_GROUP_MAX_Z"
D3D11.constant[1 . ""] := "D3D11_CS_THREAD_GROUP_MIN_X"
D3D11.constant[1 . ""] := "D3D11_CS_THREAD_GROUP_MIN_Y"
D3D11.constant[1 . ""] := "D3D11_CS_THREAD_GROUP_MIN_Z"
D3D11.constant[16384 . ""] := "D3D11_CS_THREAD_LOCAL_TEMP_REGISTER_POOL"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_DEPTH_BIAS"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_RENDER_TARGET_ARRAY_INDEX"
D3D11.constant[4294967295 . ""] := "D3D11_DEFAULT_SAMPLE_MASK"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_SCISSOR_ENDX"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_SCISSOR_ENDY"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_SCISSOR_STARTX"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_SCISSOR_STARTY"
D3D11.constant[255 . ""] := "D3D11_DEFAULT_STENCIL_READ_MASK"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_STENCIL_REFERENCE"
D3D11.constant[255 . ""] := "D3D11_DEFAULT_STENCIL_WRITE_MASK"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_VIEWPORT_AND_SCISSORRECT_INDEX"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_VIEWPORT_HEIGHT"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_VIEWPORT_TOPLEFTX"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_VIEWPORT_TOPLEFTY"
D3D11.constant[0 . ""] := "D3D11_DEFAULT_VIEWPORT_WIDTH"
D3D11.constant[32 . ""] := "D3D11_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENTS"
D3D11.constant[32 . ""] := "D3D11_DS_INPUT_CONTROL_POINT_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_DS_INPUT_CONTROL_POINT_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_DS_INPUT_CONTROL_POINT_REGISTER_READS_PER_INST"
D3D11.constant[3968 . ""] := "D3D11_DS_INPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS"
D3D11.constant[32 . ""] := "D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[3 . ""] := "D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENTS"
D3D11.constant[32 . ""] := "D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_DS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_DS_OUTPUT_REGISTER_COMPONENTS"
D3D11.constant[32 . ""] := "D3D11_DS_OUTPUT_REGISTER_COUNT"
D3D11.constant[3 . ""] := "D3D11_FILTER_TYPE_MASK"
D3D11.constant[1 . ""] := "D3D11_GS_INPUT_INSTANCE_ID_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_GS_INPUT_INSTANCE_ID_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_GS_INPUT_INSTANCE_ID_REGISTER_COUNT"
D3D11.constant[32 . ""] := "D3D11_GS_INPUT_PRIM_CONST_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_GS_INPUT_PRIM_CONST_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_GS_INPUT_PRIM_CONST_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_GS_INPUT_PRIM_CONST_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_GS_INPUT_PRIM_CONST_REGISTER_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_GS_INPUT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_GS_INPUT_REGISTER_COMPONENTS"
D3D11.constant[32 . ""] := "D3D11_GS_INPUT_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_GS_INPUT_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_GS_INPUT_REGISTER_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_GS_INPUT_REGISTER_VERTICES"
D3D11.constant[32 . ""] := "D3D11_GS_MAX_INSTANCE_COUNT"
D3D11.constant[1024 . ""] := "D3D11_GS_MAX_OUTPUT_VERTEX_COUNT_ACROSS_INSTANCES"
D3D11.constant[32 . ""] := "D3D11_GS_OUTPUT_ELEMENTS"
D3D11.constant[32 . ""] := "D3D11_GS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_GS_OUTPUT_REGISTER_COMPONENTS"
D3D11.constant[32 . ""] := "D3D11_GS_OUTPUT_REGISTER_COUNT"
D3D11.constant[32 . ""] := "D3D11_HS_CONTROL_POINT_PHASE_INPUT_REGISTER_COUNT"
D3D11.constant[32 . ""] := "D3D11_HS_CONTROL_POINT_PHASE_OUTPUT_REGISTER_COUNT"
D3D11.constant[32 . ""] := "D3D11_HS_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_HS_CONTROL_POINT_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_HS_CONTROL_POINT_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_HS_CONTROL_POINT_REGISTER_READS_PER_INST"
D3D11.constant[4294967295 . ""] := "D3D11_HS_FORK_PHASE_INSTANCE_COUNT_UPPER_BOUND"
D3D11.constant[32 . ""] := "D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_READS_PER_INST"
D3D11.constant[4294967295 . ""] := "D3D11_HS_JOIN_PHASE_INSTANCE_COUNT_UPPER_BOUND"
D3D11.constant[32 . ""] := "D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READS_PER_INST"
D3D11.constant[3968 . ""] := "D3D11_HS_OUTPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS"
D3D11.constant[32 . ""] := "D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENTS"
D3D11.constant[32 . ""] := "D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST"
D3D11.constant[0 . ""] := "D3D11_IA_DEFAULT_INDEX_BUFFER_OFFSET_IN_BYTES"
D3D11.constant[0 . ""] := "D3D11_IA_DEFAULT_PRIMITIVE_TOPOLOGY"
D3D11.constant[0 . ""] := "D3D11_IA_DEFAULT_VERTEX_BUFFER_OFFSET_IN_BYTES"
D3D11.constant[1 . ""] := "D3D11_IA_INDEX_INPUT_RESOURCE_SLOT_COUNT"
D3D11.constant[32 . ""] := "D3D11_IA_INSTANCE_ID_BIT_COUNT"
D3D11.constant[32 . ""] := "D3D11_IA_INTEGER_ARITHMETIC_BIT_COUNT"
D3D11.constant[32 . ""] := "D3D11_IA_PATCH_MAX_CONTROL_POINT_COUNT"
D3D11.constant[32 . ""] := "D3D11_IA_PRIMITIVE_ID_BIT_COUNT"
D3D11.constant[32 . ""] := "D3D11_IA_VERTEX_ID_BIT_COUNT"
D3D11.constant[32 . ""] := "D3D11_IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT"
D3D11.constant[32 . ""] := "D3D11_IA_VERTEX_INPUT_STRUCTURE_ELEMENT_COUNT"
D3D11.constant[128 . ""] := "D3D11_IA_VERTEX_INPUT_STRUCTURE_ELEMENTS_COMPONENTS"
D3D11.constant[4294967295 . ""] := "D3D11_INTEGER_DIVIDE_BY_ZERO_QUOTIENT"
D3D11.constant[4294967295 . ""] := "D3D11_INTEGER_DIVIDE_BY_ZERO_REMAINDER"
D3D11.constant[4294967295 . ""] := "D3D11_KEEP_RENDER_TARGETS_AND_DEPTH_STENCIL"
D3D11.constant[4294967295 . ""] := "D3D11_KEEP_UNORDERED_ACCESS_VIEWS"
D3D11.constant[2 . ""] := "D3D11_MAG_FILTER_SHIFT"
D3D11.constant[11 . ""] := "D3D11_MAJOR_VERSION"
D3D11.constant[16 . ""] := "D3D11_MAX_MAXANISOTROPY"
D3D11.constant[32 . ""] := "D3D11_MAX_MULTISAMPLE_SAMPLE_COUNT"
D3D11.constant[17 . ""] := "D3D11_MAX_TEXTURE_DIMENSION_2_TO_EXP"
D3D11.constant[4 . ""] := "D3D11_MIN_FILTER_SHIFT"
D3D11.constant[0 . ""] := "D3D11_MIN_MAXANISOTROPY"
D3D11.constant[0 . ""] := "D3D11_MINOR_VERSION"
D3D11.constant[0 . ""] := "D3D11_MIP_FILTER_SHIFT"
D3D11.constant[8 . ""] := "D3D11_MIP_LOD_FRACTIONAL_BIT_COUNT"
D3D11.constant[8 . ""] := "D3D11_MIP_LOD_RANGE_BIT_COUNT"
D3D11.constant[0 . ""] := "D3D11_NONSAMPLE_FETCH_OUT_OF_RANGE_ACCESS_RESULT"
D3D11.constant[15 . ""] := "D3D11_PIXEL_ADDRESS_RANGE_BIT_COUNT"
D3D11.constant[16 . ""] := "D3D11_PRE_SCISSOR_PIXEL_ADDRESS_RANGE_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_PS_CS_UAV_REGISTER_COMPONENTS"
D3D11.constant[8 . ""] := "D3D11_PS_CS_UAV_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_PS_CS_UAV_REGISTER_READ_PORTS"
D3D11.constant[1 . ""] := "D3D11_PS_CS_UAV_REGISTER_READS_PER_INST"
D3D11.constant[4294967295 . ""] := "D3D11_PS_FRONTFACING_DEFAULT_VALUE"
D3D11.constant[0 . ""] := "D3D11_PS_FRONTFACING_FALSE_VALUE"
D3D11.constant[4294967295 . ""] := "D3D11_PS_FRONTFACING_TRUE_VALUE"
D3D11.constant[32 . ""] := "D3D11_PS_INPUT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_PS_INPUT_REGISTER_COMPONENTS"
D3D11.constant[32 . ""] := "D3D11_PS_INPUT_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_PS_INPUT_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_PS_INPUT_REGISTER_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_PS_OUTPUT_DEPTH_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_PS_OUTPUT_DEPTH_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_PS_OUTPUT_DEPTH_REGISTER_COUNT"
D3D11.constant[32 . ""] := "D3D11_PS_OUTPUT_MASK_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[1 . ""] := "D3D11_PS_OUTPUT_MASK_REGISTER_COMPONENTS"
D3D11.constant[1 . ""] := "D3D11_PS_OUTPUT_MASK_REGISTER_COUNT"
D3D11.constant[32 . ""] := "D3D11_PS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_PS_OUTPUT_REGISTER_COMPONENTS"
D3D11.constant[8 . ""] := "D3D11_PS_OUTPUT_REGISTER_COUNT"
D3D11.constant[16 . ""] := "D3D11_RAW_UAV_SRV_BYTE_ALIGNMENT"
D3D11.constant[4096 . ""] := "D3D11_REQ_BLEND_OBJECT_COUNT_PER_DEVICE"
D3D11.constant[27 . ""] := "D3D11_REQ_BUFFER_RESOURCE_TEXEL_COUNT_2_TO_EXP"
D3D11.constant[4096 . ""] := "D3D11_REQ_CONSTANT_BUFFER_ELEMENT_COUNT"
D3D11.constant[4096 . ""] := "D3D11_REQ_DEPTH_STENCIL_OBJECT_COUNT_PER_DEVICE"
D3D11.constant[32 . ""] := "D3D11_REQ_DRAW_VERTEX_COUNT_2_TO_EXP"
D3D11.constant[32 . ""] := "D3D11_REQ_DRAWINDEXED_INDEX_COUNT_2_TO_EXP"
D3D11.constant[16384 . ""] := "D3D11_REQ_FILTERING_HW_ADDRESSABLE_RESOURCE_DIMENSION"
D3D11.constant[1024 . ""] := "D3D11_REQ_GS_INVOCATION_32BIT_OUTPUT_COMPONENT_LIMIT"
D3D11.constant[4096 . ""] := "D3D11_REQ_IMMEDIATE_CONSTANT_BUFFER_ELEMENT_COUNT"
D3D11.constant[16 . ""] := "D3D11_REQ_MAXANISOTROPY"
D3D11.constant[15 . ""] := "D3D11_REQ_MIP_LEVELS"
D3D11.constant[2048 . ""] := "D3D11_REQ_MULTI_ELEMENT_STRUCTURE_SIZE_IN_BYTES"
D3D11.constant[4096 . ""] := "D3D11_REQ_RASTERIZER_OBJECT_COUNT_PER_DEVICE"
D3D11.constant[16384 . ""] := "D3D11_REQ_RENDER_TO_BUFFER_WINDOW_WIDTH"
D3D11.constant[128 . ""] := "D3D11_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_A_TERM"
D3D11.constant[20 . ""] := "D3D11_REQ_RESOURCE_VIEW_COUNT_PER_DEVICE_2_TO_EXP"
D3D11.constant[4096 . ""] := "D3D11_REQ_SAMPLER_OBJECT_COUNT_PER_DEVICE"
D3D11.constant[2048 . ""] := "D3D11_REQ_TEXTURE1D_ARRAY_AXIS_DIMENSION"
D3D11.constant[16384 . ""] := "D3D11_REQ_TEXTURE1D_U_DIMENSION"
D3D11.constant[2048 . ""] := "D3D11_REQ_TEXTURE2D_ARRAY_AXIS_DIMENSION"
D3D11.constant[16384 . ""] := "D3D11_REQ_TEXTURE2D_U_OR_V_DIMENSION"
D3D11.constant[2048 . ""] := "D3D11_REQ_TEXTURE3D_U_V_OR_W_DIMENSION"
D3D11.constant[16384 . ""] := "D3D11_REQ_TEXTURECUBE_DIMENSION"
D3D11.constant[0 . ""] := "D3D11_RESINFO_INSTRUCTION_MISSING_COMPONENT_RETVAL"
D3D11.constant[7 . ""] := "D3D11_SDK_VERSION"
D3D11.constant[5 . ""] := "D3D11_SHADER_MAJOR_VERSION"
D3D11.constant[65535 . ""] := "D3D11_SHADER_MAX_INSTANCES"
D3D11.constant[4096 . ""] := "D3D11_SHADER_MAX_INTERFACE_CALL_SITES"
D3D11.constant[253 . ""] := "D3D11_SHADER_MAX_INTERFACES"
D3D11.constant[65535 . ""] := "D3D11_SHADER_MAX_TYPES"
D3D11.constant[0 . ""] := "D3D11_SHADER_MINOR_VERSION"
D3D11.constant[0 . ""] := "D3D11_SHIFT_INSTRUCTION_PAD_VALUE"
D3D11.constant[5 . ""] := "D3D11_SHIFT_INSTRUCTION_SHIFT_VALUE_BIT_COUNT"
D3D11.constant[8 . ""] := "D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT"
D3D11.constant[2048 . ""] := "D3D11_SO_BUFFER_MAX_STRIDE_IN_BYTES"
D3D11.constant[512 . ""] := "D3D11_SO_BUFFER_MAX_WRITE_WINDOW_IN_BYTES"
D3D11.constant[4 . ""] := "D3D11_SO_BUFFER_SLOT_COUNT"
D3D11.constant[4294967295 . ""] := "D3D11_SO_DDI_REGISTER_INDEX_DENOTING_GAP"
D3D11.constant[4294967295 . ""] := "D3D11_SO_NO_RASTERIZED_STREAM"
D3D11.constant[128 . ""] := "D3D11_SO_OUTPUT_COMPONENT_COUNT"
D3D11.constant[4 . ""] := "D3D11_SO_STREAM_COUNT"
D3D11.constant[4 . ""] := "D3D11_SPEC_DATE_DAY"
D3D11.constant[6 . ""] := "D3D11_SPEC_DATE_MONTH"
D3D11.constant[2009 . ""] := "D3D11_SPEC_DATE_YEAR"
D3D11.constant[32 . ""] := "D3D11_STANDARD_COMPONENT_BIT_COUNT"
D3D11.constant[64 . ""] := "D3D11_STANDARD_COMPONENT_BIT_COUNT_DOUBLED"
D3D11.constant[4 . ""] := "D3D11_STANDARD_MAXIMUM_ELEMENT_ALIGNMENT_BYTE_MULTIPLE"
D3D11.constant[128 . ""] := "D3D11_STANDARD_PIXEL_COMPONENT_COUNT"
D3D11.constant[32 . ""] := "D3D11_STANDARD_PIXEL_ELEMENT_COUNT"
D3D11.constant[4 . ""] := "D3D11_STANDARD_VECTOR_SIZE"
D3D11.constant[32 . ""] := "D3D11_STANDARD_VERTEX_ELEMENT_COUNT"
D3D11.constant[64 . ""] := "D3D11_STANDARD_VERTEX_TOTAL_COMPONENT_COUNT"
D3D11.constant[8 . ""] := "D3D11_SUBPIXEL_FRACTIONAL_BIT_COUNT"
D3D11.constant[8 . ""] := "D3D11_SUBTEXEL_FRACTIONAL_BIT_COUNT"
D3D11.constant[64 . ""] := "D3D11_TESSELLATOR_MAX_EVEN_TESSELLATION_FACTOR"
D3D11.constant[64 . ""] := "D3D11_TESSELLATOR_MAX_ISOLINE_DENSITY_TESSELLATION_FACTOR"
D3D11.constant[63 . ""] := "D3D11_TESSELLATOR_MAX_ODD_TESSELLATION_FACTOR"
D3D11.constant[64 . ""] := "D3D11_TESSELLATOR_MAX_TESSELLATION_FACTOR"
D3D11.constant[2 . ""] := "D3D11_TESSELLATOR_MIN_EVEN_TESSELLATION_FACTOR"
D3D11.constant[1 . ""] := "D3D11_TESSELLATOR_MIN_ISOLINE_DENSITY_TESSELLATION_FACTOR"
D3D11.constant[1 . ""] := "D3D11_TESSELLATOR_MIN_ODD_TESSELLATION_FACTOR"
D3D11.constant[16 . ""] := "D3D11_TEXEL_ADDRESS_RANGE_BIT_COUNT"
D3D11.constant[0 . ""] := "D3D11_UNBOUND_MEMORY_ACCESS_RESULT"
D3D11.constant[15 . ""] := "D3D11_VIEWPORT_AND_SCISSORRECT_MAX_INDEX"
D3D11.constant[16 . ""] := "D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE"
D3D11.constant[32767 . ""] := "D3D11_VIEWPORT_BOUNDS_MAX"
D3D11.constant[-32768 . ""] := "D3D11_VIEWPORT_BOUNDS_MIN"
D3D11.constant[32 . ""] := "D3D11_VS_INPUT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_VS_INPUT_REGISTER_COMPONENTS"
D3D11.constant[32 . ""] := "D3D11_VS_INPUT_REGISTER_COUNT"
D3D11.constant[1 . ""] := "D3D11_VS_INPUT_REGISTER_READ_PORTS"
D3D11.constant[2 . ""] := "D3D11_VS_INPUT_REGISTER_READS_PER_INST"
D3D11.constant[32 . ""] := "D3D11_VS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT"
D3D11.constant[4 . ""] := "D3D11_VS_OUTPUT_REGISTER_COMPONENTS"
D3D11.constant[32 . ""] := "D3D11_VS_OUTPUT_REGISTER_COUNT"
D3D11.constant[10 . ""] := "D3D11_WHQL_CONTEXT_COUNT_FOR_RESOURCE_LIMIT"
D3D11.constant[25 . ""] := "D3D11_WHQL_DRAW_VERTEX_COUNT_2_TO_EXP"
D3D11.constant[25 . ""] := "D3D11_WHQL_DRAWINDEXED_INDEX_COUNT_2_TO_EXP"


Global _FACD3D11 := 2172
Global D3D11_16BIT_INDEX_STRIP_CUT_VALUE := 65535
Global D3D11_32BIT_INDEX_STRIP_CUT_VALUE := 4294967295
Global D3D11_8BIT_INDEX_STRIP_CUT_VALUE := 255
Global D3D11_ANISOTROPIC_FILTERING_BIT := 64
Global D3D11_APPEND_ALIGNED_ELEMENT := 4294967295
Global D3D11_ARRAY_AXIS_ADDRESS_RANGE_BIT_COUNT := 9
Global D3D11_CLIP_OR_CULL_DISTANCE_COUNT := 8
Global D3D11_CLIP_OR_CULL_DISTANCE_ELEMENT_COUNT := 2
Global D3D11_COMMONSHADER_CONSTANT_BUFFER_API_SLOT_COUNT := 14
Global D3D11_COMMONSHADER_CONSTANT_BUFFER_COMPONENT_BIT_COUNT := 32
Global D3D11_COMMONSHADER_CONSTANT_BUFFER_COMPONENTS := 4
Global D3D11_COMMONSHADER_CONSTANT_BUFFER_HW_SLOT_COUNT := 15
Global D3D11_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COMPONENTS := 4
Global D3D11_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COUNT := 15
Global D3D11_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READ_PORTS := 1
Global D3D11_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READS_PER_INST := 1
Global D3D11_COMMONSHADER_FLOWCONTROL_NESTING_LIMIT := 64
Global D3D11_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COMPONENTS := 4
Global D3D11_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COUNT := 1
Global D3D11_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READ_PORTS := 1
Global D3D11_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READS_PER_INST := 1
Global D3D11_COMMONSHADER_IMMEDIATE_VALUE_COMPONENT_BIT_COUNT := 32
Global D3D11_COMMONSHADER_INPUT_RESOURCE_REGISTER_COMPONENTS := 1
Global D3D11_COMMONSHADER_INPUT_RESOURCE_REGISTER_COUNT := 128
Global D3D11_COMMONSHADER_INPUT_RESOURCE_REGISTER_READ_PORTS := 1
Global D3D11_COMMONSHADER_INPUT_RESOURCE_REGISTER_READS_PER_INST := 1
Global D3D11_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT := 128
Global D3D11_COMMONSHADER_SAMPLER_REGISTER_COMPONENTS := 1
Global D3D11_COMMONSHADER_SAMPLER_REGISTER_COUNT := 16
Global D3D11_COMMONSHADER_SAMPLER_REGISTER_READ_PORTS := 1
Global D3D11_COMMONSHADER_SAMPLER_REGISTER_READS_PER_INST := 1
Global D3D11_COMMONSHADER_SAMPLER_SLOT_COUNT := 16
Global D3D11_COMMONSHADER_SUBROUTINE_NESTING_LIMIT := 32
Global D3D11_COMMONSHADER_TEMP_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_COMMONSHADER_TEMP_REGISTER_COMPONENTS := 4
Global D3D11_COMMONSHADER_TEMP_REGISTER_COUNT := 4096
Global D3D11_COMMONSHADER_TEMP_REGISTER_READ_PORTS := 3
Global D3D11_COMMONSHADER_TEMP_REGISTER_READS_PER_INST := 3
Global D3D11_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MAX := 10
Global D3D11_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MIN := -10
Global D3D11_COMMONSHADER_TEXEL_OFFSET_MAX_NEGATIVE := -8
Global D3D11_COMMONSHADER_TEXEL_OFFSET_MAX_POSITIVE := 7
Global D3D11_COMPARISON_FILTERING_BIT := 128
Global D3D11_CS_4_X_BUCKET00_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 256
Global D3D11_CS_4_X_BUCKET00_MAX_NUM_THREADS_PER_GROUP := 64
Global D3D11_CS_4_X_BUCKET01_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 240
Global D3D11_CS_4_X_BUCKET01_MAX_NUM_THREADS_PER_GROUP := 68
Global D3D11_CS_4_X_BUCKET02_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 224
Global D3D11_CS_4_X_BUCKET02_MAX_NUM_THREADS_PER_GROUP := 72
Global D3D11_CS_4_X_BUCKET03_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 208
Global D3D11_CS_4_X_BUCKET03_MAX_NUM_THREADS_PER_GROUP := 76
Global D3D11_CS_4_X_BUCKET04_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 192
Global D3D11_CS_4_X_BUCKET04_MAX_NUM_THREADS_PER_GROUP := 84
Global D3D11_CS_4_X_BUCKET05_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 176
Global D3D11_CS_4_X_BUCKET05_MAX_NUM_THREADS_PER_GROUP := 92
Global D3D11_CS_4_X_BUCKET06_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 160
Global D3D11_CS_4_X_BUCKET06_MAX_NUM_THREADS_PER_GROUP := 100
Global D3D11_CS_4_X_BUCKET07_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 144
Global D3D11_CS_4_X_BUCKET07_MAX_NUM_THREADS_PER_GROUP := 112
Global D3D11_CS_4_X_BUCKET08_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 128
Global D3D11_CS_4_X_BUCKET08_MAX_NUM_THREADS_PER_GROUP := 128
Global D3D11_CS_4_X_BUCKET09_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 112
Global D3D11_CS_4_X_BUCKET09_MAX_NUM_THREADS_PER_GROUP := 144
Global D3D11_CS_4_X_BUCKET10_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 96
Global D3D11_CS_4_X_BUCKET10_MAX_NUM_THREADS_PER_GROUP := 168
Global D3D11_CS_4_X_BUCKET11_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 80
Global D3D11_CS_4_X_BUCKET11_MAX_NUM_THREADS_PER_GROUP := 204
Global D3D11_CS_4_X_BUCKET12_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 64
Global D3D11_CS_4_X_BUCKET12_MAX_NUM_THREADS_PER_GROUP := 256
Global D3D11_CS_4_X_BUCKET13_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 48
Global D3D11_CS_4_X_BUCKET13_MAX_NUM_THREADS_PER_GROUP := 340
Global D3D11_CS_4_X_BUCKET14_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 32
Global D3D11_CS_4_X_BUCKET14_MAX_NUM_THREADS_PER_GROUP := 512
Global D3D11_CS_4_X_BUCKET15_MAX_BYTES_TGSM_WRITABLE_PER_THREAD := 16
Global D3D11_CS_4_X_BUCKET15_MAX_NUM_THREADS_PER_GROUP := 768
Global D3D11_CS_4_X_DISPATCH_MAX_THREAD_GROUPS_IN_Z_DIMENSION := 1
Global D3D11_CS_4_X_RAW_UAV_BYTE_ALIGNMENT := 256
Global D3D11_CS_4_X_THREAD_GROUP_MAX_THREADS_PER_GROUP := 768
Global D3D11_CS_4_X_THREAD_GROUP_MAX_X := 768
Global D3D11_CS_4_X_THREAD_GROUP_MAX_Y := 768
Global D3D11_CS_4_X_UAV_REGISTER_COUNT := 1
Global D3D11_CS_DISPATCH_MAX_THREAD_GROUPS_PER_DIMENSION := 65535
Global D3D11_CS_TGSM_REGISTER_COUNT := 8192
Global D3D11_CS_TGSM_REGISTER_READS_PER_INST := 1
Global D3D11_CS_TGSM_RESOURCE_REGISTER_COMPONENTS := 1
Global D3D11_CS_TGSM_RESOURCE_REGISTER_READ_PORTS := 1
Global D3D11_CS_THREAD_GROUP_MAX_THREADS_PER_GROUP := 1024
Global D3D11_CS_THREAD_GROUP_MAX_X := 1024
Global D3D11_CS_THREAD_GROUP_MAX_Y := 1024
Global D3D11_CS_THREAD_GROUP_MAX_Z := 64
Global D3D11_CS_THREAD_GROUP_MIN_X := 1
Global D3D11_CS_THREAD_GROUP_MIN_Y := 1
Global D3D11_CS_THREAD_GROUP_MIN_Z := 1
Global D3D11_CS_THREAD_LOCAL_TEMP_REGISTER_POOL := 16384
Global D3D11_DEFAULT_DEPTH_BIAS := 0
Global D3D11_DEFAULT_RENDER_TARGET_ARRAY_INDEX := 0
Global D3D11_DEFAULT_SAMPLE_MASK := 4294967295
Global D3D11_DEFAULT_SCISSOR_ENDX := 0
Global D3D11_DEFAULT_SCISSOR_ENDY := 0
Global D3D11_DEFAULT_SCISSOR_STARTX := 0
Global D3D11_DEFAULT_SCISSOR_STARTY := 0
Global D3D11_DEFAULT_STENCIL_READ_MASK := 255
Global D3D11_DEFAULT_STENCIL_REFERENCE := 0
Global D3D11_DEFAULT_STENCIL_WRITE_MASK := 255
Global D3D11_DEFAULT_VIEWPORT_AND_SCISSORRECT_INDEX := 0
Global D3D11_DEFAULT_VIEWPORT_HEIGHT := 0
Global D3D11_DEFAULT_VIEWPORT_TOPLEFTX := 0
Global D3D11_DEFAULT_VIEWPORT_TOPLEFTY := 0
Global D3D11_DEFAULT_VIEWPORT_WIDTH := 0
Global D3D11_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENTS := 4
Global D3D11_DS_INPUT_CONTROL_POINT_REGISTER_COUNT := 32
Global D3D11_DS_INPUT_CONTROL_POINT_REGISTER_READ_PORTS := 1
Global D3D11_DS_INPUT_CONTROL_POINT_REGISTER_READS_PER_INST := 2
Global D3D11_DS_INPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS := 3968
Global D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENTS := 3
Global D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_COUNT := 1
Global D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_READ_PORTS := 1
Global D3D11_DS_INPUT_DOMAIN_POINT_REGISTER_READS_PER_INST := 2
Global D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENTS := 4
Global D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_COUNT := 32
Global D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_READ_PORTS := 1
Global D3D11_DS_INPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST := 2
Global D3D11_DS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_DS_OUTPUT_REGISTER_COMPONENTS := 4
Global D3D11_DS_OUTPUT_REGISTER_COUNT := 32
Global D3D11_FILTER_TYPE_MASK := 3
Global D3D11_GS_INPUT_INSTANCE_ID_READ_PORTS := 1
Global D3D11_GS_INPUT_INSTANCE_ID_READS_PER_INST := 2
Global D3D11_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENTS := 1
Global D3D11_GS_INPUT_INSTANCE_ID_REGISTER_COUNT := 1
Global D3D11_GS_INPUT_PRIM_CONST_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_GS_INPUT_PRIM_CONST_REGISTER_COMPONENTS := 1
Global D3D11_GS_INPUT_PRIM_CONST_REGISTER_COUNT := 1
Global D3D11_GS_INPUT_PRIM_CONST_REGISTER_READ_PORTS := 1
Global D3D11_GS_INPUT_PRIM_CONST_REGISTER_READS_PER_INST := 2
Global D3D11_GS_INPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_GS_INPUT_REGISTER_COMPONENTS := 4
Global D3D11_GS_INPUT_REGISTER_COUNT := 32
Global D3D11_GS_INPUT_REGISTER_READ_PORTS := 1
Global D3D11_GS_INPUT_REGISTER_READS_PER_INST := 2
Global D3D11_GS_INPUT_REGISTER_VERTICES := 32
Global D3D11_GS_MAX_INSTANCE_COUNT := 32
Global D3D11_GS_MAX_OUTPUT_VERTEX_COUNT_ACROSS_INSTANCES := 1024
Global D3D11_GS_OUTPUT_ELEMENTS := 32
Global D3D11_GS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_GS_OUTPUT_REGISTER_COMPONENTS := 4
Global D3D11_GS_OUTPUT_REGISTER_COUNT := 32
Global D3D11_HS_CONTROL_POINT_PHASE_INPUT_REGISTER_COUNT := 32
Global D3D11_HS_CONTROL_POINT_PHASE_OUTPUT_REGISTER_COUNT := 32
Global D3D11_HS_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_HS_CONTROL_POINT_REGISTER_COMPONENTS := 4
Global D3D11_HS_CONTROL_POINT_REGISTER_READ_PORTS := 1
Global D3D11_HS_CONTROL_POINT_REGISTER_READS_PER_INST := 2
Global D3D11_HS_FORK_PHASE_INSTANCE_COUNT_UPPER_BOUND := 4294967295
Global D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENTS := 1
Global D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COUNT := 1
Global D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READ_PORTS := 1
Global D3D11_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READS_PER_INST := 2
Global D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENTS := 1
Global D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COUNT := 1
Global D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READ_PORTS := 1
Global D3D11_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READS_PER_INST := 2
Global D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENTS := 1
Global D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_COUNT := 1
Global D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_READ_PORTS := 1
Global D3D11_HS_INPUT_PRIMITIVE_ID_REGISTER_READS_PER_INST := 2
Global D3D11_HS_JOIN_PHASE_INSTANCE_COUNT_UPPER_BOUND := 4294967295
Global D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENTS := 1
Global D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COUNT := 1
Global D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READ_PORTS := 1
Global D3D11_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READS_PER_INST := 2
Global D3D11_HS_OUTPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS := 3968
Global D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENTS := 4
Global D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COUNT := 32
Global D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READ_PORTS := 1
Global D3D11_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST := 2
Global D3D11_IA_DEFAULT_INDEX_BUFFER_OFFSET_IN_BYTES := 0
Global D3D11_IA_DEFAULT_PRIMITIVE_TOPOLOGY := 0
Global D3D11_IA_DEFAULT_VERTEX_BUFFER_OFFSET_IN_BYTES := 0
Global D3D11_IA_INDEX_INPUT_RESOURCE_SLOT_COUNT := 1
Global D3D11_IA_INSTANCE_ID_BIT_COUNT := 32
Global D3D11_IA_INTEGER_ARITHMETIC_BIT_COUNT := 32
Global D3D11_IA_PATCH_MAX_CONTROL_POINT_COUNT := 32
Global D3D11_IA_PRIMITIVE_ID_BIT_COUNT := 32
Global D3D11_IA_VERTEX_ID_BIT_COUNT := 32
Global D3D11_IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT := 32
Global D3D11_IA_VERTEX_INPUT_STRUCTURE_ELEMENT_COUNT := 32
Global D3D11_IA_VERTEX_INPUT_STRUCTURE_ELEMENTS_COMPONENTS := 128
Global D3D11_INTEGER_DIVIDE_BY_ZERO_QUOTIENT := 4294967295
Global D3D11_INTEGER_DIVIDE_BY_ZERO_REMAINDER := 4294967295
Global D3D11_KEEP_RENDER_TARGETS_AND_DEPTH_STENCIL := 4294967295
Global D3D11_KEEP_UNORDERED_ACCESS_VIEWS := 4294967295
Global D3D11_MAG_FILTER_SHIFT := 2
Global D3D11_MAJOR_VERSION := 11
Global D3D11_MAX_MAXANISOTROPY := 16
Global D3D11_MAX_MULTISAMPLE_SAMPLE_COUNT := 32
Global D3D11_MAX_TEXTURE_DIMENSION_2_TO_EXP := 17
Global D3D11_MIN_FILTER_SHIFT := 4
Global D3D11_MIN_MAXANISOTROPY := 0
Global D3D11_MINOR_VERSION := 0
Global D3D11_MIP_FILTER_SHIFT := 0
Global D3D11_MIP_LOD_FRACTIONAL_BIT_COUNT := 8
Global D3D11_MIP_LOD_RANGE_BIT_COUNT := 8
Global D3D11_NONSAMPLE_FETCH_OUT_OF_RANGE_ACCESS_RESULT := 0
Global D3D11_PIXEL_ADDRESS_RANGE_BIT_COUNT := 15
Global D3D11_PRE_SCISSOR_PIXEL_ADDRESS_RANGE_BIT_COUNT := 16
Global D3D11_PS_CS_UAV_REGISTER_COMPONENTS := 1
Global D3D11_PS_CS_UAV_REGISTER_COUNT := 8
Global D3D11_PS_CS_UAV_REGISTER_READ_PORTS := 1
Global D3D11_PS_CS_UAV_REGISTER_READS_PER_INST := 1
Global D3D11_PS_FRONTFACING_DEFAULT_VALUE := 4294967295
Global D3D11_PS_FRONTFACING_FALSE_VALUE := 0
Global D3D11_PS_FRONTFACING_TRUE_VALUE := 4294967295
Global D3D11_PS_INPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_PS_INPUT_REGISTER_COMPONENTS := 4
Global D3D11_PS_INPUT_REGISTER_COUNT := 32
Global D3D11_PS_INPUT_REGISTER_READ_PORTS := 1
Global D3D11_PS_INPUT_REGISTER_READS_PER_INST := 2
Global D3D11_PS_OUTPUT_DEPTH_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_PS_OUTPUT_DEPTH_REGISTER_COMPONENTS := 1
Global D3D11_PS_OUTPUT_DEPTH_REGISTER_COUNT := 1
Global D3D11_PS_OUTPUT_MASK_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_PS_OUTPUT_MASK_REGISTER_COMPONENTS := 1
Global D3D11_PS_OUTPUT_MASK_REGISTER_COUNT := 1
Global D3D11_PS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_PS_OUTPUT_REGISTER_COMPONENTS := 4
Global D3D11_PS_OUTPUT_REGISTER_COUNT := 8
Global D3D11_RAW_UAV_SRV_BYTE_ALIGNMENT := 16
Global D3D11_REQ_BLEND_OBJECT_COUNT_PER_DEVICE := 4096
Global D3D11_REQ_BUFFER_RESOURCE_TEXEL_COUNT_2_TO_EXP := 27
Global D3D11_REQ_CONSTANT_BUFFER_ELEMENT_COUNT := 4096
Global D3D11_REQ_DEPTH_STENCIL_OBJECT_COUNT_PER_DEVICE := 4096
Global D3D11_REQ_DRAW_VERTEX_COUNT_2_TO_EXP := 32
Global D3D11_REQ_DRAWINDEXED_INDEX_COUNT_2_TO_EXP := 32
Global D3D11_REQ_FILTERING_HW_ADDRESSABLE_RESOURCE_DIMENSION := 16384
Global D3D11_REQ_GS_INVOCATION_32BIT_OUTPUT_COMPONENT_LIMIT := 1024
Global D3D11_REQ_IMMEDIATE_CONSTANT_BUFFER_ELEMENT_COUNT := 4096
Global D3D11_REQ_MAXANISOTROPY := 16
Global D3D11_REQ_MIP_LEVELS := 15
Global D3D11_REQ_MULTI_ELEMENT_STRUCTURE_SIZE_IN_BYTES := 2048
Global D3D11_REQ_RASTERIZER_OBJECT_COUNT_PER_DEVICE := 4096
Global D3D11_REQ_RENDER_TO_BUFFER_WINDOW_WIDTH := 16384
Global D3D11_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_A_TERM := 128
Global D3D11_REQ_RESOURCE_VIEW_COUNT_PER_DEVICE_2_TO_EXP := 20
Global D3D11_REQ_SAMPLER_OBJECT_COUNT_PER_DEVICE := 4096
Global D3D11_REQ_TEXTURE1D_ARRAY_AXIS_DIMENSION := 2048
Global D3D11_REQ_TEXTURE1D_U_DIMENSION := 16384
Global D3D11_REQ_TEXTURE2D_ARRAY_AXIS_DIMENSION := 2048
Global D3D11_REQ_TEXTURE2D_U_OR_V_DIMENSION := 16384
Global D3D11_REQ_TEXTURE3D_U_V_OR_W_DIMENSION := 2048
Global D3D11_REQ_TEXTURECUBE_DIMENSION := 16384
Global D3D11_RESINFO_INSTRUCTION_MISSING_COMPONENT_RETVAL := 0
Global D3D11_SDK_VERSION := 7
Global D3D11_SHADER_MAJOR_VERSION := 5
Global D3D11_SHADER_MAX_INSTANCES := 65535
Global D3D11_SHADER_MAX_INTERFACE_CALL_SITES := 4096
Global D3D11_SHADER_MAX_INTERFACES := 253
Global D3D11_SHADER_MAX_TYPES := 65535
Global D3D11_SHADER_MINOR_VERSION := 0
Global D3D11_SHIFT_INSTRUCTION_PAD_VALUE := 0
Global D3D11_SHIFT_INSTRUCTION_SHIFT_VALUE_BIT_COUNT := 5
Global D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT := 8
Global D3D11_SO_BUFFER_MAX_STRIDE_IN_BYTES := 2048
Global D3D11_SO_BUFFER_MAX_WRITE_WINDOW_IN_BYTES := 512
Global D3D11_SO_BUFFER_SLOT_COUNT := 4
Global D3D11_SO_DDI_REGISTER_INDEX_DENOTING_GAP := 4294967295
Global D3D11_SO_NO_RASTERIZED_STREAM := 4294967295
Global D3D11_SO_OUTPUT_COMPONENT_COUNT := 128
Global D3D11_SO_STREAM_COUNT := 4
Global D3D11_SPEC_DATE_DAY := 4
Global D3D11_SPEC_DATE_MONTH := 6
Global D3D11_SPEC_DATE_YEAR := 2009
Global D3D11_STANDARD_COMPONENT_BIT_COUNT := 32
Global D3D11_STANDARD_COMPONENT_BIT_COUNT_DOUBLED := 64
Global D3D11_STANDARD_MAXIMUM_ELEMENT_ALIGNMENT_BYTE_MULTIPLE := 4
Global D3D11_STANDARD_PIXEL_COMPONENT_COUNT := 128
Global D3D11_STANDARD_PIXEL_ELEMENT_COUNT := 32
Global D3D11_STANDARD_VECTOR_SIZE := 4
Global D3D11_STANDARD_VERTEX_ELEMENT_COUNT := 32
Global D3D11_STANDARD_VERTEX_TOTAL_COMPONENT_COUNT := 64
Global D3D11_SUBPIXEL_FRACTIONAL_BIT_COUNT := 8
Global D3D11_SUBTEXEL_FRACTIONAL_BIT_COUNT := 8
Global D3D11_TESSELLATOR_MAX_EVEN_TESSELLATION_FACTOR := 64
Global D3D11_TESSELLATOR_MAX_ISOLINE_DENSITY_TESSELLATION_FACTOR := 64
Global D3D11_TESSELLATOR_MAX_ODD_TESSELLATION_FACTOR := 63
Global D3D11_TESSELLATOR_MAX_TESSELLATION_FACTOR := 64
Global D3D11_TESSELLATOR_MIN_EVEN_TESSELLATION_FACTOR := 2
Global D3D11_TESSELLATOR_MIN_ISOLINE_DENSITY_TESSELLATION_FACTOR := 1
Global D3D11_TESSELLATOR_MIN_ODD_TESSELLATION_FACTOR := 1
Global D3D11_TEXEL_ADDRESS_RANGE_BIT_COUNT := 16
Global D3D11_UNBOUND_MEMORY_ACCESS_RESULT := 0
Global D3D11_VIEWPORT_AND_SCISSORRECT_MAX_INDEX := 15
Global D3D11_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE := 16
Global D3D11_VIEWPORT_BOUNDS_MAX := 32767
Global D3D11_VIEWPORT_BOUNDS_MIN := -32768
Global D3D11_VS_INPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_VS_INPUT_REGISTER_COMPONENTS := 4
Global D3D11_VS_INPUT_REGISTER_COUNT := 32
Global D3D11_VS_INPUT_REGISTER_READ_PORTS := 1
Global D3D11_VS_INPUT_REGISTER_READS_PER_INST := 2
Global D3D11_VS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D11_VS_OUTPUT_REGISTER_COMPONENTS := 4
Global D3D11_VS_OUTPUT_REGISTER_COUNT := 32
Global D3D11_WHQL_CONTEXT_COUNT_FOR_RESOURCE_LIMIT := 10
Global D3D11_WHQL_DRAW_VERTEX_COUNT_2_TO_EXP := 25
Global D3D11_WHQL_DRAWINDEXED_INDEX_COUNT_2_TO_EXP := 25

D3D11.result := {}
D3D11.result[2289827844 . ""] := "D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD"
D3D11.result[2289827842 . ""] := "D3D11_ERROR_FILE_NOT_FOUND"
D3D11.result[2289827841 . ""] := "D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS"
D3D11.result[2289827843 . ""] := "D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS"


Global D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD := 2289827844
Global D3D11_ERROR_FILE_NOT_FOUND := 2289827842
Global D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS := 2289827841
Global D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS := 2289827843