;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global dinput := {}
dinput.CLSID_DirectInput := "{25E609E0-B259-11CF-BFC7-444553540000}"
dinput.CLSID_DirectInputDevice := "{25E609E1-B259-11CF-BFC7-444553540000}"
dinput.CLSID_DirectInput8 := "{25E609E4-B259-11CF-BFC7-444553540000}"
dinput.CLSID_DirectInputDevice8 := "{25E609E5-B259-11CF-BFC7-444553540000}"
dinput.IID_IDirectInputA := "{89521360-AA8A-11CF-BFC7-444553540000}"
dinput.IID_IDirectInputW := "{89521361-AA8A-11CF-BFC7-444553540000}"
dinput.IID_IDirectInput2A := "{5944E662-AA8A-11CF-BFC7-444553540000}"
dinput.IID_IDirectInput2W := "{5944E663-AA8A-11CF-BFC7-444553540000}"
dinput.IID_IDirectInput7A := "{9A4CB684-236D-11D3-8E9D-00C04F6844AE}"
dinput.IID_IDirectInput7W := "{9A4CB685-236D-11D3-8E9D-00C04F6844AE}"
dinput.IID_IDirectInput8A := "{BF798030-483A-4DA2-AA99-5D64ED369700}"
dinput.IID_IDirectInput8W := "{BF798031-483A-4DA2-AA99-5D64ED369700}"
dinput.IID_IDirectInputDeviceA := "{5944E680-C92E-11CF-BFC7-444553540000}"
dinput.IID_IDirectInputDeviceW := "{5944E681-C92E-11CF-BFC7-444553540000}"
dinput.IID_IDirectInputDevice2A := "{5944E682-C92E-11CF-BFC7-444553540000}"
dinput.IID_IDirectInputDevice2W := "{5944E683-C92E-11CF-BFC7-444553540000}"
dinput.IID_IDirectInputDevice7A := "{57D7C6BC-2356-11D3-8E9D-00C04F6844AE}"
dinput.IID_IDirectInputDevice7W := "{57D7C6BD-2356-11D3-8E9D-00C04F6844AE}"
dinput.IID_IDirectInputDevice8A := "{54D41080-DC15-4833-A41B-748F73A38179}"
dinput.IID_IDirectInputDevice8W := "{54D41081-DC15-4833-A41B-748F73A38179}"
dinput.IID_IDirectInputEffect := "{E7E1F7C0-88D2-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_XAxis := "{A36D02E0-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_YAxis := "{A36D02E1-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_ZAxis := "{A36D02E2-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_RxAxis := "{A36D02F4-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_RyAxis := "{A36D02F5-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_RzAxis := "{A36D02E3-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_Slider := "{A36D02E4-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_Button := "{A36D02F0-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_Key := "{55728220-D33C-11CF-BFC7-444553540000}"
dinput.GUID_POV := "{A36D02F2-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_Unknown := "{A36D02F3-C9F3-11CF-BFC7-444553540000}"
dinput.GUID_SysMouse := "{6F1D2B60-D5A0-11CF-BFC7-444553540000}"
dinput.GUID_SysKeyboard := "{6F1D2B61-D5A0-11CF-BFC7-444553540000}"
dinput.GUID_Joystick := "{6F1D2B70-D5A0-11CF-BFC7-444553540000}"
dinput.GUID_SysMouseEm := "{6F1D2B80-D5A0-11CF-BFC7-444553540000}"
dinput.GUID_SysMouseEm2 := "{6F1D2B81-D5A0-11CF-BFC7-444553540000}"
dinput.GUID_SysKeyboardEm := "{6F1D2B82-D5A0-11CF-BFC7-444553540000}"
dinput.GUID_SysKeyboardEm2 := "{6F1D2B83-D5A0-11CF-BFC7-444553540000}"
dinput.GUID_ConstantForce := "{13541C20-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_RampForce := "{13541C21-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_Square := "{13541C22-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_Sine := "{13541C23-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_Triangle := "{13541C24-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_SawtoothUp := "{13541C25-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_SawtoothDown := "{13541C26-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_Spring := "{13541C27-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_Damper := "{13541C28-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_Inertia := "{13541C29-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_Friction := "{13541C2A-8E33-11D0-9AD0-00A0C9A06E35}"
dinput.GUID_CustomForce := "{13541C2B-8E33-11D0-9AD0-00A0C9A06E35}"

dinput.IDirectInputEffect:= {}
dinput.IDirectInputEffect.name := "IDirectInputEffect"
dinput.IDirectInputEffect.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD,REFGUID) PURE;
    STDMETHOD(GetEffectGuid)(THIS_ LPGUID) PURE;
    STDMETHOD(GetParameters)(THIS_ LPDIEFFECT,DWORD) PURE;
    STDMETHOD(SetParameters)(THIS_ LPCDIEFFECT,DWORD) PURE;
    STDMETHOD(Start)(THIS_ DWORD,DWORD) PURE;
    STDMETHOD(Stop)(THIS) PURE;
    STDMETHOD(GetEffectStatus)(THIS_ LPDWORD) PURE;
    STDMETHOD(Download)(THIS) PURE;
    STDMETHOD(Unload)(THIS) PURE;
    STDMETHOD(Escape)(THIS_ LPDIEFFESCAPE) PURE;
"
)

dinput.IDirectInputDeviceW:= {}
dinput.IDirectInputDeviceW.name := "IDirectInputDeviceW"
dinput.IDirectInputDeviceW.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(GetCapabilities)(THIS_ LPDIDEVCAPS) PURE;
    STDMETHOD(EnumObjects)(THIS_ LPDIENUMDEVICEOBJECTSCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetProperty)(THIS_ REFGUID,LPDIPROPHEADER) PURE;
    STDMETHOD(SetProperty)(THIS_ REFGUID,LPCDIPROPHEADER) PURE;
    STDMETHOD(Acquire)(THIS) PURE;
    STDMETHOD(Unacquire)(THIS) PURE;
    STDMETHOD(GetDeviceState)(THIS_ DWORD,LPVOID) PURE;
    STDMETHOD(GetDeviceData)(THIS_ DWORD,LPDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(SetDataFormat)(THIS_ LPCDIDATAFORMAT) PURE;
    STDMETHOD(SetEventNotification)(THIS_ HANDLE) PURE;
    STDMETHOD(SetCooperativeLevel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(GetObjectInfo)(THIS_ LPDIDEVICEOBJECTINSTANCEW,DWORD,DWORD) PURE;
    STDMETHOD(GetDeviceInfo)(THIS_ LPDIDEVICEINSTANCEW) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD,REFGUID) PURE;
"
)

dinput.IDirectInputDeviceA:= {}
dinput.IDirectInputDeviceA.name := "IDirectInputDeviceA"
dinput.IDirectInputDeviceA.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(GetCapabilities)(THIS_ LPDIDEVCAPS) PURE;
    STDMETHOD(EnumObjects)(THIS_ LPDIENUMDEVICEOBJECTSCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetProperty)(THIS_ REFGUID,LPDIPROPHEADER) PURE;
    STDMETHOD(SetProperty)(THIS_ REFGUID,LPCDIPROPHEADER) PURE;
    STDMETHOD(Acquire)(THIS) PURE;
    STDMETHOD(Unacquire)(THIS) PURE;
    STDMETHOD(GetDeviceState)(THIS_ DWORD,LPVOID) PURE;
    STDMETHOD(GetDeviceData)(THIS_ DWORD,LPDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(SetDataFormat)(THIS_ LPCDIDATAFORMAT) PURE;
    STDMETHOD(SetEventNotification)(THIS_ HANDLE) PURE;
    STDMETHOD(SetCooperativeLevel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(GetObjectInfo)(THIS_ LPDIDEVICEOBJECTINSTANCEA,DWORD,DWORD) PURE;
    STDMETHOD(GetDeviceInfo)(THIS_ LPDIDEVICEINSTANCEA) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD,REFGUID) PURE;
"
)

dinput.IDirectInputDevice2W:= {}
dinput.IDirectInputDevice2W.name := "IDirectInputDevice2W"
dinput.IDirectInputDevice2W.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(GetCapabilities)(THIS_ LPDIDEVCAPS) PURE;
    STDMETHOD(EnumObjects)(THIS_ LPDIENUMDEVICEOBJECTSCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetProperty)(THIS_ REFGUID,LPDIPROPHEADER) PURE;
    STDMETHOD(SetProperty)(THIS_ REFGUID,LPCDIPROPHEADER) PURE;
    STDMETHOD(Acquire)(THIS) PURE;
    STDMETHOD(Unacquire)(THIS) PURE;
    STDMETHOD(GetDeviceState)(THIS_ DWORD,LPVOID) PURE;
    STDMETHOD(GetDeviceData)(THIS_ DWORD,LPDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(SetDataFormat)(THIS_ LPCDIDATAFORMAT) PURE;
    STDMETHOD(SetEventNotification)(THIS_ HANDLE) PURE;
    STDMETHOD(SetCooperativeLevel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(GetObjectInfo)(THIS_ LPDIDEVICEOBJECTINSTANCEW,DWORD,DWORD) PURE;
    STDMETHOD(GetDeviceInfo)(THIS_ LPDIDEVICEINSTANCEW) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD,REFGUID) PURE;
    STDMETHOD(CreateEffect)(THIS_ REFGUID,LPCDIEFFECT,LPDIRECTINPUTEFFECT *,LPUNKNOWN) PURE;
    STDMETHOD(EnumEffects)(THIS_ LPDIENUMEFFECTSCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetEffectInfo)(THIS_ LPDIEFFECTINFOW,REFGUID) PURE;
    STDMETHOD(GetForceFeedbackState)(THIS_ LPDWORD) PURE;
    STDMETHOD(SendForceFeedbackCommand)(THIS_ DWORD) PURE;
    STDMETHOD(EnumCreatedEffectObjects)(THIS_ LPDIENUMCREATEDEFFECTOBJECTSCALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(Escape)(THIS_ LPDIEFFESCAPE) PURE;
    STDMETHOD(Poll)(THIS) PURE;
    STDMETHOD(SendDeviceData)(THIS_ DWORD,LPCDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
"
)

dinput.IDirectInputDevice2A:= {}
dinput.IDirectInputDevice2A.name := "IDirectInputDevice2A"
dinput.IDirectInputDevice2A.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(GetCapabilities)(THIS_ LPDIDEVCAPS) PURE;
    STDMETHOD(EnumObjects)(THIS_ LPDIENUMDEVICEOBJECTSCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetProperty)(THIS_ REFGUID,LPDIPROPHEADER) PURE;
    STDMETHOD(SetProperty)(THIS_ REFGUID,LPCDIPROPHEADER) PURE;
    STDMETHOD(Acquire)(THIS) PURE;
    STDMETHOD(Unacquire)(THIS) PURE;
    STDMETHOD(GetDeviceState)(THIS_ DWORD,LPVOID) PURE;
    STDMETHOD(GetDeviceData)(THIS_ DWORD,LPDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(SetDataFormat)(THIS_ LPCDIDATAFORMAT) PURE;
    STDMETHOD(SetEventNotification)(THIS_ HANDLE) PURE;
    STDMETHOD(SetCooperativeLevel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(GetObjectInfo)(THIS_ LPDIDEVICEOBJECTINSTANCEA,DWORD,DWORD) PURE;
    STDMETHOD(GetDeviceInfo)(THIS_ LPDIDEVICEINSTANCEA) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD,REFGUID) PURE;
    STDMETHOD(CreateEffect)(THIS_ REFGUID,LPCDIEFFECT,LPDIRECTINPUTEFFECT *,LPUNKNOWN) PURE;
    STDMETHOD(EnumEffects)(THIS_ LPDIENUMEFFECTSCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetEffectInfo)(THIS_ LPDIEFFECTINFOA,REFGUID) PURE;
    STDMETHOD(GetForceFeedbackState)(THIS_ LPDWORD) PURE;
    STDMETHOD(SendForceFeedbackCommand)(THIS_ DWORD) PURE;
    STDMETHOD(EnumCreatedEffectObjects)(THIS_ LPDIENUMCREATEDEFFECTOBJECTSCALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(Escape)(THIS_ LPDIEFFESCAPE) PURE;
    STDMETHOD(Poll)(THIS) PURE;
    STDMETHOD(SendDeviceData)(THIS_ DWORD,LPCDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
"
)

dinput.IDirectInputDevice7W:= {}
dinput.IDirectInputDevice7W.name := "IDirectInputDevice7W"
dinput.IDirectInputDevice7W.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(GetCapabilities)(THIS_ LPDIDEVCAPS) PURE;
    STDMETHOD(EnumObjects)(THIS_ LPDIENUMDEVICEOBJECTSCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetProperty)(THIS_ REFGUID,LPDIPROPHEADER) PURE;
    STDMETHOD(SetProperty)(THIS_ REFGUID,LPCDIPROPHEADER) PURE;
    STDMETHOD(Acquire)(THIS) PURE;
    STDMETHOD(Unacquire)(THIS) PURE;
    STDMETHOD(GetDeviceState)(THIS_ DWORD,LPVOID) PURE;
    STDMETHOD(GetDeviceData)(THIS_ DWORD,LPDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(SetDataFormat)(THIS_ LPCDIDATAFORMAT) PURE;
    STDMETHOD(SetEventNotification)(THIS_ HANDLE) PURE;
    STDMETHOD(SetCooperativeLevel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(GetObjectInfo)(THIS_ LPDIDEVICEOBJECTINSTANCEW,DWORD,DWORD) PURE;
    STDMETHOD(GetDeviceInfo)(THIS_ LPDIDEVICEINSTANCEW) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD,REFGUID) PURE;
    STDMETHOD(CreateEffect)(THIS_ REFGUID,LPCDIEFFECT,LPDIRECTINPUTEFFECT *,LPUNKNOWN) PURE;
    STDMETHOD(EnumEffects)(THIS_ LPDIENUMEFFECTSCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetEffectInfo)(THIS_ LPDIEFFECTINFOW,REFGUID) PURE;
    STDMETHOD(GetForceFeedbackState)(THIS_ LPDWORD) PURE;
    STDMETHOD(SendForceFeedbackCommand)(THIS_ DWORD) PURE;
    STDMETHOD(EnumCreatedEffectObjects)(THIS_ LPDIENUMCREATEDEFFECTOBJECTSCALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(Escape)(THIS_ LPDIEFFESCAPE) PURE;
    STDMETHOD(Poll)(THIS) PURE;
    STDMETHOD(SendDeviceData)(THIS_ DWORD,LPCDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(EnumEffectsInFile)(THIS_ LPCWSTR,LPDIENUMEFFECTSINFILECALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(WriteEffectToFile)(THIS_ LPCWSTR,DWORD,LPDIFILEEFFECT,DWORD) PURE;
"
)

dinput.IDirectInputDevice7A:= {}
dinput.IDirectInputDevice7A.name := "IDirectInputDevice7A"
dinput.IDirectInputDevice7A.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(GetCapabilities)(THIS_ LPDIDEVCAPS) PURE;
    STDMETHOD(EnumObjects)(THIS_ LPDIENUMDEVICEOBJECTSCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetProperty)(THIS_ REFGUID,LPDIPROPHEADER) PURE;
    STDMETHOD(SetProperty)(THIS_ REFGUID,LPCDIPROPHEADER) PURE;
    STDMETHOD(Acquire)(THIS) PURE;
    STDMETHOD(Unacquire)(THIS) PURE;
    STDMETHOD(GetDeviceState)(THIS_ DWORD,LPVOID) PURE;
    STDMETHOD(GetDeviceData)(THIS_ DWORD,LPDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(SetDataFormat)(THIS_ LPCDIDATAFORMAT) PURE;
    STDMETHOD(SetEventNotification)(THIS_ HANDLE) PURE;
    STDMETHOD(SetCooperativeLevel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(GetObjectInfo)(THIS_ LPDIDEVICEOBJECTINSTANCEA,DWORD,DWORD) PURE;
    STDMETHOD(GetDeviceInfo)(THIS_ LPDIDEVICEINSTANCEA) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD,REFGUID) PURE;
    STDMETHOD(CreateEffect)(THIS_ REFGUID,LPCDIEFFECT,LPDIRECTINPUTEFFECT *,LPUNKNOWN) PURE;
    STDMETHOD(EnumEffects)(THIS_ LPDIENUMEFFECTSCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetEffectInfo)(THIS_ LPDIEFFECTINFOA,REFGUID) PURE;
    STDMETHOD(GetForceFeedbackState)(THIS_ LPDWORD) PURE;
    STDMETHOD(SendForceFeedbackCommand)(THIS_ DWORD) PURE;
    STDMETHOD(EnumCreatedEffectObjects)(THIS_ LPDIENUMCREATEDEFFECTOBJECTSCALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(Escape)(THIS_ LPDIEFFESCAPE) PURE;
    STDMETHOD(Poll)(THIS) PURE;
    STDMETHOD(SendDeviceData)(THIS_ DWORD,LPCDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(EnumEffectsInFile)(THIS_ LPCSTR,LPDIENUMEFFECTSINFILECALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(WriteEffectToFile)(THIS_ LPCSTR,DWORD,LPDIFILEEFFECT,DWORD) PURE;
"
)

dinput.IDirectInputDevice8W:= {}
dinput.IDirectInputDevice8W.name := "IDirectInputDevice8W"
dinput.IDirectInputDevice8W.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(GetCapabilities)(THIS_ LPDIDEVCAPS) PURE;
    STDMETHOD(EnumObjects)(THIS_ LPDIENUMDEVICEOBJECTSCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetProperty)(THIS_ REFGUID,LPDIPROPHEADER) PURE;
    STDMETHOD(SetProperty)(THIS_ REFGUID,LPCDIPROPHEADER) PURE;
    STDMETHOD(Acquire)(THIS) PURE;
    STDMETHOD(Unacquire)(THIS) PURE;
    STDMETHOD(GetDeviceState)(THIS_ DWORD,LPVOID) PURE;
    STDMETHOD(GetDeviceData)(THIS_ DWORD,LPDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(SetDataFormat)(THIS_ LPCDIDATAFORMAT) PURE;
    STDMETHOD(SetEventNotification)(THIS_ HANDLE) PURE;
    STDMETHOD(SetCooperativeLevel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(GetObjectInfo)(THIS_ LPDIDEVICEOBJECTINSTANCEW,DWORD,DWORD) PURE;
    STDMETHOD(GetDeviceInfo)(THIS_ LPDIDEVICEINSTANCEW) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD,REFGUID) PURE;
    STDMETHOD(CreateEffect)(THIS_ REFGUID,LPCDIEFFECT,LPDIRECTINPUTEFFECT *,LPUNKNOWN) PURE;
    STDMETHOD(EnumEffects)(THIS_ LPDIENUMEFFECTSCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetEffectInfo)(THIS_ LPDIEFFECTINFOW,REFGUID) PURE;
    STDMETHOD(GetForceFeedbackState)(THIS_ LPDWORD) PURE;
    STDMETHOD(SendForceFeedbackCommand)(THIS_ DWORD) PURE;
    STDMETHOD(EnumCreatedEffectObjects)(THIS_ LPDIENUMCREATEDEFFECTOBJECTSCALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(Escape)(THIS_ LPDIEFFESCAPE) PURE;
    STDMETHOD(Poll)(THIS) PURE;
    STDMETHOD(SendDeviceData)(THIS_ DWORD,LPCDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(EnumEffectsInFile)(THIS_ LPCWSTR,LPDIENUMEFFECTSINFILECALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(WriteEffectToFile)(THIS_ LPCWSTR,DWORD,LPDIFILEEFFECT,DWORD) PURE;
    STDMETHOD(BuildActionMap)(THIS_ LPDIACTIONFORMATW,LPCWSTR,DWORD) PURE;
    STDMETHOD(SetActionMap)(THIS_ LPDIACTIONFORMATW,LPCWSTR,DWORD) PURE;
    STDMETHOD(GetImageInfo)(THIS_ LPDIDEVICEIMAGEINFOHEADERW) PURE;
"
)

dinput.IDirectInputDevice8A:= {}
dinput.IDirectInputDevice8A.name := "IDirectInputDevice8A"
dinput.IDirectInputDevice8A.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(GetCapabilities)(THIS_ LPDIDEVCAPS) PURE;
    STDMETHOD(EnumObjects)(THIS_ LPDIENUMDEVICEOBJECTSCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetProperty)(THIS_ REFGUID,LPDIPROPHEADER) PURE;
    STDMETHOD(SetProperty)(THIS_ REFGUID,LPCDIPROPHEADER) PURE;
    STDMETHOD(Acquire)(THIS) PURE;
    STDMETHOD(Unacquire)(THIS) PURE;
    STDMETHOD(GetDeviceState)(THIS_ DWORD,LPVOID) PURE;
    STDMETHOD(GetDeviceData)(THIS_ DWORD,LPDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(SetDataFormat)(THIS_ LPCDIDATAFORMAT) PURE;
    STDMETHOD(SetEventNotification)(THIS_ HANDLE) PURE;
    STDMETHOD(SetCooperativeLevel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(GetObjectInfo)(THIS_ LPDIDEVICEOBJECTINSTANCEA,DWORD,DWORD) PURE;
    STDMETHOD(GetDeviceInfo)(THIS_ LPDIDEVICEINSTANCEA) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD,REFGUID) PURE;
    STDMETHOD(CreateEffect)(THIS_ REFGUID,LPCDIEFFECT,LPDIRECTINPUTEFFECT *,LPUNKNOWN) PURE;
    STDMETHOD(EnumEffects)(THIS_ LPDIENUMEFFECTSCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetEffectInfo)(THIS_ LPDIEFFECTINFOA,REFGUID) PURE;
    STDMETHOD(GetForceFeedbackState)(THIS_ LPDWORD) PURE;
    STDMETHOD(SendForceFeedbackCommand)(THIS_ DWORD) PURE;
    STDMETHOD(EnumCreatedEffectObjects)(THIS_ LPDIENUMCREATEDEFFECTOBJECTSCALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(Escape)(THIS_ LPDIEFFESCAPE) PURE;
    STDMETHOD(Poll)(THIS) PURE;
    STDMETHOD(SendDeviceData)(THIS_ DWORD,LPCDIDEVICEOBJECTDATA,LPDWORD,DWORD) PURE;
    STDMETHOD(EnumEffectsInFile)(THIS_ LPCSTR,LPDIENUMEFFECTSINFILECALLBACK,LPVOID,DWORD) PURE;
    STDMETHOD(WriteEffectToFile)(THIS_ LPCSTR,DWORD,LPDIFILEEFFECT,DWORD) PURE;
    STDMETHOD(BuildActionMap)(THIS_ LPDIACTIONFORMATA,LPCSTR,DWORD) PURE;
    STDMETHOD(SetActionMap)(THIS_ LPDIACTIONFORMATA,LPCSTR,DWORD) PURE;
    STDMETHOD(GetImageInfo)(THIS_ LPDIDEVICEIMAGEINFOHEADERA) PURE;
"
)

dinput.IDirectInputW:= {}
dinput.IDirectInputW.name := "IDirectInputW"
dinput.IDirectInputW.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(CreateDevice)(THIS_ REFGUID,LPDIRECTINPUTDEVICEW *,LPUNKNOWN) PURE;
    STDMETHOD(EnumDevices)(THIS_ DWORD,LPDIENUMDEVICESCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetDeviceStatus)(THIS_ REFGUID) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD) PURE;
"
)

dinput.IDirectInputA:= {}
dinput.IDirectInputA.name := "IDirectInputA"
dinput.IDirectInputA.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(CreateDevice)(THIS_ REFGUID,LPDIRECTINPUTDEVICEA *,LPUNKNOWN) PURE;
    STDMETHOD(EnumDevices)(THIS_ DWORD,LPDIENUMDEVICESCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetDeviceStatus)(THIS_ REFGUID) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD) PURE;
"
)

dinput.IDirectInput2W:= {}
dinput.IDirectInput2W.name := "IDirectInput2W"
dinput.IDirectInput2W.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(CreateDevice)(THIS_ REFGUID,LPDIRECTINPUTDEVICEW *,LPUNKNOWN) PURE;
    STDMETHOD(EnumDevices)(THIS_ DWORD,LPDIENUMDEVICESCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetDeviceStatus)(THIS_ REFGUID) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD) PURE;
    STDMETHOD(FindDevice)(THIS_ REFGUID,LPCWSTR,LPGUID) PURE;
"
)

dinput.IDirectInput2A:= {}
dinput.IDirectInput2A.name := "IDirectInput2A"
dinput.IDirectInput2A.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(CreateDevice)(THIS_ REFGUID,LPDIRECTINPUTDEVICEA *,LPUNKNOWN) PURE;
    STDMETHOD(EnumDevices)(THIS_ DWORD,LPDIENUMDEVICESCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetDeviceStatus)(THIS_ REFGUID) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD) PURE;
    STDMETHOD(FindDevice)(THIS_ REFGUID,LPCSTR,LPGUID) PURE;
"
)

dinput.IDirectInput7W:= {}
dinput.IDirectInput7W.name := "IDirectInput7W"
dinput.IDirectInput7W.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(CreateDevice)(THIS_ REFGUID,LPDIRECTINPUTDEVICEW *,LPUNKNOWN) PURE;
    STDMETHOD(EnumDevices)(THIS_ DWORD,LPDIENUMDEVICESCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetDeviceStatus)(THIS_ REFGUID) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD) PURE;
    STDMETHOD(FindDevice)(THIS_ REFGUID,LPCWSTR,LPGUID) PURE;
    STDMETHOD(CreateDeviceEx)(THIS_ REFGUID,REFIID,LPVOID *,LPUNKNOWN) PURE;
"
)

dinput.IDirectInput7A:= {}
dinput.IDirectInput7A.name := "IDirectInput7A"
dinput.IDirectInput7A.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(CreateDevice)(THIS_ REFGUID,LPDIRECTINPUTDEVICEA *,LPUNKNOWN) PURE;
    STDMETHOD(EnumDevices)(THIS_ DWORD,LPDIENUMDEVICESCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetDeviceStatus)(THIS_ REFGUID) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD) PURE;
    STDMETHOD(FindDevice)(THIS_ REFGUID,LPCSTR,LPGUID) PURE;
    STDMETHOD(CreateDeviceEx)(THIS_ REFGUID,REFIID,LPVOID *,LPUNKNOWN) PURE;
"
)

dinput.IDirectInput8W:= {}
dinput.IDirectInput8W.name := "IDirectInput8W"
dinput.IDirectInput8W.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(CreateDevice)(THIS_ REFGUID,LPDIRECTINPUTDEVICE8W *,LPUNKNOWN) PURE;
    STDMETHOD(EnumDevices)(THIS_ DWORD,LPDIENUMDEVICESCALLBACKW,LPVOID,DWORD) PURE;
    STDMETHOD(GetDeviceStatus)(THIS_ REFGUID) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD) PURE;
    STDMETHOD(FindDevice)(THIS_ REFGUID,LPCWSTR,LPGUID) PURE;
    STDMETHOD(EnumDevicesBySemantics)(THIS_ LPCWSTR,LPDIACTIONFORMATW,LPDIENUMDEVICESBYSEMANTICSCBW,LPVOID,DWORD) PURE;
    STDMETHOD(ConfigureDevices)(THIS_ LPDICONFIGUREDEVICESCALLBACK,LPDICONFIGUREDEVICESPARAMSW,DWORD,LPVOID) PURE;
"
)

dinput.IDirectInput8A:= {}
dinput.IDirectInput8A.name := "IDirectInput8A"
dinput.IDirectInput8A.def :=
( 
"
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj) PURE;
    STDMETHOD_(ULONG,AddRef)(THIS) PURE;
    STDMETHOD_(ULONG,Release)(THIS) PURE;
    STDMETHOD(CreateDevice)(THIS_ REFGUID,LPDIRECTINPUTDEVICE8A *,LPUNKNOWN) PURE;
    STDMETHOD(EnumDevices)(THIS_ DWORD,LPDIENUMDEVICESCALLBACKA,LPVOID,DWORD) PURE;
    STDMETHOD(GetDeviceStatus)(THIS_ REFGUID) PURE;
    STDMETHOD(RunControlPanel)(THIS_ HWND,DWORD) PURE;
    STDMETHOD(Initialize)(THIS_ HINSTANCE,DWORD) PURE;
    STDMETHOD(FindDevice)(THIS_ REFGUID,LPCSTR,LPGUID) PURE;
    STDMETHOD(EnumDevicesBySemantics)(THIS_ LPCSTR,LPDIACTIONFORMATA,LPDIENUMDEVICESBYSEMANTICSCBA,LPVOID,DWORD) PURE;
    STDMETHOD(ConfigureDevices)(THIS_ LPDICONFIGUREDEVICESCALLBACK,LPDICONFIGUREDEVICESPARAMSA,DWORD,LPVOID) PURE;
"
)

dinput.constant := {}
dinput.constant[1 . ""] := "DI8DEVCLASS_DEVICE"
dinput.constant[4 . ""] := "DI8DEVCLASS_GAMECTRL"
dinput.constant[3 . ""] := "DI8DEVCLASS_KEYBOARD"
dinput.constant[2 . ""] := "DI8DEVCLASS_POINTER"
dinput.constant[4 . ""] := "DI8DEVTYPE1STPERSON_SHOOTER"
dinput.constant[3 . ""] := "DI8DEVTYPE1STPERSON_SIXDOF"
dinput.constant[2 . ""] := "DI8DEVTYPE1STPERSON_UNKNOWN"
dinput.constant[24 . ""] := "DI8DEVTYPE_1STPERSON"
dinput.constant[17 . ""] := "DI8DEVTYPE_DEVICE"
dinput.constant[25 . ""] := "DI8DEVTYPE_DEVICECTRL"
dinput.constant[22 . ""] := "DI8DEVTYPE_DRIVING"
dinput.constant[23 . ""] := "DI8DEVTYPE_FLIGHT"
dinput.constant[21 . ""] := "DI8DEVTYPE_GAMEPAD"
dinput.constant[20 . ""] := "DI8DEVTYPE_JOYSTICK"
dinput.constant[19 . ""] := "DI8DEVTYPE_KEYBOARD"
dinput.constant[1 . ""] := "DI8DEVTYPE_LIMITEDGAMESUBTYPE"
dinput.constant[18 . ""] := "DI8DEVTYPE_MOUSE"
dinput.constant[27 . ""] := "DI8DEVTYPE_REMOTE"
dinput.constant[26 . ""] := "DI8DEVTYPE_SCREENPOINTER"
dinput.constant[28 . ""] := "DI8DEVTYPE_SUPPLEMENTAL"
dinput.constant[3 . ""] := "DI8DEVTYPEDEVICECTRL_COMMSSELECTION"
dinput.constant[4 . ""] := "DI8DEVTYPEDEVICECTRL_COMMSSELECTION_HARDWIRED"
dinput.constant[2 . ""] := "DI8DEVTYPEDEVICECTRL_UNKNOWN"
dinput.constant[2 . ""] := "DI8DEVTYPEDRIVING_COMBINEDPEDALS"
dinput.constant[3 . ""] := "DI8DEVTYPEDRIVING_DUALPEDALS"
dinput.constant[5 . ""] := "DI8DEVTYPEDRIVING_HANDHELD"
dinput.constant[4 . ""] := "DI8DEVTYPEDRIVING_THREEPEDALS"
dinput.constant[4 . ""] := "DI8DEVTYPEFLIGHT_RC"
dinput.constant[2 . ""] := "DI8DEVTYPEFLIGHT_STICK"
dinput.constant[3 . ""] := "DI8DEVTYPEFLIGHT_YOKE"
dinput.constant[2 . ""] := "DI8DEVTYPEGAMEPAD_STANDARD"
dinput.constant[3 . ""] := "DI8DEVTYPEGAMEPAD_TILT"
dinput.constant[2 . ""] := "DI8DEVTYPEJOYSTICK_STANDARD"
dinput.constant[12 . ""] := "DI8DEVTYPEKEYBOARD_J3100"
dinput.constant[10 . ""] := "DI8DEVTYPEKEYBOARD_JAPAN106"
dinput.constant[11 . ""] := "DI8DEVTYPEKEYBOARD_JAPANAX"
dinput.constant[7 . ""] := "DI8DEVTYPEKEYBOARD_NEC98"
dinput.constant[9 . ""] := "DI8DEVTYPEKEYBOARD_NEC98106"
dinput.constant[8 . ""] := "DI8DEVTYPEKEYBOARD_NEC98LAPTOP"
dinput.constant[5 . ""] := "DI8DEVTYPEKEYBOARD_NOKIA1050"
dinput.constant[6 . ""] := "DI8DEVTYPEKEYBOARD_NOKIA9140"
dinput.constant[2 . ""] := "DI8DEVTYPEKEYBOARD_OLIVETTI"
dinput.constant[3 . ""] := "DI8DEVTYPEKEYBOARD_PCAT"
dinput.constant[4 . ""] := "DI8DEVTYPEKEYBOARD_PCENH"
dinput.constant[1 . ""] := "DI8DEVTYPEKEYBOARD_PCXT"
dinput.constant[6 . ""] := "DI8DEVTYPEMOUSE_ABSOLUTE"
dinput.constant[3 . ""] := "DI8DEVTYPEMOUSE_FINGERSTICK"
dinput.constant[4 . ""] := "DI8DEVTYPEMOUSE_TOUCHPAD"
dinput.constant[5 . ""] := "DI8DEVTYPEMOUSE_TRACKBALL"
dinput.constant[2 . ""] := "DI8DEVTYPEMOUSE_TRADITIONAL"
dinput.constant[1 . ""] := "DI8DEVTYPEMOUSE_UNKNOWN"
dinput.constant[2 . ""] := "DI8DEVTYPEREMOTE_UNKNOWN"
dinput.constant[3 . ""] := "DI8DEVTYPESCREENPTR_LIGHTGUN"
dinput.constant[4 . ""] := "DI8DEVTYPESCREENPTR_LIGHTPEN"
dinput.constant[5 . ""] := "DI8DEVTYPESCREENPTR_TOUCH"
dinput.constant[2 . ""] := "DI8DEVTYPESCREENPTR_UNKNOWN"
dinput.constant[3 . ""] := "DI8DEVTYPESUPPLEMENTAL_2NDHANDCONTROLLER"
dinput.constant[10 . ""] := "DI8DEVTYPESUPPLEMENTAL_COMBINEDPEDALS"
dinput.constant[11 . ""] := "DI8DEVTYPESUPPLEMENTAL_DUALPEDALS"
dinput.constant[5 . ""] := "DI8DEVTYPESUPPLEMENTAL_HANDTRACKER"
dinput.constant[4 . ""] := "DI8DEVTYPESUPPLEMENTAL_HEADTRACKER"
dinput.constant[13 . ""] := "DI8DEVTYPESUPPLEMENTAL_RUDDERPEDALS"
dinput.constant[7 . ""] := "DI8DEVTYPESUPPLEMENTAL_SHIFTER"
dinput.constant[6 . ""] := "DI8DEVTYPESUPPLEMENTAL_SHIFTSTICKGATE"
dinput.constant[9 . ""] := "DI8DEVTYPESUPPLEMENTAL_SPLITTHROTTLE"
dinput.constant[12 . ""] := "DI8DEVTYPESUPPLEMENTAL_THREEPEDALS"
dinput.constant[8 . ""] := "DI8DEVTYPESUPPLEMENTAL_THROTTLE"
dinput.constant[2 . ""] := "DI8DEVTYPESUPPLEMENTAL_UNKNOWN"
dinput.constant[100 . ""] := "DI_DEGREES"
dinput.constant[0x00000003 . ""] := "DI_DOWNLOADSKIPPED"
dinput.constant[0x00000004 . ""] := "DI_EFFECTRESTARTED"
dinput.constant[10000 . ""] := "DI_FFNOMINALMAX"
dinput.constant[0x00000002 . ""] := "DI_POLLEDDEVICE"
dinput.constant[1000000 . ""] := "DI_SECONDS"
dinput.constant[0x0000000B . ""] := "DI_SETTINGSNOTSAVED"
dinput.constant[0x00000008 . ""] := "DI_TRUNCATED"
dinput.constant[0x0000000C . ""] := "DI_TRUNCATEDANDRESTARTED"
dinput.constant[0x00000013 . ""] := "DI_WRITEPROTECT"
dinput.constant[16 . ""] := "DIA_APPFIXED"
dinput.constant[2 . ""] := "DIA_APPMAPPED"
dinput.constant[4 . ""] := "DIA_APPNOMAP"
dinput.constant[1 . ""] := "DIA_FORCEFEEDBACK"
dinput.constant[8 . ""] := "DIA_NORANGE"
dinput.constant[4294967295 . ""] := "DIAFTS_NEWDEVICEHIGH"
dinput.constant[4294967295 . ""] := "DIAFTS_NEWDEVICELOW"
dinput.constant[2 . ""] := "DIAH_APPREQUESTED"
dinput.constant[32 . ""] := "DIAH_DEFAULT"
dinput.constant[2147483648 . ""] := "DIAH_ERROR"
dinput.constant[4 . ""] := "DIAH_HWAPP"
dinput.constant[8 . ""] := "DIAH_HWDEFAULT"
dinput.constant[1 . ""] := "DIAH_USERCONFIG"
dinput.constant[4278206977 . ""] := "DIAXIS_ANY_1"
dinput.constant[4278206978 . ""] := "DIAXIS_ANY_2"
dinput.constant[4278206979 . ""] := "DIAXIS_ANY_3"
dinput.constant[4278206980 . ""] := "DIAXIS_ANY_4"
dinput.constant[4278436353 . ""] := "DIAXIS_ANY_A_1"
dinput.constant[4278436354 . ""] := "DIAXIS_ANY_A_2"
dinput.constant[4278469121 . ""] := "DIAXIS_ANY_B_1"
dinput.constant[4278469122 . ""] := "DIAXIS_ANY_B_2"
dinput.constant[4278501889 . ""] := "DIAXIS_ANY_C_1"
dinput.constant[4278501890 . ""] := "DIAXIS_ANY_C_2"
dinput.constant[4278338049 . ""] := "DIAXIS_ANY_R_1"
dinput.constant[4278338050 . ""] := "DIAXIS_ANY_R_2"
dinput.constant[4278534657 . ""] := "DIAXIS_ANY_S_1"
dinput.constant[4278534658 . ""] := "DIAXIS_ANY_S_2"
dinput.constant[4278370817 . ""] := "DIAXIS_ANY_U_1"
dinput.constant[4278370818 . ""] := "DIAXIS_ANY_U_2"
dinput.constant[4278403585 . ""] := "DIAXIS_ANY_V_1"
dinput.constant[4278403586 . ""] := "DIAXIS_ANY_V_2"
dinput.constant[4278239745 . ""] := "DIAXIS_ANY_X_1"
dinput.constant[4278239746 . ""] := "DIAXIS_ANY_X_2"
dinput.constant[4278272513 . ""] := "DIAXIS_ANY_Y_1"
dinput.constant[4278272514 . ""] := "DIAXIS_ANY_Y_2"
dinput.constant[4278305281 . ""] := "DIAXIS_ANY_Z_1"
dinput.constant[4278305282 . ""] := "DIAXIS_ANY_Z_2"
dinput.constant[1 . ""] := "DICD_EDIT"
dinput.constant[8 . ""] := "DIDAL_BOTTOMALIGNED"
dinput.constant[1 . ""] := "DIDAL_LEFTALIGNED"
dinput.constant[2 . ""] := "DIDAL_RIGHTALIGNED"
dinput.constant[4 . ""] := "DIDAL_TOPALIGNED"
dinput.constant[4 . ""] := "DIDBAM_HWDEFAULTS"
dinput.constant[2 . ""] := "DIDBAM_INITIALIZE"
dinput.constant[1 . ""] := "DIDBAM_PRESERVE"
dinput.constant[65536 . ""] := "DIDC_ALIAS"
dinput.constant[1 . ""] := "DIDC_ATTACHED"
dinput.constant[16384 . ""] := "DIDC_DEADBAND"
dinput.constant[4 . ""] := "DIDC_EMULATED"
dinput.constant[512 . ""] := "DIDC_FFATTACK"
dinput.constant[1024 . ""] := "DIDC_FFFADE"
dinput.constant[256 . ""] := "DIDC_FORCEFEEDBACK"
dinput.constant[262144 . ""] := "DIDC_HIDDEN"
dinput.constant[131072 . ""] := "DIDC_PHANTOM"
dinput.constant[8 . ""] := "DIDC_POLLEDDATAFORMAT"
dinput.constant[2 . ""] := "DIDC_POLLEDDEVICE"
dinput.constant[4096 . ""] := "DIDC_POSNEGCOEFFICIENTS"
dinput.constant[8192 . ""] := "DIDC_POSNEGSATURATION"
dinput.constant[2048 . ""] := "DIDC_SATURATION"
dinput.constant[32768 . ""] := "DIDC_STARTDELAY"
dinput.constant[1 . ""] := "DIDEVTYPE_DEVICE"
dinput.constant[65536 . ""] := "DIDEVTYPE_HID"
dinput.constant[4 . ""] := "DIDEVTYPE_JOYSTICK"
dinput.constant[3 . ""] := "DIDEVTYPE_KEYBOARD"
dinput.constant[2 . ""] := "DIDEVTYPE_MOUSE"
dinput.constant[3 . ""] := "DIDEVTYPEJOYSTICK_FLIGHTSTICK"
dinput.constant[4 . ""] := "DIDEVTYPEJOYSTICK_GAMEPAD"
dinput.constant[7 . ""] := "DIDEVTYPEJOYSTICK_HEADTRACKER"
dinput.constant[5 . ""] := "DIDEVTYPEJOYSTICK_RUDDER"
dinput.constant[2 . ""] := "DIDEVTYPEJOYSTICK_TRADITIONAL"
dinput.constant[1 . ""] := "DIDEVTYPEJOYSTICK_UNKNOWN"
dinput.constant[6 . ""] := "DIDEVTYPEJOYSTICK_WHEEL"
dinput.constant[12 . ""] := "DIDEVTYPEKEYBOARD_J3100"
dinput.constant[10 . ""] := "DIDEVTYPEKEYBOARD_JAPAN106"
dinput.constant[11 . ""] := "DIDEVTYPEKEYBOARD_JAPANAX"
dinput.constant[7 . ""] := "DIDEVTYPEKEYBOARD_NEC98"
dinput.constant[9 . ""] := "DIDEVTYPEKEYBOARD_NEC98106"
dinput.constant[8 . ""] := "DIDEVTYPEKEYBOARD_NEC98LAPTOP"
dinput.constant[5 . ""] := "DIDEVTYPEKEYBOARD_NOKIA1050"
dinput.constant[6 . ""] := "DIDEVTYPEKEYBOARD_NOKIA9140"
dinput.constant[2 . ""] := "DIDEVTYPEKEYBOARD_OLIVETTI"
dinput.constant[3 . ""] := "DIDEVTYPEKEYBOARD_PCAT"
dinput.constant[4 . ""] := "DIDEVTYPEKEYBOARD_PCENH"
dinput.constant[1 . ""] := "DIDEVTYPEKEYBOARD_PCXT"
dinput.constant[3 . ""] := "DIDEVTYPEMOUSE_FINGERSTICK"
dinput.constant[4 . ""] := "DIDEVTYPEMOUSE_TOUCHPAD"
dinput.constant[5 . ""] := "DIDEVTYPEMOUSE_TRACKBALL"
dinput.constant[2 . ""] := "DIDEVTYPEMOUSE_TRADITIONAL"
dinput.constant[1 . ""] := "DIDEVTYPEMOUSE_UNKNOWN"
dinput.constant[1 . ""] := "DIDF_ABSAXIS"
dinput.constant[2 . ""] := "DIDF_RELAXIS"
dinput.constant[2 . ""] := "DIDFT_ABSAXIS"
dinput.constant[134217728 . ""] := "DIDFT_ALIAS"
dinput.constant[16776960 . ""] := "DIDFT_ANYINSTANCE"
dinput.constant[3 . ""] := "DIDFT_AXIS"
dinput.constant[12 . ""] := "DIDFT_BUTTON"
dinput.constant[64 . ""] := "DIDFT_COLLECTION"
dinput.constant[16777216 . ""] := "DIDFT_FFACTUATOR"
dinput.constant[33554432 . ""] := "DIDFT_FFEFFECTTRIGGER"
dinput.constant[16776960 . ""] := "DIDFT_NOCOLLECTION"
dinput.constant[128 . ""] := "DIDFT_NODATA"
dinput.constant[2147483648 . ""] := "DIDFT_OPTIONAL"
dinput.constant[268435456 . ""] := "DIDFT_OUTPUT"
dinput.constant[16 . ""] := "DIDFT_POV"
dinput.constant[4 . ""] := "DIDFT_PSHBUTTON"
dinput.constant[1 . ""] := "DIDFT_RELAXIS"
dinput.constant[8 . ""] := "DIDFT_TGLBUTTON"
dinput.constant[67108864 . ""] := "DIDFT_VENDORDEFINED"
dinput.constant[1 . ""] := "DIDIFT_CONFIGURATION"
dinput.constant[2 . ""] := "DIDIFT_OVERLAY"
dinput.constant[768 . ""] := "DIDOI_ASPECTACCEL"
dinput.constant[1024 . ""] := "DIDOI_ASPECTFORCE"
dinput.constant[3840 . ""] := "DIDOI_ASPECTMASK"
dinput.constant[256 . ""] := "DIDOI_ASPECTPOSITION"
dinput.constant[512 . ""] := "DIDOI_ASPECTVELOCITY"
dinput.constant[1 . ""] := "DIDOI_FFACTUATOR"
dinput.constant[2 . ""] := "DIDOI_FFEFFECTTRIGGER"
dinput.constant[65536 . ""] := "DIDOI_GUIDISUSAGE"
dinput.constant[32768 . ""] := "DIDOI_POLLED"
dinput.constant[2 . ""] := "DIDSAM_FORCESAVE"
dinput.constant[1 . ""] := "DIDSAM_NOUSER"
dinput.constant[4294967295 . ""] := "DIEB_NOTRIGGER"
dinput.constant[1 . ""] := "DIEDBS_MAPPEDPRI1"
dinput.constant[2 . ""] := "DIEDBS_MAPPEDPRI2"
dinput.constant[32 . ""] := "DIEDBS_NEWDEVICE"
dinput.constant[16 . ""] := "DIEDBS_RECENTDEVICE"
dinput.constant[4096 . ""] := "DIEDBSFL_AVAILABLEDEVICES"
dinput.constant[8192 . ""] := "DIEDBSFL_MULTIMICEKEYBOARDS"
dinput.constant[16384 . ""] := "DIEDBSFL_NONGAMINGDEVICES"
dinput.constant[16 . ""] := "DIEDBSFL_THISUSER"
dinput.constant[28944 . ""] := "DIEDBSFL_VALID"
dinput.constant[1 . ""] := "DIEDFL_ATTACHEDONLY"
dinput.constant[256 . ""] := "DIEDFL_FORCEFEEDBACK"
dinput.constant[65536 . ""] := "DIEDFL_INCLUDEALIASES"
dinput.constant[262144 . ""] := "DIEDFL_INCLUDEHIDDEN"
dinput.constant[131072 . ""] := "DIEDFL_INCLUDEPHANTOMS"
dinput.constant[16 . ""] := "DIEFF_CARTESIAN"
dinput.constant[1 . ""] := "DIEFF_OBJECTIDS"
dinput.constant[2 . ""] := "DIEFF_OBJECTOFFSETS"
dinput.constant[32 . ""] := "DIEFF_POLAR"
dinput.constant[64 . ""] := "DIEFF_SPHERICAL"
dinput.constant[4 . ""] := "DIEFT_CONDITION"
dinput.constant[1 . ""] := "DIEFT_CONSTANTFORCE"
dinput.constant[5 . ""] := "DIEFT_CUSTOMFORCE"
dinput.constant[16384 . ""] := "DIEFT_DEADBAND"
dinput.constant[512 . ""] := "DIEFT_FFATTACK"
dinput.constant[1024 . ""] := "DIEFT_FFFADE"
dinput.constant[255 . ""] := "DIEFT_HARDWARE"
dinput.constant[3 . ""] := "DIEFT_PERIODIC"
dinput.constant[4096 . ""] := "DIEFT_POSNEGCOEFFICIENTS"
dinput.constant[8192 . ""] := "DIEFT_POSNEGSATURATION"
dinput.constant[2 . ""] := "DIEFT_RAMPFORCE"
dinput.constant[2048 . ""] := "DIEFT_SATURATION"
dinput.constant[32768 . ""] := "DIEFT_STARTDELAY"
dinput.constant[2 . ""] := "DIEGES_EMULATED"
dinput.constant[1 . ""] := "DIEGES_PLAYING"
dinput.constant[1 . ""] := "DIENUM_CONTINUE"
dinput.constant[511 . ""] := "DIEP_ALLPARAMS"
dinput.constant[511 . ""] := "DIEP_ALLPARAMS_DX5"
dinput.constant[32 . ""] := "DIEP_AXES"
dinput.constant[64 . ""] := "DIEP_DIRECTION"
dinput.constant[1 . ""] := "DIEP_DURATION"
dinput.constant[128 . ""] := "DIEP_ENVELOPE"
dinput.constant[4 . ""] := "DIEP_GAIN"
dinput.constant[2147483648 . ""] := "DIEP_NODOWNLOAD"
dinput.constant[1073741824 . ""] := "DIEP_NORESTART"
dinput.constant[2 . ""] := "DIEP_SAMPLEPERIOD"
dinput.constant[536870912 . ""] := "DIEP_START"
dinput.constant[512 . ""] := "DIEP_STARTDELAY"
dinput.constant[8 . ""] := "DIEP_TRIGGERBUTTON"
dinput.constant[16 . ""] := "DIEP_TRIGGERREPEATINTERVAL"
dinput.constant[256 . ""] := "DIEP_TYPESPECIFICPARAMS"
dinput.constant[0x80040201 . ""] := "DIERR_DEVICEFULL"
dinput.constant[0x80040208 . ""] := "DIERR_EFFECTPLAYING"
dinput.constant[0x80040204 . ""] := "DIERR_HASEFFECTS"
dinput.constant[0x80040206 . ""] := "DIERR_INCOMPLETEEFFECT"
dinput.constant[0x80040200 . ""] := "DIERR_INSUFFICIENTPRIVS"
dinput.constant[0x8004020B . ""] := "DIERR_MAPFILEFAIL"
dinput.constant[0x80040202 . ""] := "DIERR_MOREDATA"
dinput.constant[0x80040207 . ""] := "DIERR_NOTBUFFERED"
dinput.constant[0x80040203 . ""] := "DIERR_NOTDOWNLOADED"
dinput.constant[0x80040205 . ""] := "DIERR_NOTEXCLUSIVEACQUIRED"
dinput.constant[0x8004020A . ""] := "DIERR_REPORTFULL"
dinput.constant[0x80040209 . ""] := "DIERR_UNPLUGGED"
dinput.constant[2147483648 . ""] := "DIES_NODOWNLOAD"
dinput.constant[1 . ""] := "DIES_SOLO"
dinput.constant[1 . ""] := "DIFEF_INCLUDENONSTANDARD"
dinput.constant[16 . ""] := "DIFEF_MODIFYIFNEEDED"
dinput.constant[1 . ""] := "DIGDD_PEEK"
dinput.constant[32 . ""] := "DIGFFS_ACTUATORSOFF"
dinput.constant[16 . ""] := "DIGFFS_ACTUATORSON"
dinput.constant[2147483648 . ""] := "DIGFFS_DEVICELOST"
dinput.constant[1 . ""] := "DIGFFS_EMPTY"
dinput.constant[4 . ""] := "DIGFFS_PAUSED"
dinput.constant[128 . ""] := "DIGFFS_POWEROFF"
dinput.constant[64 . ""] := "DIGFFS_POWERON"
dinput.constant[512 . ""] := "DIGFFS_SAFETYSWITCHOFF"
dinput.constant[256 . ""] := "DIGFFS_SAFETYSWITCHON"
dinput.constant[2 . ""] := "DIGFFS_STOPPED"
dinput.constant[2048 . ""] := "DIGFFS_USERFFSWITCHOFF"
dinput.constant[1024 . ""] := "DIGFFS_USERFFSWITCHON"
dinput.constant[11 . ""] := "DIK_0"
dinput.constant[2 . ""] := "DIK_1"
dinput.constant[3 . ""] := "DIK_2"
dinput.constant[4 . ""] := "DIK_3"
dinput.constant[5 . ""] := "DIK_4"
dinput.constant[6 . ""] := "DIK_5"
dinput.constant[7 . ""] := "DIK_6"
dinput.constant[8 . ""] := "DIK_7"
dinput.constant[9 . ""] := "DIK_8"
dinput.constant[10 . ""] := "DIK_9"
dinput.constant[30 . ""] := "DIK_A"
dinput.constant[40 . ""] := "DIK_APOSTROPHE"
dinput.constant[48 . ""] := "DIK_B"
dinput.constant[43 . ""] := "DIK_BACKSLASH"
dinput.constant[46 . ""] := "DIK_C"
dinput.constant[58 . ""] := "DIK_CAPITAL"
dinput.constant[51 . ""] := "DIK_COMMA"
dinput.constant[32 . ""] := "DIK_D"
dinput.constant[18 . ""] := "DIK_E"
dinput.constant[13 . ""] := "DIK_EQUALS"
dinput.constant[1 . ""] := "DIK_ESCAPE"
dinput.constant[33 . ""] := "DIK_F"
dinput.constant[59 . ""] := "DIK_F1"
dinput.constant[68 . ""] := "DIK_F10"
dinput.constant[87 . ""] := "DIK_F11"
dinput.constant[88 . ""] := "DIK_F12"
dinput.constant[60 . ""] := "DIK_F2"
dinput.constant[61 . ""] := "DIK_F3"
dinput.constant[62 . ""] := "DIK_F4"
dinput.constant[63 . ""] := "DIK_F5"
dinput.constant[64 . ""] := "DIK_F6"
dinput.constant[65 . ""] := "DIK_F7"
dinput.constant[66 . ""] := "DIK_F8"
dinput.constant[67 . ""] := "DIK_F9"
dinput.constant[34 . ""] := "DIK_G"
dinput.constant[35 . ""] := "DIK_H"
dinput.constant[23 . ""] := "DIK_I"
dinput.constant[36 . ""] := "DIK_J"
dinput.constant[37 . ""] := "DIK_K"
dinput.constant[38 . ""] := "DIK_L"
dinput.constant[26 . ""] := "DIK_LBRACKET"
dinput.constant[29 . ""] := "DIK_LCONTROL"
dinput.constant[42 . ""] := "DIK_LSHIFT"
dinput.constant[50 . ""] := "DIK_M"
dinput.constant[49 . ""] := "DIK_N"
dinput.constant[69 . ""] := "DIK_NUMLOCK"
dinput.constant[82 . ""] := "DIK_NUMPAD0"
dinput.constant[79 . ""] := "DIK_NUMPAD1"
dinput.constant[80 . ""] := "DIK_NUMPAD2"
dinput.constant[81 . ""] := "DIK_NUMPAD3"
dinput.constant[75 . ""] := "DIK_NUMPAD4"
dinput.constant[76 . ""] := "DIK_NUMPAD5"
dinput.constant[77 . ""] := "DIK_NUMPAD6"
dinput.constant[71 . ""] := "DIK_NUMPAD7"
dinput.constant[72 . ""] := "DIK_NUMPAD8"
dinput.constant[73 . ""] := "DIK_NUMPAD9"
dinput.constant[24 . ""] := "DIK_O"
dinput.constant[25 . ""] := "DIK_P"
dinput.constant[16 . ""] := "DIK_Q"
dinput.constant[19 . ""] := "DIK_R"
dinput.constant[27 . ""] := "DIK_RBRACKET"
dinput.constant[157 . ""] := "DIK_RCONTROL"
dinput.constant[54 . ""] := "DIK_RSHIFT"
dinput.constant[31 . ""] := "DIK_S"
dinput.constant[39 . ""] := "DIK_SEMICOLON"
dinput.constant[57 . ""] := "DIK_SPACE"
dinput.constant[183 . ""] := "DIK_SYSRQ"
dinput.constant[20 . ""] := "DIK_T"
dinput.constant[15 . ""] := "DIK_TAB"
dinput.constant[22 . ""] := "DIK_U"
dinput.constant[47 . ""] := "DIK_V"
dinput.constant[17 . ""] := "DIK_W"
dinput.constant[45 . ""] := "DIK_X"
dinput.constant[21 . ""] := "DIK_Y"
dinput.constant[44 . ""] := "DIK_Z"
dinput.constant[2164261899 . ""] := "DIKEYBOARD_0"
dinput.constant[2164261890 . ""] := "DIKEYBOARD_1"
dinput.constant[2164261891 . ""] := "DIKEYBOARD_2"
dinput.constant[2164261892 . ""] := "DIKEYBOARD_3"
dinput.constant[2164261893 . ""] := "DIKEYBOARD_4"
dinput.constant[2164261894 . ""] := "DIKEYBOARD_5"
dinput.constant[2164261895 . ""] := "DIKEYBOARD_6"
dinput.constant[2164261896 . ""] := "DIKEYBOARD_7"
dinput.constant[2164261897 . ""] := "DIKEYBOARD_8"
dinput.constant[2164261898 . ""] := "DIKEYBOARD_9"
dinput.constant[2164261918 . ""] := "DIKEYBOARD_A"
dinput.constant[2164261928 . ""] := "DIKEYBOARD_APOSTROPHE"
dinput.constant[2164261936 . ""] := "DIKEYBOARD_B"
dinput.constant[2164261931 . ""] := "DIKEYBOARD_BACKSLASH"
dinput.constant[2164261934 . ""] := "DIKEYBOARD_C"
dinput.constant[2164261946 . ""] := "DIKEYBOARD_CAPITAL"
dinput.constant[2164261939 . ""] := "DIKEYBOARD_COMMA"
dinput.constant[2164261920 . ""] := "DIKEYBOARD_D"
dinput.constant[2164261906 . ""] := "DIKEYBOARD_E"
dinput.constant[2164261901 . ""] := "DIKEYBOARD_EQUALS"
dinput.constant[2164261889 . ""] := "DIKEYBOARD_ESCAPE"
dinput.constant[2164261921 . ""] := "DIKEYBOARD_F"
dinput.constant[2164261947 . ""] := "DIKEYBOARD_F1"
dinput.constant[2164261956 . ""] := "DIKEYBOARD_F10"
dinput.constant[2164261975 . ""] := "DIKEYBOARD_F11"
dinput.constant[2164261976 . ""] := "DIKEYBOARD_F12"
dinput.constant[2164261948 . ""] := "DIKEYBOARD_F2"
dinput.constant[2164261949 . ""] := "DIKEYBOARD_F3"
dinput.constant[2164261950 . ""] := "DIKEYBOARD_F4"
dinput.constant[2164261951 . ""] := "DIKEYBOARD_F5"
dinput.constant[2164261952 . ""] := "DIKEYBOARD_F6"
dinput.constant[2164261953 . ""] := "DIKEYBOARD_F7"
dinput.constant[2164261954 . ""] := "DIKEYBOARD_F8"
dinput.constant[2164261955 . ""] := "DIKEYBOARD_F9"
dinput.constant[2164261922 . ""] := "DIKEYBOARD_G"
dinput.constant[2164261923 . ""] := "DIKEYBOARD_H"
dinput.constant[2164261911 . ""] := "DIKEYBOARD_I"
dinput.constant[2164261924 . ""] := "DIKEYBOARD_J"
dinput.constant[2164261925 . ""] := "DIKEYBOARD_K"
dinput.constant[2164261926 . ""] := "DIKEYBOARD_L"
dinput.constant[2164261914 . ""] := "DIKEYBOARD_LBRACKET"
dinput.constant[2164261917 . ""] := "DIKEYBOARD_LCONTROL"
dinput.constant[2164261930 . ""] := "DIKEYBOARD_LSHIFT"
dinput.constant[2164261938 . ""] := "DIKEYBOARD_M"
dinput.constant[2164261937 . ""] := "DIKEYBOARD_N"
dinput.constant[2164261957 . ""] := "DIKEYBOARD_NUMLOCK"
dinput.constant[2164261970 . ""] := "DIKEYBOARD_NUMPAD0"
dinput.constant[2164261967 . ""] := "DIKEYBOARD_NUMPAD1"
dinput.constant[2164261968 . ""] := "DIKEYBOARD_NUMPAD2"
dinput.constant[2164261969 . ""] := "DIKEYBOARD_NUMPAD3"
dinput.constant[2164261963 . ""] := "DIKEYBOARD_NUMPAD4"
dinput.constant[2164261964 . ""] := "DIKEYBOARD_NUMPAD5"
dinput.constant[2164261965 . ""] := "DIKEYBOARD_NUMPAD6"
dinput.constant[2164261959 . ""] := "DIKEYBOARD_NUMPAD7"
dinput.constant[2164261960 . ""] := "DIKEYBOARD_NUMPAD8"
dinput.constant[2164261961 . ""] := "DIKEYBOARD_NUMPAD9"
dinput.constant[2164261912 . ""] := "DIKEYBOARD_O"
dinput.constant[2164261913 . ""] := "DIKEYBOARD_P"
dinput.constant[2164261904 . ""] := "DIKEYBOARD_Q"
dinput.constant[2164261907 . ""] := "DIKEYBOARD_R"
dinput.constant[2164261915 . ""] := "DIKEYBOARD_RBRACKET"
dinput.constant[2164262045 . ""] := "DIKEYBOARD_RCONTROL"
dinput.constant[2164261942 . ""] := "DIKEYBOARD_RSHIFT"
dinput.constant[2164261919 . ""] := "DIKEYBOARD_S"
dinput.constant[2164261927 . ""] := "DIKEYBOARD_SEMICOLON"
dinput.constant[2164261945 . ""] := "DIKEYBOARD_SPACE"
dinput.constant[2164262071 . ""] := "DIKEYBOARD_SYSRQ"
dinput.constant[2164261908 . ""] := "DIKEYBOARD_T"
dinput.constant[2164261903 . ""] := "DIKEYBOARD_TAB"
dinput.constant[2164261910 . ""] := "DIKEYBOARD_U"
dinput.constant[2164261935 . ""] := "DIKEYBOARD_V"
dinput.constant[2164261905 . ""] := "DIKEYBOARD_W"
dinput.constant[2164261933 . ""] := "DIKEYBOARD_X"
dinput.constant[2164261909 . ""] := "DIKEYBOARD_Y"
dinput.constant[2164261932 . ""] := "DIKEYBOARD_Z"
dinput.constant[2 . ""] := "DIPH_BYID"
dinput.constant[1 . ""] := "DIPH_BYOFFSET"
dinput.constant[3 . ""] := "DIPH_BYUSAGE"
dinput.constant[4278208001 . ""] := "DIPOV_ANY_1"
dinput.constant[4278208002 . ""] := "DIPOV_ANY_2"
dinput.constant[4278208003 . ""] := "DIPOV_ANY_3"
dinput.constant[4278208004 . ""] := "DIPOV_ANY_4"
dinput.constant[1 . ""] := "DIPROPAUTOCENTER_ON"
dinput.constant[1 . ""] := "DIPROPAXISMODE_REL"
dinput.constant[1 . ""] := "DIPROPCALIBRATIONMODE_RAW"
dinput.constant[2048 . ""] := "DIRECTINPUT_HEADER_VERSION"
dinput.constant[8 . ""] := "DISCL_BACKGROUND"
dinput.constant[1 . ""] := "DISCL_EXCLUSIVE"
dinput.constant[4 . ""] := "DISCL_FOREGROUND"
dinput.constant[2 . ""] := "DISCL_NONEXCLUSIVE"
dinput.constant[16 . ""] := "DISCL_NOWINKEY"
dinput.constant[1 . ""] := "DISDD_CONTINUE"
dinput.constant[8 . ""] := "DISFFC_CONTINUE"
dinput.constant[4 . ""] := "DISFFC_PAUSE"
dinput.constant[1 . ""] := "DISFFC_RESET"
dinput.constant[32 . ""] := "DISFFC_SETACTUATORSOFF"
dinput.constant[16 . ""] := "DISFFC_SETACTUATORSON"
dinput.constant[2 . ""] := "DISFFC_STOPALL"
dinput.constant[570425344 . ""] := "DIVIRTUAL_ARCADE_PLATFORM"
dinput.constant[553648128 . ""] := "DIVIRTUAL_ARCADE_SIDE2SIDE"
dinput.constant[671088640 . ""] := "DIVIRTUAL_BROWSER_CONTROL"
dinput.constant[587202560 . ""] := "DIVIRTUAL_CAD_2DCONTROL"
dinput.constant[603979776 . ""] := "DIVIRTUAL_CAD_3DCONTROL"
dinput.constant[620756992 . ""] := "DIVIRTUAL_CAD_FLYBY"
dinput.constant[637534208 . ""] := "DIVIRTUAL_CAD_MODEL"
dinput.constant[33554432 . ""] := "DIVIRTUAL_DRIVING_COMBAT"
dinput.constant[687865856 . ""] := "DIVIRTUAL_DRIVING_MECHA"
dinput.constant[16777216 . ""] := "DIVIRTUAL_DRIVING_RACE"
dinput.constant[50331648 . ""] := "DIVIRTUAL_DRIVING_TANK"
dinput.constant[150994944 . ""] := "DIVIRTUAL_FIGHTING_FPS"
dinput.constant[134217728 . ""] := "DIVIRTUAL_FIGHTING_HAND2HAND"
dinput.constant[167772160 . ""] := "DIVIRTUAL_FIGHTING_THIRDPERSON"
dinput.constant[67108864 . ""] := "DIVIRTUAL_FLYING_CIVILIAN"
dinput.constant[100663296 . ""] := "DIVIRTUAL_FLYING_HELICOPTER"
dinput.constant[83886080 . ""] := "DIVIRTUAL_FLYING_MILITARY"
dinput.constant[654311424 . ""] := "DIVIRTUAL_REMOTE_CONTROL"
dinput.constant[117440512 . ""] := "DIVIRTUAL_SPACESIM"
dinput.constant[251658240 . ""] := "DIVIRTUAL_SPORTS_BASEBALL_BAT"
dinput.constant[285212672 . ""] := "DIVIRTUAL_SPORTS_BASEBALL_FIELD"
dinput.constant[268435456 . ""] := "DIVIRTUAL_SPORTS_BASEBALL_PITCH"
dinput.constant[318767104 . ""] := "DIVIRTUAL_SPORTS_BASKETBALL_DEFENSE"
dinput.constant[301989888 . ""] := "DIVIRTUAL_SPORTS_BASKETBALL_OFFENSE"
dinput.constant[469762048 . ""] := "DIVIRTUAL_SPORTS_BIKING_MOUNTAIN"
dinput.constant[234881024 . ""] := "DIVIRTUAL_SPORTS_FISHING"
dinput.constant[385875968 . ""] := "DIVIRTUAL_SPORTS_FOOTBALL_DEFENSE"
dinput.constant[335544320 . ""] := "DIVIRTUAL_SPORTS_FOOTBALL_FIELD"
dinput.constant[369098752 . ""] := "DIVIRTUAL_SPORTS_FOOTBALL_OFFENSE"
dinput.constant[352321536 . ""] := "DIVIRTUAL_SPORTS_FOOTBALL_QBCK"
dinput.constant[402653184 . ""] := "DIVIRTUAL_SPORTS_GOLF"
dinput.constant[436207616 . ""] := "DIVIRTUAL_SPORTS_HOCKEY_DEFENSE"
dinput.constant[452984832 . ""] := "DIVIRTUAL_SPORTS_HOCKEY_GOALIE"
dinput.constant[419430400 . ""] := "DIVIRTUAL_SPORTS_HOCKEY_OFFENSE"
dinput.constant[218103808 . ""] := "DIVIRTUAL_SPORTS_HUNTING"
dinput.constant[536870912 . ""] := "DIVIRTUAL_SPORTS_RACQUET"
dinput.constant[486539264 . ""] := "DIVIRTUAL_SPORTS_SKIING"
dinput.constant[520093696 . ""] := "DIVIRTUAL_SPORTS_SOCCER_DEFENSE"
dinput.constant[503316480 . ""] := "DIVIRTUAL_SPORTS_SOCCER_OFFENSE"
dinput.constant[184549376 . ""] := "DIVIRTUAL_STRATEGY_ROLEPLAYING"
dinput.constant[201326592 . ""] := "DIVIRTUAL_STRATEGY_TURN"
dinput.constant[2197816330 . ""] := "DIVOICE_ALL"
dinput.constant[2197816321 . ""] := "DIVOICE_CHANNEL1"
dinput.constant[2197816322 . ""] := "DIVOICE_CHANNEL2"
dinput.constant[2197816323 . ""] := "DIVOICE_CHANNEL3"
dinput.constant[2197816324 . ""] := "DIVOICE_CHANNEL4"
dinput.constant[2197816325 . ""] := "DIVOICE_CHANNEL5"
dinput.constant[2197816326 . ""] := "DIVOICE_CHANNEL6"
dinput.constant[2197816327 . ""] := "DIVOICE_CHANNEL7"
dinput.constant[2197816328 . ""] := "DIVOICE_CHANNEL8"
dinput.constant[2197816332 . ""] := "DIVOICE_PLAYBACKMUTE"
dinput.constant[2197816331 . ""] := "DIVOICE_RECORDMUTE"
dinput.constant[2197816329 . ""] := "DIVOICE_TEAM"
dinput.constant[2197816333 . ""] := "DIVOICE_TRANSMIT"
dinput.constant[2197816336 . ""] := "DIVOICE_VOICECOMMAND"
dinput.constant[0x8000000A . ""] := "E_PENDING"
dinput.constant[0x10000000 . ""] := "JOY_HWS_AUTOLOAD"
dinput.constant[0x00000001 . ""] := "JOY_HWS_GAMEPORTBUSBUSY"
dinput.constant[0x08000000 . ""] := "JOY_HWS_ISANALOGPORTDRIVER"
dinput.constant[0x80000000 . ""] := "JOY_HWS_ISGAMEPORTBUS"
dinput.constant[0x04000000 . ""] := "JOY_HWS_ISGAMEPORTDRIVER"
dinput.constant[0x02000000 . ""] := "JOY_HWS_ISHEADTRACKER"
dinput.constant[0x20000000 . ""] := "JOY_HWS_NODEVNODE"
dinput.constant[7 . ""] := "JOY_OEMPOLL_PASSDRIVERDATA"
dinput.constant[0x10000000 . ""] := "JOY_PASSDRIVERDATA"
dinput.constant[0x00000008 . ""] := "JOY_US_VOLATILE"
dinput.constant[8 . ""] := "MAXCPOINTSNUM"


Global DI8DEVCLASS_DEVICE := 1
Global DI8DEVCLASS_GAMECTRL := 4
Global DI8DEVCLASS_KEYBOARD := 3
Global DI8DEVCLASS_POINTER := 2
Global DI8DEVTYPE1STPERSON_SHOOTER := 4
Global DI8DEVTYPE1STPERSON_SIXDOF := 3
Global DI8DEVTYPE1STPERSON_UNKNOWN := 2
Global DI8DEVTYPE_1STPERSON := 24
Global DI8DEVTYPE_DEVICE := 17
Global DI8DEVTYPE_DEVICECTRL := 25
Global DI8DEVTYPE_DRIVING := 22
Global DI8DEVTYPE_FLIGHT := 23
Global DI8DEVTYPE_GAMEPAD := 21
Global DI8DEVTYPE_JOYSTICK := 20
Global DI8DEVTYPE_KEYBOARD := 19
Global DI8DEVTYPE_LIMITEDGAMESUBTYPE := 1
Global DI8DEVTYPE_MOUSE := 18
Global DI8DEVTYPE_REMOTE := 27
Global DI8DEVTYPE_SCREENPOINTER := 26
Global DI8DEVTYPE_SUPPLEMENTAL := 28
Global DI8DEVTYPEDEVICECTRL_COMMSSELECTION := 3
Global DI8DEVTYPEDEVICECTRL_COMMSSELECTION_HARDWIRED := 4
Global DI8DEVTYPEDEVICECTRL_UNKNOWN := 2
Global DI8DEVTYPEDRIVING_COMBINEDPEDALS := 2
Global DI8DEVTYPEDRIVING_DUALPEDALS := 3
Global DI8DEVTYPEDRIVING_HANDHELD := 5
Global DI8DEVTYPEDRIVING_THREEPEDALS := 4
Global DI8DEVTYPEFLIGHT_RC := 4
Global DI8DEVTYPEFLIGHT_STICK := 2
Global DI8DEVTYPEFLIGHT_YOKE := 3
Global DI8DEVTYPEGAMEPAD_STANDARD := 2
Global DI8DEVTYPEGAMEPAD_TILT := 3
Global DI8DEVTYPEJOYSTICK_STANDARD := 2
Global DI8DEVTYPEKEYBOARD_J3100 := 12
Global DI8DEVTYPEKEYBOARD_JAPAN106 := 10
Global DI8DEVTYPEKEYBOARD_JAPANAX := 11
Global DI8DEVTYPEKEYBOARD_NEC98 := 7
Global DI8DEVTYPEKEYBOARD_NEC98106 := 9
Global DI8DEVTYPEKEYBOARD_NEC98LAPTOP := 8
Global DI8DEVTYPEKEYBOARD_NOKIA1050 := 5
Global DI8DEVTYPEKEYBOARD_NOKIA9140 := 6
Global DI8DEVTYPEKEYBOARD_OLIVETTI := 2
Global DI8DEVTYPEKEYBOARD_PCAT := 3
Global DI8DEVTYPEKEYBOARD_PCENH := 4
Global DI8DEVTYPEKEYBOARD_PCXT := 1
Global DI8DEVTYPEMOUSE_ABSOLUTE := 6
Global DI8DEVTYPEMOUSE_FINGERSTICK := 3
Global DI8DEVTYPEMOUSE_TOUCHPAD := 4
Global DI8DEVTYPEMOUSE_TRACKBALL := 5
Global DI8DEVTYPEMOUSE_TRADITIONAL := 2
Global DI8DEVTYPEMOUSE_UNKNOWN := 1
Global DI8DEVTYPEREMOTE_UNKNOWN := 2
Global DI8DEVTYPESCREENPTR_LIGHTGUN := 3
Global DI8DEVTYPESCREENPTR_LIGHTPEN := 4
Global DI8DEVTYPESCREENPTR_TOUCH := 5
Global DI8DEVTYPESCREENPTR_UNKNOWN := 2
Global DI8DEVTYPESUPPLEMENTAL_2NDHANDCONTROLLER := 3
Global DI8DEVTYPESUPPLEMENTAL_COMBINEDPEDALS := 10
Global DI8DEVTYPESUPPLEMENTAL_DUALPEDALS := 11
Global DI8DEVTYPESUPPLEMENTAL_HANDTRACKER := 5
Global DI8DEVTYPESUPPLEMENTAL_HEADTRACKER := 4
Global DI8DEVTYPESUPPLEMENTAL_RUDDERPEDALS := 13
Global DI8DEVTYPESUPPLEMENTAL_SHIFTER := 7
Global DI8DEVTYPESUPPLEMENTAL_SHIFTSTICKGATE := 6
Global DI8DEVTYPESUPPLEMENTAL_SPLITTHROTTLE := 9
Global DI8DEVTYPESUPPLEMENTAL_THREEPEDALS := 12
Global DI8DEVTYPESUPPLEMENTAL_THROTTLE := 8
Global DI8DEVTYPESUPPLEMENTAL_UNKNOWN := 2
Global DI_DEGREES := 100
Global DI_DOWNLOADSKIPPED := 0x00000003
Global DI_EFFECTRESTARTED := 0x00000004
Global DI_FFNOMINALMAX := 10000
Global DI_POLLEDDEVICE := 0x00000002
Global DI_SECONDS := 1000000
Global DI_SETTINGSNOTSAVED := 0x0000000B
Global DI_TRUNCATED := 0x00000008
Global DI_TRUNCATEDANDRESTARTED := 0x0000000C
Global DI_WRITEPROTECT := 0x00000013
Global DIA_APPFIXED := 16
Global DIA_APPMAPPED := 2
Global DIA_APPNOMAP := 4
Global DIA_FORCEFEEDBACK := 1
Global DIA_NORANGE := 8
Global DIAFTS_NEWDEVICEHIGH := 4294967295
Global DIAFTS_NEWDEVICELOW := 4294967295
Global DIAH_APPREQUESTED := 2
Global DIAH_DEFAULT := 32
Global DIAH_ERROR := 2147483648
Global DIAH_HWAPP := 4
Global DIAH_HWDEFAULT := 8
Global DIAH_USERCONFIG := 1
Global DIAXIS_ANY_1 := 4278206977
Global DIAXIS_ANY_2 := 4278206978
Global DIAXIS_ANY_3 := 4278206979
Global DIAXIS_ANY_4 := 4278206980
Global DIAXIS_ANY_A_1 := 4278436353
Global DIAXIS_ANY_A_2 := 4278436354
Global DIAXIS_ANY_B_1 := 4278469121
Global DIAXIS_ANY_B_2 := 4278469122
Global DIAXIS_ANY_C_1 := 4278501889
Global DIAXIS_ANY_C_2 := 4278501890
Global DIAXIS_ANY_R_1 := 4278338049
Global DIAXIS_ANY_R_2 := 4278338050
Global DIAXIS_ANY_S_1 := 4278534657
Global DIAXIS_ANY_S_2 := 4278534658
Global DIAXIS_ANY_U_1 := 4278370817
Global DIAXIS_ANY_U_2 := 4278370818
Global DIAXIS_ANY_V_1 := 4278403585
Global DIAXIS_ANY_V_2 := 4278403586
Global DIAXIS_ANY_X_1 := 4278239745
Global DIAXIS_ANY_X_2 := 4278239746
Global DIAXIS_ANY_Y_1 := 4278272513
Global DIAXIS_ANY_Y_2 := 4278272514
Global DIAXIS_ANY_Z_1 := 4278305281
Global DIAXIS_ANY_Z_2 := 4278305282
Global DICD_EDIT := 1
Global DIDAL_BOTTOMALIGNED := 8
Global DIDAL_LEFTALIGNED := 1
Global DIDAL_RIGHTALIGNED := 2
Global DIDAL_TOPALIGNED := 4
Global DIDBAM_HWDEFAULTS := 4
Global DIDBAM_INITIALIZE := 2
Global DIDBAM_PRESERVE := 1
Global DIDC_ALIAS := 65536
Global DIDC_ATTACHED := 1
Global DIDC_DEADBAND := 16384
Global DIDC_EMULATED := 4
Global DIDC_FFATTACK := 512
Global DIDC_FFFADE := 1024
Global DIDC_FORCEFEEDBACK := 256
Global DIDC_HIDDEN := 262144
Global DIDC_PHANTOM := 131072
Global DIDC_POLLEDDATAFORMAT := 8
Global DIDC_POLLEDDEVICE := 2
Global DIDC_POSNEGCOEFFICIENTS := 4096
Global DIDC_POSNEGSATURATION := 8192
Global DIDC_SATURATION := 2048
Global DIDC_STARTDELAY := 32768
Global DIDEVTYPE_DEVICE := 1
Global DIDEVTYPE_HID := 65536
Global DIDEVTYPE_JOYSTICK := 4
Global DIDEVTYPE_KEYBOARD := 3
Global DIDEVTYPE_MOUSE := 2
Global DIDEVTYPEJOYSTICK_FLIGHTSTICK := 3
Global DIDEVTYPEJOYSTICK_GAMEPAD := 4
Global DIDEVTYPEJOYSTICK_HEADTRACKER := 7
Global DIDEVTYPEJOYSTICK_RUDDER := 5
Global DIDEVTYPEJOYSTICK_TRADITIONAL := 2
Global DIDEVTYPEJOYSTICK_UNKNOWN := 1
Global DIDEVTYPEJOYSTICK_WHEEL := 6
Global DIDEVTYPEKEYBOARD_J3100 := 12
Global DIDEVTYPEKEYBOARD_JAPAN106 := 10
Global DIDEVTYPEKEYBOARD_JAPANAX := 11
Global DIDEVTYPEKEYBOARD_NEC98 := 7
Global DIDEVTYPEKEYBOARD_NEC98106 := 9
Global DIDEVTYPEKEYBOARD_NEC98LAPTOP := 8
Global DIDEVTYPEKEYBOARD_NOKIA1050 := 5
Global DIDEVTYPEKEYBOARD_NOKIA9140 := 6
Global DIDEVTYPEKEYBOARD_OLIVETTI := 2
Global DIDEVTYPEKEYBOARD_PCAT := 3
Global DIDEVTYPEKEYBOARD_PCENH := 4
Global DIDEVTYPEKEYBOARD_PCXT := 1
Global DIDEVTYPEMOUSE_FINGERSTICK := 3
Global DIDEVTYPEMOUSE_TOUCHPAD := 4
Global DIDEVTYPEMOUSE_TRACKBALL := 5
Global DIDEVTYPEMOUSE_TRADITIONAL := 2
Global DIDEVTYPEMOUSE_UNKNOWN := 1
Global DIDF_ABSAXIS := 1
Global DIDF_RELAXIS := 2
Global DIDFT_ABSAXIS := 2
Global DIDFT_ALIAS := 134217728
Global DIDFT_ANYINSTANCE := 16776960
Global DIDFT_AXIS := 3
Global DIDFT_BUTTON := 12
Global DIDFT_COLLECTION := 64
Global DIDFT_FFACTUATOR := 16777216
Global DIDFT_FFEFFECTTRIGGER := 33554432
Global DIDFT_NOCOLLECTION := 16776960
Global DIDFT_NODATA := 128
Global DIDFT_OPTIONAL := 2147483648
Global DIDFT_OUTPUT := 268435456
Global DIDFT_POV := 16
Global DIDFT_PSHBUTTON := 4
Global DIDFT_RELAXIS := 1
Global DIDFT_TGLBUTTON := 8
Global DIDFT_VENDORDEFINED := 67108864
Global DIDIFT_CONFIGURATION := 1
Global DIDIFT_OVERLAY := 2
Global DIDOI_ASPECTACCEL := 768
Global DIDOI_ASPECTFORCE := 1024
Global DIDOI_ASPECTMASK := 3840
Global DIDOI_ASPECTPOSITION := 256
Global DIDOI_ASPECTVELOCITY := 512
Global DIDOI_FFACTUATOR := 1
Global DIDOI_FFEFFECTTRIGGER := 2
Global DIDOI_GUIDISUSAGE := 65536
Global DIDOI_POLLED := 32768
Global DIDSAM_FORCESAVE := 2
Global DIDSAM_NOUSER := 1
Global DIEB_NOTRIGGER := 4294967295
Global DIEDBS_MAPPEDPRI1 := 1
Global DIEDBS_MAPPEDPRI2 := 2
Global DIEDBS_NEWDEVICE := 32
Global DIEDBS_RECENTDEVICE := 16
Global DIEDBSFL_AVAILABLEDEVICES := 4096
Global DIEDBSFL_MULTIMICEKEYBOARDS := 8192
Global DIEDBSFL_NONGAMINGDEVICES := 16384
Global DIEDBSFL_THISUSER := 16
Global DIEDBSFL_VALID := 28944
Global DIEDFL_ATTACHEDONLY := 1
Global DIEDFL_FORCEFEEDBACK := 256
Global DIEDFL_INCLUDEALIASES := 65536
Global DIEDFL_INCLUDEHIDDEN := 262144
Global DIEDFL_INCLUDEPHANTOMS := 131072
Global DIEFF_CARTESIAN := 16
Global DIEFF_OBJECTIDS := 1
Global DIEFF_OBJECTOFFSETS := 2
Global DIEFF_POLAR := 32
Global DIEFF_SPHERICAL := 64
Global DIEFT_CONDITION := 4
Global DIEFT_CONSTANTFORCE := 1
Global DIEFT_CUSTOMFORCE := 5
Global DIEFT_DEADBAND := 16384
Global DIEFT_FFATTACK := 512
Global DIEFT_FFFADE := 1024
Global DIEFT_HARDWARE := 255
Global DIEFT_PERIODIC := 3
Global DIEFT_POSNEGCOEFFICIENTS := 4096
Global DIEFT_POSNEGSATURATION := 8192
Global DIEFT_RAMPFORCE := 2
Global DIEFT_SATURATION := 2048
Global DIEFT_STARTDELAY := 32768
Global DIEGES_EMULATED := 2
Global DIEGES_PLAYING := 1
Global DIENUM_CONTINUE := 1
Global DIEP_ALLPARAMS := 511
Global DIEP_ALLPARAMS_DX5 := 511
Global DIEP_AXES := 32
Global DIEP_DIRECTION := 64
Global DIEP_DURATION := 1
Global DIEP_ENVELOPE := 128
Global DIEP_GAIN := 4
Global DIEP_NODOWNLOAD := 2147483648
Global DIEP_NORESTART := 1073741824
Global DIEP_SAMPLEPERIOD := 2
Global DIEP_START := 536870912
Global DIEP_STARTDELAY := 512
Global DIEP_TRIGGERBUTTON := 8
Global DIEP_TRIGGERREPEATINTERVAL := 16
Global DIEP_TYPESPECIFICPARAMS := 256
Global DIERR_DEVICEFULL := 0x80040201
Global DIERR_EFFECTPLAYING := 0x80040208
Global DIERR_HASEFFECTS := 0x80040204
Global DIERR_INCOMPLETEEFFECT := 0x80040206
Global DIERR_INSUFFICIENTPRIVS := 0x80040200
Global DIERR_MAPFILEFAIL := 0x8004020B
Global DIERR_MOREDATA := 0x80040202
Global DIERR_NOTBUFFERED := 0x80040207
Global DIERR_NOTDOWNLOADED := 0x80040203
Global DIERR_NOTEXCLUSIVEACQUIRED := 0x80040205
Global DIERR_REPORTFULL := 0x8004020A
Global DIERR_UNPLUGGED := 0x80040209
Global DIES_NODOWNLOAD := 2147483648
Global DIES_SOLO := 1
Global DIFEF_INCLUDENONSTANDARD := 1
Global DIFEF_MODIFYIFNEEDED := 16
Global DIGDD_PEEK := 1
Global DIGFFS_ACTUATORSOFF := 32
Global DIGFFS_ACTUATORSON := 16
Global DIGFFS_DEVICELOST := 2147483648
Global DIGFFS_EMPTY := 1
Global DIGFFS_PAUSED := 4
Global DIGFFS_POWEROFF := 128
Global DIGFFS_POWERON := 64
Global DIGFFS_SAFETYSWITCHOFF := 512
Global DIGFFS_SAFETYSWITCHON := 256
Global DIGFFS_STOPPED := 2
Global DIGFFS_USERFFSWITCHOFF := 2048
Global DIGFFS_USERFFSWITCHON := 1024
Global DIK_0 := 11
Global DIK_1 := 2
Global DIK_2 := 3
Global DIK_3 := 4
Global DIK_4 := 5
Global DIK_5 := 6
Global DIK_6 := 7
Global DIK_7 := 8
Global DIK_8 := 9
Global DIK_9 := 10
Global DIK_A := 30
Global DIK_APOSTROPHE := 40
Global DIK_B := 48
Global DIK_BACKSLASH := 43
Global DIK_C := 46
Global DIK_CAPITAL := 58
Global DIK_COMMA := 51
Global DIK_D := 32
Global DIK_E := 18
Global DIK_EQUALS := 13
Global DIK_ESCAPE := 1
Global DIK_F := 33
Global DIK_F1 := 59
Global DIK_F10 := 68
Global DIK_F11 := 87
Global DIK_F12 := 88
Global DIK_F2 := 60
Global DIK_F3 := 61
Global DIK_F4 := 62
Global DIK_F5 := 63
Global DIK_F6 := 64
Global DIK_F7 := 65
Global DIK_F8 := 66
Global DIK_F9 := 67
Global DIK_G := 34
Global DIK_H := 35
Global DIK_I := 23
Global DIK_J := 36
Global DIK_K := 37
Global DIK_L := 38
Global DIK_LBRACKET := 26
Global DIK_LCONTROL := 29
Global DIK_LSHIFT := 42
Global DIK_M := 50
Global DIK_N := 49
Global DIK_NUMLOCK := 69
Global DIK_NUMPAD0 := 82
Global DIK_NUMPAD1 := 79
Global DIK_NUMPAD2 := 80
Global DIK_NUMPAD3 := 81
Global DIK_NUMPAD4 := 75
Global DIK_NUMPAD5 := 76
Global DIK_NUMPAD6 := 77
Global DIK_NUMPAD7 := 71
Global DIK_NUMPAD8 := 72
Global DIK_NUMPAD9 := 73
Global DIK_O := 24
Global DIK_P := 25
Global DIK_Q := 16
Global DIK_R := 19
Global DIK_RBRACKET := 27
Global DIK_RCONTROL := 157
Global DIK_RSHIFT := 54
Global DIK_S := 31
Global DIK_SEMICOLON := 39
Global DIK_SPACE := 57
Global DIK_SYSRQ := 183
Global DIK_T := 20
Global DIK_TAB := 15
Global DIK_U := 22
Global DIK_V := 47
Global DIK_W := 17
Global DIK_X := 45
Global DIK_Y := 21
Global DIK_Z := 44
Global DIKEYBOARD_0 := 2164261899
Global DIKEYBOARD_1 := 2164261890
Global DIKEYBOARD_2 := 2164261891
Global DIKEYBOARD_3 := 2164261892
Global DIKEYBOARD_4 := 2164261893
Global DIKEYBOARD_5 := 2164261894
Global DIKEYBOARD_6 := 2164261895
Global DIKEYBOARD_7 := 2164261896
Global DIKEYBOARD_8 := 2164261897
Global DIKEYBOARD_9 := 2164261898
Global DIKEYBOARD_A := 2164261918
Global DIKEYBOARD_APOSTROPHE := 2164261928
Global DIKEYBOARD_B := 2164261936
Global DIKEYBOARD_BACKSLASH := 2164261931
Global DIKEYBOARD_C := 2164261934
Global DIKEYBOARD_CAPITAL := 2164261946
Global DIKEYBOARD_COMMA := 2164261939
Global DIKEYBOARD_D := 2164261920
Global DIKEYBOARD_E := 2164261906
Global DIKEYBOARD_EQUALS := 2164261901
Global DIKEYBOARD_ESCAPE := 2164261889
Global DIKEYBOARD_F := 2164261921
Global DIKEYBOARD_F1 := 2164261947
Global DIKEYBOARD_F10 := 2164261956
Global DIKEYBOARD_F11 := 2164261975
Global DIKEYBOARD_F12 := 2164261976
Global DIKEYBOARD_F2 := 2164261948
Global DIKEYBOARD_F3 := 2164261949
Global DIKEYBOARD_F4 := 2164261950
Global DIKEYBOARD_F5 := 2164261951
Global DIKEYBOARD_F6 := 2164261952
Global DIKEYBOARD_F7 := 2164261953
Global DIKEYBOARD_F8 := 2164261954
Global DIKEYBOARD_F9 := 2164261955
Global DIKEYBOARD_G := 2164261922
Global DIKEYBOARD_H := 2164261923
Global DIKEYBOARD_I := 2164261911
Global DIKEYBOARD_J := 2164261924
Global DIKEYBOARD_K := 2164261925
Global DIKEYBOARD_L := 2164261926
Global DIKEYBOARD_LBRACKET := 2164261914
Global DIKEYBOARD_LCONTROL := 2164261917
Global DIKEYBOARD_LSHIFT := 2164261930
Global DIKEYBOARD_M := 2164261938
Global DIKEYBOARD_N := 2164261937
Global DIKEYBOARD_NUMLOCK := 2164261957
Global DIKEYBOARD_NUMPAD0 := 2164261970
Global DIKEYBOARD_NUMPAD1 := 2164261967
Global DIKEYBOARD_NUMPAD2 := 2164261968
Global DIKEYBOARD_NUMPAD3 := 2164261969
Global DIKEYBOARD_NUMPAD4 := 2164261963
Global DIKEYBOARD_NUMPAD5 := 2164261964
Global DIKEYBOARD_NUMPAD6 := 2164261965
Global DIKEYBOARD_NUMPAD7 := 2164261959
Global DIKEYBOARD_NUMPAD8 := 2164261960
Global DIKEYBOARD_NUMPAD9 := 2164261961
Global DIKEYBOARD_O := 2164261912
Global DIKEYBOARD_P := 2164261913
Global DIKEYBOARD_Q := 2164261904
Global DIKEYBOARD_R := 2164261907
Global DIKEYBOARD_RBRACKET := 2164261915
Global DIKEYBOARD_RCONTROL := 2164262045
Global DIKEYBOARD_RSHIFT := 2164261942
Global DIKEYBOARD_S := 2164261919
Global DIKEYBOARD_SEMICOLON := 2164261927
Global DIKEYBOARD_SPACE := 2164261945
Global DIKEYBOARD_SYSRQ := 2164262071
Global DIKEYBOARD_T := 2164261908
Global DIKEYBOARD_TAB := 2164261903
Global DIKEYBOARD_U := 2164261910
Global DIKEYBOARD_V := 2164261935
Global DIKEYBOARD_W := 2164261905
Global DIKEYBOARD_X := 2164261933
Global DIKEYBOARD_Y := 2164261909
Global DIKEYBOARD_Z := 2164261932
Global DIPH_BYID := 2
Global DIPH_BYOFFSET := 1
Global DIPH_BYUSAGE := 3
Global DIPOV_ANY_1 := 4278208001
Global DIPOV_ANY_2 := 4278208002
Global DIPOV_ANY_3 := 4278208003
Global DIPOV_ANY_4 := 4278208004
Global DIPROPAUTOCENTER_ON := 1
Global DIPROPAXISMODE_REL := 1
Global DIPROPCALIBRATIONMODE_RAW := 1
Global DIRECTINPUT_HEADER_VERSION := 2048
Global DISCL_BACKGROUND := 8
Global DISCL_EXCLUSIVE := 1
Global DISCL_FOREGROUND := 4
Global DISCL_NONEXCLUSIVE := 2
Global DISCL_NOWINKEY := 16
Global DISDD_CONTINUE := 1
Global DISFFC_CONTINUE := 8
Global DISFFC_PAUSE := 4
Global DISFFC_RESET := 1
Global DISFFC_SETACTUATORSOFF := 32
Global DISFFC_SETACTUATORSON := 16
Global DISFFC_STOPALL := 2
Global DIVIRTUAL_ARCADE_PLATFORM := 570425344
Global DIVIRTUAL_ARCADE_SIDE2SIDE := 553648128
Global DIVIRTUAL_BROWSER_CONTROL := 671088640
Global DIVIRTUAL_CAD_2DCONTROL := 587202560
Global DIVIRTUAL_CAD_3DCONTROL := 603979776
Global DIVIRTUAL_CAD_FLYBY := 620756992
Global DIVIRTUAL_CAD_MODEL := 637534208
Global DIVIRTUAL_DRIVING_COMBAT := 33554432
Global DIVIRTUAL_DRIVING_MECHA := 687865856
Global DIVIRTUAL_DRIVING_RACE := 16777216
Global DIVIRTUAL_DRIVING_TANK := 50331648
Global DIVIRTUAL_FIGHTING_FPS := 150994944
Global DIVIRTUAL_FIGHTING_HAND2HAND := 134217728
Global DIVIRTUAL_FIGHTING_THIRDPERSON := 167772160
Global DIVIRTUAL_FLYING_CIVILIAN := 67108864
Global DIVIRTUAL_FLYING_HELICOPTER := 100663296
Global DIVIRTUAL_FLYING_MILITARY := 83886080
Global DIVIRTUAL_REMOTE_CONTROL := 654311424
Global DIVIRTUAL_SPACESIM := 117440512
Global DIVIRTUAL_SPORTS_BASEBALL_BAT := 251658240
Global DIVIRTUAL_SPORTS_BASEBALL_FIELD := 285212672
Global DIVIRTUAL_SPORTS_BASEBALL_PITCH := 268435456
Global DIVIRTUAL_SPORTS_BASKETBALL_DEFENSE := 318767104
Global DIVIRTUAL_SPORTS_BASKETBALL_OFFENSE := 301989888
Global DIVIRTUAL_SPORTS_BIKING_MOUNTAIN := 469762048
Global DIVIRTUAL_SPORTS_FISHING := 234881024
Global DIVIRTUAL_SPORTS_FOOTBALL_DEFENSE := 385875968
Global DIVIRTUAL_SPORTS_FOOTBALL_FIELD := 335544320
Global DIVIRTUAL_SPORTS_FOOTBALL_OFFENSE := 369098752
Global DIVIRTUAL_SPORTS_FOOTBALL_QBCK := 352321536
Global DIVIRTUAL_SPORTS_GOLF := 402653184
Global DIVIRTUAL_SPORTS_HOCKEY_DEFENSE := 436207616
Global DIVIRTUAL_SPORTS_HOCKEY_GOALIE := 452984832
Global DIVIRTUAL_SPORTS_HOCKEY_OFFENSE := 419430400
Global DIVIRTUAL_SPORTS_HUNTING := 218103808
Global DIVIRTUAL_SPORTS_RACQUET := 536870912
Global DIVIRTUAL_SPORTS_SKIING := 486539264
Global DIVIRTUAL_SPORTS_SOCCER_DEFENSE := 520093696
Global DIVIRTUAL_SPORTS_SOCCER_OFFENSE := 503316480
Global DIVIRTUAL_STRATEGY_ROLEPLAYING := 184549376
Global DIVIRTUAL_STRATEGY_TURN := 201326592
Global DIVOICE_ALL := 2197816330
Global DIVOICE_CHANNEL1 := 2197816321
Global DIVOICE_CHANNEL2 := 2197816322
Global DIVOICE_CHANNEL3 := 2197816323
Global DIVOICE_CHANNEL4 := 2197816324
Global DIVOICE_CHANNEL5 := 2197816325
Global DIVOICE_CHANNEL6 := 2197816326
Global DIVOICE_CHANNEL7 := 2197816327
Global DIVOICE_CHANNEL8 := 2197816328
Global DIVOICE_PLAYBACKMUTE := 2197816332
Global DIVOICE_RECORDMUTE := 2197816331
Global DIVOICE_TEAM := 2197816329
Global DIVOICE_TRANSMIT := 2197816333
Global DIVOICE_VOICECOMMAND := 2197816336
Global E_PENDING := 0x8000000A
Global JOY_HWS_AUTOLOAD := 0x10000000
Global JOY_HWS_GAMEPORTBUSBUSY := 0x00000001
Global JOY_HWS_ISANALOGPORTDRIVER := 0x08000000
Global JOY_HWS_ISGAMEPORTBUS := 0x80000000
Global JOY_HWS_ISGAMEPORTDRIVER := 0x04000000
Global JOY_HWS_ISHEADTRACKER := 0x02000000
Global JOY_HWS_NODEVNODE := 0x20000000
Global JOY_OEMPOLL_PASSDRIVERDATA := 7
Global JOY_PASSDRIVERDATA := 0x10000000
Global JOY_US_VOLATILE := 0x00000008
Global MAXCPOINTSNUM := 8

dinput.result := {}

