ReplaceHtmlEncodedChars(fnText)
{
	; MsgBox fnText:`n%fnText%
	StringReplace, fnText, fnText, &#32;     ,%A_Space%, All
	StringReplace, fnText, fnText, &#33;     , ! , All
	StringReplace, fnText, fnText, &#34;     , `", All
	StringReplace, fnText, fnText, &quot;    , `", All
	StringReplace, fnText, fnText, &#35;     , # , All
	StringReplace, fnText, fnText, &#36;     , $ , All
	StringReplace, fnText, fnText, &#37;     , `%, All
	StringReplace, fnText, fnText, &#38;     , & , All
	StringReplace, fnText, fnText, &amp;     , & , All
	StringReplace, fnText, fnText, &#39;     , ' , All
	StringReplace, fnText, fnText, &#40;     , ( , All
	StringReplace, fnText, fnText, &#41;     , ) , All
	StringReplace, fnText, fnText, &#42;     , * , All
	StringReplace, fnText, fnText, &#43;     , + , All
	StringReplace, fnText, fnText, &#44;     , `,, All
	StringReplace, fnText, fnText, &#45;     , - , All
	StringReplace, fnText, fnText, &#46;     , . , All
	StringReplace, fnText, fnText, &#47;     , / , All
	StringReplace, fnText, fnText, &#48;     , 0 , All
	StringReplace, fnText, fnText, &#49;     , 1 , All
	StringReplace, fnText, fnText, &#50;     , 2 , All
	StringReplace, fnText, fnText, &#51;     , 3 , All
	StringReplace, fnText, fnText, &#52;     , 4 , All
	StringReplace, fnText, fnText, &#53;     , 5 , All
	StringReplace, fnText, fnText, &#54;     , 6 , All
	StringReplace, fnText, fnText, &#55;     , 7 , All
	StringReplace, fnText, fnText, &#56;     , 8 , All
	StringReplace, fnText, fnText, &#57;     , 9 , All
	StringReplace, fnText, fnText, &#58;     , : , All
	StringReplace, fnText, fnText, &#59;     , `;, All
	StringReplace, fnText, fnText, &#60;     , < , All
	StringReplace, fnText, fnText, &lt;      , < , All
	StringReplace, fnText, fnText, &#61;     , = , All
	StringReplace, fnText, fnText, &#62;     , > , All
	StringReplace, fnText, fnText, &gt;      , > , All
	StringReplace, fnText, fnText, &#63;     , ? , All
	StringReplace, fnText, fnText, &#64;     , @ , All
	StringReplace, fnText, fnText, &#65;     , A , All
	StringReplace, fnText, fnText, &#66;     , B , All
	StringReplace, fnText, fnText, &#67;     , C , All
	StringReplace, fnText, fnText, &#68;     , D , All
	StringReplace, fnText, fnText, &#69;     , E , All
	StringReplace, fnText, fnText, &#70;     , F , All
	StringReplace, fnText, fnText, &#71;     , G , All
	StringReplace, fnText, fnText, &#72;     , H , All
	StringReplace, fnText, fnText, &#73;     , I , All
	StringReplace, fnText, fnText, &#74;     , J , All
	StringReplace, fnText, fnText, &#75;     , K , All
	StringReplace, fnText, fnText, &#76;     , L , All
	StringReplace, fnText, fnText, &#77;     , M , All
	StringReplace, fnText, fnText, &#78;     , N , All
	StringReplace, fnText, fnText, &#79;     , O , All
	StringReplace, fnText, fnText, &#80;     , P , All
	StringReplace, fnText, fnText, &#81;     , Q , All
	StringReplace, fnText, fnText, &#82;     , R , All
	StringReplace, fnText, fnText, &#83;     , S , All
	StringReplace, fnText, fnText, &#84;     , T , All
	StringReplace, fnText, fnText, &#85;     , U , All
	StringReplace, fnText, fnText, &#86;     , V , All
	StringReplace, fnText, fnText, &#87;     , W , All
	StringReplace, fnText, fnText, &#88;     , X , All
	StringReplace, fnText, fnText, &#89;     , Y , All
	StringReplace, fnText, fnText, &#90;     , Z , All
	StringReplace, fnText, fnText, &#91;     , [ , All
	StringReplace, fnText, fnText, &#92;     , \ , All
	StringReplace, fnText, fnText, &#93;     , ] , All
	StringReplace, fnText, fnText, &#94;     , ^ , All
	StringReplace, fnText, fnText, &#95;     , _ , All
	StringReplace, fnText, fnText, &#96;     , ``, All
	StringReplace, fnText, fnText, &#97;     , a , All
	StringReplace, fnText, fnText, &#98;     , b , All
	StringReplace, fnText, fnText, &#99;     , c , All
	StringReplace, fnText, fnText, &#100;    , d , All
	StringReplace, fnText, fnText, &#101;    , e , All
	StringReplace, fnText, fnText, &#102;    , f , All
	StringReplace, fnText, fnText, &#103;    , g , All
	StringReplace, fnText, fnText, &#104;    , h , All
	StringReplace, fnText, fnText, &#105;    , i , All
	StringReplace, fnText, fnText, &#106;    , j , All
	StringReplace, fnText, fnText, &#107;    , k , All
	StringReplace, fnText, fnText, &#108;    , l , All
	StringReplace, fnText, fnText, &#109;    , m , All
	StringReplace, fnText, fnText, &#110;    , n , All
	StringReplace, fnText, fnText, &#111;    , o , All
	StringReplace, fnText, fnText, &#112;    , p , All
	StringReplace, fnText, fnText, &#113;    , q , All
	StringReplace, fnText, fnText, &#114;    , r , All
	StringReplace, fnText, fnText, &#115;    , s , All
	StringReplace, fnText, fnText, &#116;    , t , All
	StringReplace, fnText, fnText, &#117;    , u , All
	StringReplace, fnText, fnText, &#118;    , v , All
	StringReplace, fnText, fnText, &#119;    , w , All
	StringReplace, fnText, fnText, &#120;    , x , All
	StringReplace, fnText, fnText, &#121;    , y , All
	StringReplace, fnText, fnText, &#122;    , z , All
	StringReplace, fnText, fnText, &#123;    , { , All
	StringReplace, fnText, fnText, &#124;    , | , All
	StringReplace, fnText, fnText, &#125;    , } , All
	StringReplace, fnText, fnText, &#126;    , ~ , All
	  
	StringReplace, fnText, fnText, &#160;    ,   , All
	StringReplace, fnText, fnText, &nbsp;    ,   , All
	StringReplace, fnText, fnText, &#161;    , ¡ , All
	StringReplace, fnText, fnText, &iexcl;   , ¡ , All
	StringReplace, fnText, fnText, &#162;    , ¢ , All
	StringReplace, fnText, fnText, &cent;    , ¢ , All
	StringReplace, fnText, fnText, &#163;    , £ , All
	StringReplace, fnText, fnText, &pound;   , £ , All
	StringReplace, fnText, fnText, &#164;    , ¤ , All
	StringReplace, fnText, fnText, &curren;  , ¤ , All
	StringReplace, fnText, fnText, &#165;    , ¥ , All
	StringReplace, fnText, fnText, &yen;     , ¥ , All
	StringReplace, fnText, fnText, &#166;    , ¦ , All
	StringReplace, fnText, fnText, &brvbar;  , ¦ , All
	StringReplace, fnText, fnText, &#167;    , § , All
	StringReplace, fnText, fnText, &sect;    , § , All
	StringReplace, fnText, fnText, &#168;    , ¨ , All
	StringReplace, fnText, fnText, &uml;     , ¨ , All
	StringReplace, fnText, fnText, &#169;    , © , All
	StringReplace, fnText, fnText, &copy;    , © , All
	StringReplace, fnText, fnText, &#170;    , ª , All
	StringReplace, fnText, fnText, &ordf;    , ª , All
	StringReplace, fnText, fnText, &#171;    , « , All
	StringReplace, fnText, fnText, &laquo;   , « , All
	StringReplace, fnText, fnText, &#172;    , ¬ , All
	StringReplace, fnText, fnText, &not;     , ¬ , All
	StringReplace, fnText, fnText, &#173;    ,   , All
	StringReplace, fnText, fnText, &shy;     ,   , All
	StringReplace, fnText, fnText, &#174;    , ® , All
	StringReplace, fnText, fnText, &reg;     , ® , All
	StringReplace, fnText, fnText, &#175;    , ¯ , All
	StringReplace, fnText, fnText, &macr;    , ¯ , All
	StringReplace, fnText, fnText, &#176;    , ° , All
	StringReplace, fnText, fnText, &deg;     , ° , All
	StringReplace, fnText, fnText, &#177;    , ± , All
	StringReplace, fnText, fnText, &plusmn;  , ± , All
	StringReplace, fnText, fnText, &#178;    , ² , All
	StringReplace, fnText, fnText, &sup2;    , ² , All
	StringReplace, fnText, fnText, &#179;    , ³ , All
	StringReplace, fnText, fnText, &sup3;    , ³ , All
	StringReplace, fnText, fnText, &#180;    , ´ , All
	StringReplace, fnText, fnText, &acute;   , ´ , All
	StringReplace, fnText, fnText, &#181;    , µ , All
	StringReplace, fnText, fnText, &micro;   , µ , All
	StringReplace, fnText, fnText, &#182;    , ¶ , All
	StringReplace, fnText, fnText, &para;    , ¶ , All
	StringReplace, fnText, fnText, &#183;    , · , All
	StringReplace, fnText, fnText, &middot;  , · , All
	StringReplace, fnText, fnText, &#184;    , ¸ , All
	StringReplace, fnText, fnText, &cedil;   , ¸ , All
	StringReplace, fnText, fnText, &#185;    , ¹ , All
	StringReplace, fnText, fnText, &sup1;    , ¹ , All
	StringReplace, fnText, fnText, &#186;    , º , All
	StringReplace, fnText, fnText, &ordm;    , º , All
	StringReplace, fnText, fnText, &#187;    , » , All
	StringReplace, fnText, fnText, &raquo;   , » , All
	StringReplace, fnText, fnText, &#188;    , ¼ , All
	StringReplace, fnText, fnText, &frac14;  , ¼ , All
	StringReplace, fnText, fnText, &#189;    , ½ , All
	StringReplace, fnText, fnText, &frac12;  , ½ , All
	StringReplace, fnText, fnText, &#190;    , ¾ , All
	StringReplace, fnText, fnText, &frac34;  , ¾ , All
	StringReplace, fnText, fnText, &#191;    , ¿ , All
	StringReplace, fnText, fnText, &iquest;  , ¿ , All
	StringReplace, fnText, fnText, &#192;    , À , All
	StringReplace, fnText, fnText, &Agrave;  , À , All
	StringReplace, fnText, fnText, &#193;    , Á , All
	StringReplace, fnText, fnText, &Aacute;  , Á , All
	StringReplace, fnText, fnText, &#194;    , Â , All
	StringReplace, fnText, fnText, &Acirc;   , Â , All
	StringReplace, fnText, fnText, &#195;    , Ã , All
	StringReplace, fnText, fnText, &Atilde;  , Ã , All
	StringReplace, fnText, fnText, &#196;    , Ä , All
	StringReplace, fnText, fnText, &Auml;    , Ä , All
	StringReplace, fnText, fnText, &#197;    , Å , All
	StringReplace, fnText, fnText, &Aring;   , Å , All
	StringReplace, fnText, fnText, &#198;    , Æ , All
	StringReplace, fnText, fnText, &AElig;   , Æ , All
	StringReplace, fnText, fnText, &#199;    , Ç , All
	StringReplace, fnText, fnText, &Ccedil;  , Ç , All
	StringReplace, fnText, fnText, &#200;    , È , All
	StringReplace, fnText, fnText, &Egrave;  , È , All
	StringReplace, fnText, fnText, &#201;    , É , All
	StringReplace, fnText, fnText, &Eacute;  , É , All
	StringReplace, fnText, fnText, &#202;    , Ê , All
	StringReplace, fnText, fnText, &Ecirc;   , Ê , All
	StringReplace, fnText, fnText, &#203;    , Ë , All
	StringReplace, fnText, fnText, &Euml;    , Ë , All
	StringReplace, fnText, fnText, &#204;    , Ì , All
	StringReplace, fnText, fnText, &Igrave;  , Ì , All
	StringReplace, fnText, fnText, &#205;    , Í , All
	StringReplace, fnText, fnText, &Iacute;  , Í , All
	StringReplace, fnText, fnText, &#206;    , Î , All
	StringReplace, fnText, fnText, &Icirc;   , Î , All
	StringReplace, fnText, fnText, &#207;    , Ï , All
	StringReplace, fnText, fnText, &Iuml;    , Ï , All
	StringReplace, fnText, fnText, &#208;    , Ð , All
	StringReplace, fnText, fnText, &ETH;     , Ð , All
	StringReplace, fnText, fnText, &#209;    , Ñ , All
	StringReplace, fnText, fnText, &Ntilde;  , Ñ , All
	StringReplace, fnText, fnText, &#210;    , Ò , All
	StringReplace, fnText, fnText, &Ograve;  , Ò , All
	StringReplace, fnText, fnText, &#211;    , Ó , All
	StringReplace, fnText, fnText, &Oacute;  , Ó , All
	StringReplace, fnText, fnText, &#212;    , Ô , All
	StringReplace, fnText, fnText, &Ocirc;   , Ô , All
	StringReplace, fnText, fnText, &#213;    , Õ , All
	StringReplace, fnText, fnText, &Otilde;  , Õ , All
	StringReplace, fnText, fnText, &#214;    , Ö , All
	StringReplace, fnText, fnText, &Ouml;    , Ö , All
	StringReplace, fnText, fnText, &#215;    , × , All
	StringReplace, fnText, fnText, &times;   , × , All
	StringReplace, fnText, fnText, &#216;    , Ø , All
	StringReplace, fnText, fnText, &Oslash;  , Ø , All
	StringReplace, fnText, fnText, &#217;    , Ù , All
	StringReplace, fnText, fnText, &Ugrave;  , Ù , All
	StringReplace, fnText, fnText, &#218;    , Ú , All
	StringReplace, fnText, fnText, &Uacute;  , Ú , All
	StringReplace, fnText, fnText, &#219;    , Û , All
	StringReplace, fnText, fnText, &Ucirc;   , Û , All
	StringReplace, fnText, fnText, &#220;    , Ü , All
	StringReplace, fnText, fnText, &Uuml;    , Ü , All
	StringReplace, fnText, fnText, &#221;    , Ý , All
	StringReplace, fnText, fnText, &Yacute;  , Ý , All
	StringReplace, fnText, fnText, &#222;    , Þ , All
	StringReplace, fnText, fnText, &THORN;   , Þ , All
	StringReplace, fnText, fnText, &#223;    , ß , All
	StringReplace, fnText, fnText, &szlig;   , ß , All
	StringReplace, fnText, fnText, &#224;    , à , All
	StringReplace, fnText, fnText, &agrave;  , à , All
	StringReplace, fnText, fnText, &#225;    , á , All
	StringReplace, fnText, fnText, &aacute;  , á , All
	StringReplace, fnText, fnText, &#226;    , â , All
	StringReplace, fnText, fnText, &acirc;   , â , All
	StringReplace, fnText, fnText, &#227;    , ã , All
	StringReplace, fnText, fnText, &atilde;  , ã , All
	StringReplace, fnText, fnText, &#228;    , ä , All
	StringReplace, fnText, fnText, &auml;    , ä , All
	StringReplace, fnText, fnText, &#229;    , å , All
	StringReplace, fnText, fnText, &aring;   , å , All
	StringReplace, fnText, fnText, &#230;    , æ , All
	StringReplace, fnText, fnText, &aelig;   , æ , All
	StringReplace, fnText, fnText, &#231;    , ç , All
	StringReplace, fnText, fnText, &ccedil;  , ç , All
	StringReplace, fnText, fnText, &#232;    , è , All
	StringReplace, fnText, fnText, &egrave;  , è , All
	StringReplace, fnText, fnText, &#233;    , é , All
	StringReplace, fnText, fnText, &eacute;  , é , All
	StringReplace, fnText, fnText, &#234;    , ê , All
	StringReplace, fnText, fnText, &ecirc;   , ê , All
	StringReplace, fnText, fnText, &#235;    , ë , All
	StringReplace, fnText, fnText, &euml;    , ë , All
	StringReplace, fnText, fnText, &#236;    , ì , All
	StringReplace, fnText, fnText, &igrave;  , ì , All
	StringReplace, fnText, fnText, &#237;    , í , All
	StringReplace, fnText, fnText, &iacute;  , í , All
	StringReplace, fnText, fnText, &#238;    , î , All
	StringReplace, fnText, fnText, &icirc;   , î , All
	StringReplace, fnText, fnText, &#239;    , ï , All
	StringReplace, fnText, fnText, &iuml;    , ï , All
	StringReplace, fnText, fnText, &#240;    , ð , All
	StringReplace, fnText, fnText, &eth;     , ð , All
	StringReplace, fnText, fnText, &#241;    , ñ , All
	StringReplace, fnText, fnText, &ntilde;  , ñ , All
	StringReplace, fnText, fnText, &#242;    , ò , All
	StringReplace, fnText, fnText, &ograve;  , ò , All
	StringReplace, fnText, fnText, &#243;    , ó , All
	StringReplace, fnText, fnText, &oacute;  , ó , All
	StringReplace, fnText, fnText, &#244;    , ô , All
	StringReplace, fnText, fnText, &ocirc;   , ô , All
	StringReplace, fnText, fnText, &#245;    , õ , All
	StringReplace, fnText, fnText, &otilde;  , õ , All
	StringReplace, fnText, fnText, &#246;    , ö , All
	StringReplace, fnText, fnText, &ouml;    , ö , All
	StringReplace, fnText, fnText, &#247;    , ÷ , All
	StringReplace, fnText, fnText, &divide;  , ÷ , All
	StringReplace, fnText, fnText, &#248;    , ø , All
	StringReplace, fnText, fnText, &oslash;  , ø , All
	StringReplace, fnText, fnText, &#249;    , ù , All
	StringReplace, fnText, fnText, &Ugrave;  , ù , All
	StringReplace, fnText, fnText, &#250;    , ú , All
	StringReplace, fnText, fnText, &Uacute;  , ú , All
	StringReplace, fnText, fnText, &#251;    , û , All
	StringReplace, fnText, fnText, &Ucirc;   , û , All
	StringReplace, fnText, fnText, &#252;    , ü , All
	StringReplace, fnText, fnText, &Uuml;    , ü , All
	StringReplace, fnText, fnText, &#253;    , ý , All
	StringReplace, fnText, fnText, &yacute;  , ý , All
	StringReplace, fnText, fnText, &#254;    , þ , All
	StringReplace, fnText, fnText, &thorn;   , þ , All
	StringReplace, fnText, fnText, &#255;    , ÿ , All
	StringReplace, fnText, fnText, &yuml;    , ÿ , All
	StringReplace, fnText, fnText, &#338;    , OE, All
	StringReplace, fnText, fnText, &OElig;   , OE, All
	StringReplace, fnText, fnText, &#339;    , oe, All
	StringReplace, fnText, fnText, &oelig;   , oe, All
	StringReplace, fnText, fnText, &#352;    , Š , All
	StringReplace, fnText, fnText, &Scaron;  , Š , All
	StringReplace, fnText, fnText, &#353;    , š , All
	StringReplace, fnText, fnText, &scaron;  , š , All
	StringReplace, fnText, fnText, &#376;    , Ÿ , All
	StringReplace, fnText, fnText, &Yuml;    , Ÿ , All
	StringReplace, fnText, fnText, &#402;    , ƒ , All
	StringReplace, fnText, fnText, &fnof;    , ƒ , All
	StringReplace, fnText, fnText, &#710;    , ˆ , All
	StringReplace, fnText, fnText, &circ;    , ˆ , All
	StringReplace, fnText, fnText, &#732;    , ˜ , All
	StringReplace, fnText, fnText, &tilde;   , ˜ , All
	StringReplace, fnText, fnText, &#913;    , ? , All
	StringReplace, fnText, fnText, &Alpha;   , ? , All
	StringReplace, fnText, fnText, &#914;    , ? , All
	StringReplace, fnText, fnText, &Beta;    , ? , All
	StringReplace, fnText, fnText, &#915;    , G , All
	StringReplace, fnText, fnText, &Gamma;   , G , All
	StringReplace, fnText, fnText, &#916;    , ? , All
	StringReplace, fnText, fnText, &Delta;   , ? , All
	StringReplace, fnText, fnText, &#917;    , ? , All
	StringReplace, fnText, fnText, &Epsilon; , ? , All
	StringReplace, fnText, fnText, &#918;    , ? , All
	StringReplace, fnText, fnText, &Zeta;    , ? , All
	StringReplace, fnText, fnText, &#919;    , ? , All
	StringReplace, fnText, fnText, &Eta;     , ? , All
	StringReplace, fnText, fnText, &#920;    , T , All
	StringReplace, fnText, fnText, &Theta;   , T , All
	StringReplace, fnText, fnText, &#921;    , ? , All
	StringReplace, fnText, fnText, &Iota;    , ? , All
	StringReplace, fnText, fnText, &#922;    , ? , All
	StringReplace, fnText, fnText, &Kappa;   , ? , All
	StringReplace, fnText, fnText, &#923;    , ? , All
	StringReplace, fnText, fnText, &Lambda;  , ? , All
	StringReplace, fnText, fnText, &#924;    , ? , All
	StringReplace, fnText, fnText, &Mu;      , ? , All
	StringReplace, fnText, fnText, &#925;    , ? , All
	StringReplace, fnText, fnText, &Nu;      , ? , All
	StringReplace, fnText, fnText, &#926;    , ? , All
	StringReplace, fnText, fnText, &Xi;      , ? , All
	StringReplace, fnText, fnText, &#927;    , ? , All
	StringReplace, fnText, fnText, &Omicron  ;, ? , All
	StringReplace, fnText, fnText, &#928;    , ? , All
	StringReplace, fnText, fnText, &Pi;      , ? , All
	StringReplace, fnText, fnText, &#929;    , ? , All
	StringReplace, fnText, fnText, &Rho;     , ? , All
	StringReplace, fnText, fnText, &#931;    , S , All
	StringReplace, fnText, fnText, &Sigma;   , S , All
	StringReplace, fnText, fnText, &#932;    , ? , All
	StringReplace, fnText, fnText, &Tau;     , ? , All
	StringReplace, fnText, fnText, &#933;    , ? , All
	StringReplace, fnText, fnText, &Upsilon  ;, ? , All
	StringReplace, fnText, fnText, &#934;    , F , All
	StringReplace, fnText, fnText, &Phi;     , F , All
	StringReplace, fnText, fnText, &#935;    , ? , All
	StringReplace, fnText, fnText, &Chi;     , ? , All
	StringReplace, fnText, fnText, &#936;    , ? , All
	StringReplace, fnText, fnText, &Psi;     , ? , All
	StringReplace, fnText, fnText, &#937;    , O , All
	StringReplace, fnText, fnText, &Omega;   , O , All
	StringReplace, fnText, fnText, &#945;    , a , All
	StringReplace, fnText, fnText, &alpha;   , a , All
	StringReplace, fnText, fnText, &#946;    , ß , All
	StringReplace, fnText, fnText, &beta;    , ß , All
	StringReplace, fnText, fnText, &#947;    , ? , All
	StringReplace, fnText, fnText, &gamma;   , ? , All
	StringReplace, fnText, fnText, &#948;    , d , All
	StringReplace, fnText, fnText, &delta;   , d , All
	StringReplace, fnText, fnText, &#949;    , e , All
	StringReplace, fnText, fnText, &epsilon  ;, e , All
	StringReplace, fnText, fnText, &#950;    , ? , All
	StringReplace, fnText, fnText, &zeta;    , ? , All
	StringReplace, fnText, fnText, &#951;    , ? , All
	StringReplace, fnText, fnText, &eta;     , ? , All
	StringReplace, fnText, fnText, &#952;    , ? , All
	StringReplace, fnText, fnText, &theta;   , ? , All
	StringReplace, fnText, fnText, &#953;    , ? , All
	StringReplace, fnText, fnText, &iota;    , ? , All
	StringReplace, fnText, fnText, &#954;    , ? , All
	StringReplace, fnText, fnText, &kappa;   , ? , All
	StringReplace, fnText, fnText, &#955;    , ? , All
	StringReplace, fnText, fnText, &lambda;  , ? , All
	StringReplace, fnText, fnText, &#956;    , µ , All
	StringReplace, fnText, fnText, &mu;      , µ , All
	StringReplace, fnText, fnText, &#957;    , ? , All
	StringReplace, fnText, fnText, &nu;      , ? , All
	StringReplace, fnText, fnText, &#958;    , ? , All
	StringReplace, fnText, fnText, &xi;      , ? , All
	StringReplace, fnText, fnText, &#959;    , ? , All
	StringReplace, fnText, fnText, &omicron; , ? , All
	StringReplace, fnText, fnText, &#960;    , p , All
	StringReplace, fnText, fnText, &pi;      , p , All
	StringReplace, fnText, fnText, &#961;    , ? , All
	StringReplace, fnText, fnText, &rho;     , ? , All
	StringReplace, fnText, fnText, &#962;    , ? , All
	StringReplace, fnText, fnText, &sigmaf;  , ? , All
	StringReplace, fnText, fnText, &#963;    , s , All
	StringReplace, fnText, fnText, &sigma;   , s , All
	StringReplace, fnText, fnText, &#964;    , t , All
	StringReplace, fnText, fnText, &tau;     , t , All
	StringReplace, fnText, fnText, &#965;    , ? , All
	StringReplace, fnText, fnText, &upsilon; , ? , All
	StringReplace, fnText, fnText, &#966;    , f , All
	StringReplace, fnText, fnText, &phi;     , f , All
	StringReplace, fnText, fnText, &#967;    , ? , All
	StringReplace, fnText, fnText, &chi;     , ? , All
	StringReplace, fnText, fnText, &#968;    , ? , All
	StringReplace, fnText, fnText, &psi;     , ? , All
	StringReplace, fnText, fnText, &#969;    , ? , All
	StringReplace, fnText, fnText, &omega;   , ? , All
	StringReplace, fnText, fnText, &#977;    , ? , All
	StringReplace, fnText, fnText, &thetasym;, ? , All
	StringReplace, fnText, fnText, &#978;    , ? , All
	StringReplace, fnText, fnText, &Upsih;   , ? , All
	StringReplace, fnText, fnText, &#982;    , ? , All
	StringReplace, fnText, fnText, &piv;     , ? , All
	StringReplace, fnText, fnText, &#8194;   ,   , All
	StringReplace, fnText, fnText, &ensp;    ,   , All
	StringReplace, fnText, fnText, &#8195;   ,   , All
	StringReplace, fnText, fnText, &emsp;    ,   , All
	StringReplace, fnText, fnText, &#8201;   ,   , All
	StringReplace, fnText, fnText, &thinsp;  ,   , All
	StringReplace, fnText, fnText, &#8204;   ,   , All
	StringReplace, fnText, fnText, &zwnj;    ,   , All
	StringReplace, fnText, fnText, &#8205;   ,   , All
	StringReplace, fnText, fnText, &zwj;     ,   , All
	StringReplace, fnText, fnText, &#8206;   ,   , All
	StringReplace, fnText, fnText, &lrm;     ,   , All
	StringReplace, fnText, fnText, &#8207;   ,   , All
	StringReplace, fnText, fnText, &rlm;     ,   , All
	StringReplace, fnText, fnText, &#8211;   , – , All
	StringReplace, fnText, fnText, &ndash;   , – , All
	StringReplace, fnText, fnText, &#8212;   , — , All
	StringReplace, fnText, fnText, &mdash;   , — , All
	StringReplace, fnText, fnText, &#8216;   , ‘ , All
	StringReplace, fnText, fnText, &lsquo;   , ‘ , All
	StringReplace, fnText, fnText, &#8217;   , ’ , All
	StringReplace, fnText, fnText, &rsquo;   , ’ , All
	StringReplace, fnText, fnText, &#8218;   , ‚ , All
	StringReplace, fnText, fnText, &sbquo;   , ‚ , All
	StringReplace, fnText, fnText, &#8220;   , “ , All
	StringReplace, fnText, fnText, &ldquo;   , “ , All
	StringReplace, fnText, fnText, &#8221;   , ” , All
	StringReplace, fnText, fnText, &rdquo;   , ” , All
	StringReplace, fnText, fnText, &#8222;   , „ , All
	StringReplace, fnText, fnText, &bdquo;   , „ , All
	StringReplace, fnText, fnText, &#8224;   , † , All
	StringReplace, fnText, fnText, &dagger;  , † , All
	StringReplace, fnText, fnText, &#8225;   , ‡ , All
	StringReplace, fnText, fnText, &Dagger;  , ‡ , All
	StringReplace, fnText, fnText, &#8226;   , • , All
	StringReplace, fnText, fnText, &bull;    , • , All
	StringReplace, fnText, fnText, &#8230;   , … , All
	StringReplace, fnText, fnText, &hellip;  , … , All
	StringReplace, fnText, fnText, &#8240;   , ‰ , All
	StringReplace, fnText, fnText, &permil;  , ‰ , All
	StringReplace, fnText, fnText, &#8242;   , ' , All
	StringReplace, fnText, fnText, &prime;   , ' , All
	StringReplace, fnText, fnText, &#8243;   , ? , All
	StringReplace, fnText, fnText, &Prime;   , ? , All
	StringReplace, fnText, fnText, &#8249;   , ‹ , All
	StringReplace, fnText, fnText, &lsaquo;  , ‹ , All
	StringReplace, fnText, fnText, &#8250;   , › , All
	StringReplace, fnText, fnText, &rsaquo;  , › , All
	StringReplace, fnText, fnText, &#8254;   , ? , All
	StringReplace, fnText, fnText, &oline;   , ? , All
	StringReplace, fnText, fnText, &#8260;   , / , All
	StringReplace, fnText, fnText, &frasl;   , / , All
	StringReplace, fnText, fnText, &#8364;   , € , All
	StringReplace, fnText, fnText, &euro;    , € , All
	StringReplace, fnText, fnText, &#8465;   , I , All
	StringReplace, fnText, fnText, &image;   , I , All
	StringReplace, fnText, fnText, &#8472;   , P , All
	StringReplace, fnText, fnText, &weierp;  , P , All
	StringReplace, fnText, fnText, &#8476;   , R , All
	StringReplace, fnText, fnText, &real;    , R , All
	StringReplace, fnText, fnText, &#8482;   , ™ , All
	StringReplace, fnText, fnText, &trade;   , ™ , All
	StringReplace, fnText, fnText, &#8501;   , ? , All
	StringReplace, fnText, fnText, &alefsym; , ? , All
	StringReplace, fnText, fnText, &#8592;   , ? , All
	StringReplace, fnText, fnText, &larr;    , ? , All
	StringReplace, fnText, fnText, &#8593;   , ? , All
	StringReplace, fnText, fnText, &uarr;    , ? , All
	StringReplace, fnText, fnText, &#8594;   , ? , All
	StringReplace, fnText, fnText, &rarr;    , ? , All
	StringReplace, fnText, fnText, &#8595;   , ? , All
	StringReplace, fnText, fnText, &darr;    , ? , All
	StringReplace, fnText, fnText, &#8596;   , ? , All
	StringReplace, fnText, fnText, &harr;    , ? , All
	StringReplace, fnText, fnText, &#8629;   , ? , All
	StringReplace, fnText, fnText, &crarr;   , ? , All
	StringReplace, fnText, fnText, &#8656;   , ? , All
	StringReplace, fnText, fnText, &lArr;    , ? , All
	StringReplace, fnText, fnText, &#8657;   , ? , All
	StringReplace, fnText, fnText, &UArr;    , ? , All
	StringReplace, fnText, fnText, &#8658;   , ? , All
	StringReplace, fnText, fnText, &rArr;    , ? , All
	StringReplace, fnText, fnText, &#8659;   , ? , All
	StringReplace, fnText, fnText, &dArr;    , ? , All
	StringReplace, fnText, fnText, &#8660;   , ? , All
	StringReplace, fnText, fnText, &hArr;    , ? , All
	StringReplace, fnText, fnText, &#8704;   , ? , All
	StringReplace, fnText, fnText, &forall;  , ? , All
	StringReplace, fnText, fnText, &#8706;   , ? , All
	StringReplace, fnText, fnText, &part;    , ? , All
	StringReplace, fnText, fnText, &#8707;   , ? , All
	StringReplace, fnText, fnText, &exist;   , ? , All
	StringReplace, fnText, fnText, &#8709;   , Ø , All
	StringReplace, fnText, fnText, &empty;   , Ø , All
	StringReplace, fnText, fnText, &#8711;   , ? , All
	StringReplace, fnText, fnText, &nabla;   , ? , All
	StringReplace, fnText, fnText, &#8712;   , ? , All
	StringReplace, fnText, fnText, &isin;    , ? , All
	StringReplace, fnText, fnText, &#8713;   , ? , All
	StringReplace, fnText, fnText, &notin;   , ? , All
	StringReplace, fnText, fnText, &#8715;   , ? , All
	StringReplace, fnText, fnText, &ni;      , ? , All
	StringReplace, fnText, fnText, &#8719;   , ? , All
	StringReplace, fnText, fnText, &prod;    , ? , All
	StringReplace, fnText, fnText, &#8721;   , S , All
	StringReplace, fnText, fnText, &sum;     , S , All
	StringReplace, fnText, fnText, &#8722;   , - , All
	StringReplace, fnText, fnText, &minus;   , - , All
	StringReplace, fnText, fnText, &#8727;   , * , All
	StringReplace, fnText, fnText, &lowast;  , * , All
	StringReplace, fnText, fnText, &#8730;   , v , All
	StringReplace, fnText, fnText, &radic;   , v , All
	StringReplace, fnText, fnText, &#8733;   , ? , All
	StringReplace, fnText, fnText, &prop;    , ? , All
	StringReplace, fnText, fnText, &#8734;   , 8 , All
	StringReplace, fnText, fnText, &infin;   , 8 , All
	StringReplace, fnText, fnText, &#8736;   , ? , All
	StringReplace, fnText, fnText, &ang;     , ? , All
	StringReplace, fnText, fnText, &#8743;   , ? , All
	StringReplace, fnText, fnText, &and;     , ? , All
	StringReplace, fnText, fnText, &#8744;   , ? , All
	StringReplace, fnText, fnText, &or;      , ? , All
	StringReplace, fnText, fnText, &#8745;   , n , All
	StringReplace, fnText, fnText, &cap;     , n , All
	StringReplace, fnText, fnText, &#8746;   , ? , All
	StringReplace, fnText, fnText, &cup;     , ? , All
	StringReplace, fnText, fnText, &#8747;   , ? , All
	StringReplace, fnText, fnText, &int;     , ? , All
	StringReplace, fnText, fnText, &#8756;   , ? , All
	StringReplace, fnText, fnText, &there4;  , ? , All
	StringReplace, fnText, fnText, &#8764;   , ~ , All
	StringReplace, fnText, fnText, &sim;     , ~ , All
	StringReplace, fnText, fnText, &#8773;   , ? , All
	StringReplace, fnText, fnText, &cong;    , ? , All
	StringReplace, fnText, fnText, &#8776;   , ˜ , All
	StringReplace, fnText, fnText, &asymp;   , ˜ , All
	StringReplace, fnText, fnText, &#8800;   , ? , All
	StringReplace, fnText, fnText, &ne;      , ? , All
	StringReplace, fnText, fnText, &#8801;   , = , All
	StringReplace, fnText, fnText, &equiv;   , = , All
	StringReplace, fnText, fnText, &#8804;   , = , All
	StringReplace, fnText, fnText, &le;      , = , All
	StringReplace, fnText, fnText, &#8805;   , = , All
	StringReplace, fnText, fnText, &ge;      , = , All
	StringReplace, fnText, fnText, &#8834;   , ? , All
	StringReplace, fnText, fnText, &sub;     , ? , All
	StringReplace, fnText, fnText, &#8835;   , ? , All
	StringReplace, fnText, fnText, &sup;     , ? , All
	StringReplace, fnText, fnText, &#8836;   , ? , All
	StringReplace, fnText, fnText, &nsub;    , ? , All
	StringReplace, fnText, fnText, &#8838;   , ? , All
	StringReplace, fnText, fnText, &sube;    , ? , All
	StringReplace, fnText, fnText, &#8839;   , ? , All
	StringReplace, fnText, fnText, &supe;    , ? , All
	StringReplace, fnText, fnText, &#8853;   , ? , All
	StringReplace, fnText, fnText, &oplus;   , ? , All
	StringReplace, fnText, fnText, &#8855;   , ? , All
	StringReplace, fnText, fnText, &otimes;  , ? , All
	StringReplace, fnText, fnText, &#8869;   , ? , All
	StringReplace, fnText, fnText, &perp;    , ? , All
	StringReplace, fnText, fnText, &#8901;   , · , All
	StringReplace, fnText, fnText, &sdot;    , · , All
	StringReplace, fnText, fnText, &#8968;   , ? , All
	StringReplace, fnText, fnText, &lceil;   , ? , All
	StringReplace, fnText, fnText, &#8969;   , ? , All
	StringReplace, fnText, fnText, &rceil;   , ? , All
	StringReplace, fnText, fnText, &#8970;   , ? , All
	StringReplace, fnText, fnText, &lfloor;  , ? , All
	StringReplace, fnText, fnText, &#8971;   , ? , All
	StringReplace, fnText, fnText, &rfloor;  , ? , All
	StringReplace, fnText, fnText, &#9001;   , < , All
	StringReplace, fnText, fnText, &lang;    , < , All
	StringReplace, fnText, fnText, &#9002;   , > , All
	StringReplace, fnText, fnText, &rang;    , > , All
	StringReplace, fnText, fnText, &#9674;   , ? , All
	StringReplace, fnText, fnText, &loz;     , ? , All
	StringReplace, fnText, fnText, &#9824;   , ? , All
	StringReplace, fnText, fnText, &spades;  , ? , All
	StringReplace, fnText, fnText, &#9827;   , ? , All
	StringReplace, fnText, fnText, &clubs;   , ? , All
	StringReplace, fnText, fnText, &#9829;   , ? , All
	StringReplace, fnText, fnText, &hearts;  , ? , All
	StringReplace, fnText, fnText, &#9830;   , ? , All
	StringReplace, fnText, fnText, &diams;   , ? , All
	
	; MsgBox fnText:`n%fnText%
	Return fnText
}
