ReplaceUrlEncodedChars(fnText)
{
	; MsgBox fnText:`n%fnText%
	; StringReplace, fnText, fnText, `%08, backspace      
	; StringReplace, fnText, fnText, `%09, tab            
	; StringReplace, fnText, fnText, `%0A, linefeed       
	; StringReplace, fnText, fnText, `%0D, creturn        
	StringReplace, fnText, fnText, `%20, %A_Space%, All          
	StringReplace, fnText, fnText, `%21, !        , All      
	StringReplace, fnText, fnText, `%22, "        , All      
	StringReplace, fnText, fnText, `%23, #        , All      
	StringReplace, fnText, fnText, `%24, $        , All      
	StringReplace, fnText, fnText, `%25, `%       , All       
	StringReplace, fnText, fnText, `%26, &        , All      
	StringReplace, fnText, fnText, `%27, '        , All      
	StringReplace, fnText, fnText, `%28, (        , All      
	StringReplace, fnText, fnText, `%29, )        , All      
	StringReplace, fnText, fnText, `%2A, *        , All      
	StringReplace, fnText, fnText, `%2B, +        , All      
	StringReplace, fnText, fnText, `%2C, ,        , All      
	StringReplace, fnText, fnText, `%2D, -        , All      
	StringReplace, fnText, fnText, `%2E, .        , All      
	StringReplace, fnText, fnText, `%2F, /        , All      
	StringReplace, fnText, fnText, `%30, 0        , All      
	StringReplace, fnText, fnText, `%31, 1        , All      
	StringReplace, fnText, fnText, `%32, 2        , All      
	StringReplace, fnText, fnText, `%33, 3        , All      
	StringReplace, fnText, fnText, `%34, 4        , All      
	StringReplace, fnText, fnText, `%35, 5        , All      
	StringReplace, fnText, fnText, `%36, 6        , All      
	StringReplace, fnText, fnText, `%37, 7        , All      
	StringReplace, fnText, fnText, `%38, 8        , All      
	StringReplace, fnText, fnText, `%39, 9        , All      
	StringReplace, fnText, fnText, `%3A, :        , All      
	StringReplace, fnText, fnText, `%3B, ;        , All      
	StringReplace, fnText, fnText, `%3C, <        , All      
	StringReplace, fnText, fnText, `%3D, =        , All      
	StringReplace, fnText, fnText, `%3E, >        , All      
	StringReplace, fnText, fnText, `%3F, ?        , All      
	StringReplace, fnText, fnText, `%40, @        , All      
	StringReplace, fnText, fnText, `%41, A        , All      
	StringReplace, fnText, fnText, `%42, B        , All      
	StringReplace, fnText, fnText, `%43, C        , All      
	StringReplace, fnText, fnText, `%44, D        , All      
	StringReplace, fnText, fnText, `%45, E        , All      
	StringReplace, fnText, fnText, `%46, F        , All      
	StringReplace, fnText, fnText, `%47, G        , All      
	StringReplace, fnText, fnText, `%48, H        , All      
	StringReplace, fnText, fnText, `%49, I        , All      
	StringReplace, fnText, fnText, `%4A, J        , All      
	StringReplace, fnText, fnText, `%4B, K        , All      
	StringReplace, fnText, fnText, `%4C, L        , All      
	StringReplace, fnText, fnText, `%4D, M        , All      
	StringReplace, fnText, fnText, `%4E, N        , All      
	StringReplace, fnText, fnText, `%4F, O        , All      
	StringReplace, fnText, fnText, `%50, P        , All      
	StringReplace, fnText, fnText, `%51, Q        , All      
	StringReplace, fnText, fnText, `%52, R        , All      
	StringReplace, fnText, fnText, `%53, S        , All      
	StringReplace, fnText, fnText, `%54, T        , All      
	StringReplace, fnText, fnText, `%55, U        , All      
	StringReplace, fnText, fnText, `%56, V        , All      
	StringReplace, fnText, fnText, `%57, W        , All      
	StringReplace, fnText, fnText, `%58, X        , All      
	StringReplace, fnText, fnText, `%59, Y        , All      
	StringReplace, fnText, fnText, `%5A, Z        , All      
	StringReplace, fnText, fnText, `%5B, [        , All      
	StringReplace, fnText, fnText, `%5C, \        , All      
	StringReplace, fnText, fnText, `%5D, ]        , All      
	StringReplace, fnText, fnText, `%5E, ^        , All      
	StringReplace, fnText, fnText, `%5F, _        , All      
	StringReplace, fnText, fnText, `%60, `        , All      
	StringReplace, fnText, fnText, `%61, a        , All      
	StringReplace, fnText, fnText, `%62, b        , All      
	StringReplace, fnText, fnText, `%63, c        , All      
	StringReplace, fnText, fnText, `%64, d        , All      
	StringReplace, fnText, fnText, `%65, e        , All      
	StringReplace, fnText, fnText, `%66, f        , All      
	StringReplace, fnText, fnText, `%67, g        , All      
	StringReplace, fnText, fnText, `%68, h        , All      
	StringReplace, fnText, fnText, `%69, i        , All      
	StringReplace, fnText, fnText, `%6A, j        , All      
	StringReplace, fnText, fnText, `%6B, k        , All      
	StringReplace, fnText, fnText, `%6C, l        , All      
	StringReplace, fnText, fnText, `%6D, m        , All      
	StringReplace, fnText, fnText, `%6E, n        , All      
	StringReplace, fnText, fnText, `%6F, o        , All      
	StringReplace, fnText, fnText, `%70, p        , All      
	StringReplace, fnText, fnText, `%71, q        , All      
	StringReplace, fnText, fnText, `%72, r        , All      
	StringReplace, fnText, fnText, `%73, s        , All      
	StringReplace, fnText, fnText, `%74, t        , All      
	StringReplace, fnText, fnText, `%75, u        , All      
	StringReplace, fnText, fnText, `%76, v        , All      
	StringReplace, fnText, fnText, `%77, w        , All      
	StringReplace, fnText, fnText, `%78, x        , All      
	StringReplace, fnText, fnText, `%79, y        , All      
	StringReplace, fnText, fnText, `%7A, z        , All      
	StringReplace, fnText, fnText, `%7B, {        , All      
	StringReplace, fnText, fnText, `%7C, |        , All      
	StringReplace, fnText, fnText, `%7D, }        , All      
	StringReplace, fnText, fnText, `%7E, ~        , All      
	StringReplace, fnText, fnText, `%A2, ¢        , All      
	StringReplace, fnText, fnText, `%A3, £        , All      
	StringReplace, fnText, fnText, `%A5, ¥        , All      
	StringReplace, fnText, fnText, `%A6, |        , All      
	StringReplace, fnText, fnText, `%A7, §        , All      
	StringReplace, fnText, fnText, `%AB, «        , All      
	StringReplace, fnText, fnText, `%AC, ¬        , All      
	StringReplace, fnText, fnText, `%AD, ¯        , All      
	StringReplace, fnText, fnText, `%B0, º        , All      
	StringReplace, fnText, fnText, `%B1, ±        , All      
	StringReplace, fnText, fnText, `%B2, ª        , All      
	StringReplace, fnText, fnText, `%B4, ,        , All      
	StringReplace, fnText, fnText, `%B5, µ        , All      
	StringReplace, fnText, fnText, `%BB, »        , All      
	StringReplace, fnText, fnText, `%BC, ¼        , All      
	StringReplace, fnText, fnText, `%BD, ½        , All      
	StringReplace, fnText, fnText, `%BF, ¿        , All      
	StringReplace, fnText, fnText, `%C0, À        , All      
	StringReplace, fnText, fnText, `%C1, Á        , All      
	StringReplace, fnText, fnText, `%C2, Â        , All      
	StringReplace, fnText, fnText, `%C3, Ã        , All      
	StringReplace, fnText, fnText, `%C4, Ä        , All      
	StringReplace, fnText, fnText, `%C5, Å        , All      
	StringReplace, fnText, fnText, `%C6, Æ        , All      
	StringReplace, fnText, fnText, `%C7, Ç        , All      
	StringReplace, fnText, fnText, `%C8, È        , All      
	StringReplace, fnText, fnText, `%C9, É        , All      
	StringReplace, fnText, fnText, `%CA, Ê        , All      
	StringReplace, fnText, fnText, `%CB, Ë        , All      
	StringReplace, fnText, fnText, `%CC, Ì        , All      
	StringReplace, fnText, fnText, `%CD, Í        , All      
	StringReplace, fnText, fnText, `%CE, Î        , All      
	StringReplace, fnText, fnText, `%CF, Ï        , All      
	StringReplace, fnText, fnText, `%D0, Ð        , All      
	StringReplace, fnText, fnText, `%D1, Ñ        , All      
	StringReplace, fnText, fnText, `%D2, Ò        , All      
	StringReplace, fnText, fnText, `%D3, Ó        , All      
	StringReplace, fnText, fnText, `%D4, Ô        , All      
	StringReplace, fnText, fnText, `%D5, Õ        , All      
	StringReplace, fnText, fnText, `%D6, Ö        , All      
	StringReplace, fnText, fnText, `%D8, Ø        , All      
	StringReplace, fnText, fnText, `%D9, Ù        , All      
	StringReplace, fnText, fnText, `%DA, Ú        , All      
	StringReplace, fnText, fnText, `%DB, Û        , All      
	StringReplace, fnText, fnText, `%DC, Ü        , All      
	StringReplace, fnText, fnText, `%DD, Ý        , All      
	StringReplace, fnText, fnText, `%DE, Þ        , All      
	StringReplace, fnText, fnText, `%DF, ß        , All      
	StringReplace, fnText, fnText, `%E0, à        , All      
	StringReplace, fnText, fnText, `%E1, á        , All      
	StringReplace, fnText, fnText, `%E2, â        , All      
	StringReplace, fnText, fnText, `%E3, ã        , All      
	StringReplace, fnText, fnText, `%E4, ä        , All      
	StringReplace, fnText, fnText, `%E5, å        , All      
	StringReplace, fnText, fnText, `%E6, æ        , All      
	StringReplace, fnText, fnText, `%E7, ç        , All      
	StringReplace, fnText, fnText, `%E8, è        , All      
	StringReplace, fnText, fnText, `%E9, é        , All      
	StringReplace, fnText, fnText, `%EA, ê        , All      
	StringReplace, fnText, fnText, `%EB, ë        , All      
	StringReplace, fnText, fnText, `%EC, ì        , All      
	StringReplace, fnText, fnText, `%ED, í        , All      
	StringReplace, fnText, fnText, `%EE, î        , All      
	StringReplace, fnText, fnText, `%EF, ï        , All      
	StringReplace, fnText, fnText, `%F0, ð        , All      
	StringReplace, fnText, fnText, `%F1, ñ        , All      
	StringReplace, fnText, fnText, `%F2, ò        , All      
	StringReplace, fnText, fnText, `%F3, ó        , All      
	StringReplace, fnText, fnText, `%F4, ô        , All      
	StringReplace, fnText, fnText, `%F5, õ        , All      
	StringReplace, fnText, fnText, `%F6, ö        , All      
	StringReplace, fnText, fnText, `%F7, ÷        , All      
	StringReplace, fnText, fnText, `%F8, ø        , All      
	StringReplace, fnText, fnText, `%F9, ù        , All      
	StringReplace, fnText, fnText, `%FA, ú        , All      
	StringReplace, fnText, fnText, `%FB, û        , All      
	StringReplace, fnText, fnText, `%FC, ü        , All      
	StringReplace, fnText, fnText, `%FD, ý        , All      
	StringReplace, fnText, fnText, `%FE, þ        , All      
	StringReplace, fnText, fnText, `%FF, ÿ        , All      
	
	; MsgBox fnText:`n%fnText%
	Return fnText
}


/*
MsgBox % ReplaceUrlEncodedChars("%FD%FD")
*/