GlobalStruct(){
  static POINT:="x;y",FILETIME:="DWORD dwLowDateTime;DWORD dwHighDateTime",RegItemStruct:="HKEY root_key_type;HKEY root_key;TCHAR subkey[1024];TCHAR name[1024];DWORD type;GlobalStruct(FILETIME) ftLastWriteTime"
    ,CPINFO:="UINT MaxCharSize;BYTE DefaultChar[2];BYTE LeadByte[12]"
	,FuncParam := "GlobalStruct(Var) *var,WORD is_byref,default_type,{LPTSTR default_str,Int64 default_int64,Double default_double}"
    ,Func:="PTR vTable,LPTSTR mName,{struct{GlobalStruct(Line) *mJumpToLine,GlobalStruct(FuncParam) *mParam,PTR *mClass},struct{PTR mBIF,UCHAR *mOutputVars,PTR mID}},Int mParamCount,MinParams,GlobalStruct(Label) *mFirstLabel,*mLastLabel,GlobalStruct(Var) **mGlobalvar,**mVar,**mLazyVar,**mStaticVar,**mStaticLazyVar,Int mGlobalVarCount,mVarCount,mVarCountMax,mLazyVarCount,mStaticVarCount,mStaticLazyVarCount,Instances,BYTE mDefaultVarType,bool mIsBuiltIn,mIsVariadic,mHasReturn"
    ,Var:="{Int64 mContentsInt64,Double mContentsDouble,PTR mobject,PTR mVV},{char *mByteContents,LPTSTR mCharContents},{UINT_PTR mLength,GlobalStruct(Var) *mAliasFor},{UINT_PTR mCapacity,UINT_PTR mBIV},BYTE mHowAllocated,mAttrib,mScope,mType,LPTSTR mName"
  ,ExprTokenType:="{__int64 value_int64,double value_double,struct{{PTR *object,GlobalStruct(DerefType) *deref,GlobalStruct(Var) *var,LPTSTR marker},{LPTSTR buf,size_t marker_length}}},UINT symbol,{GlobalStruct(ExprTokenType) *circuit_token,LPTSTR mem_to_free}"
  ,DerefType:="LPTSTR marker,{GlobalStruct(Var) *var,GlobalStruct(Func) *func,GlobalStruct(DerefType) *next,int symbol},Byte type,BYTE param_count,WORD length"
  ,ArgStruct:="BYTE type,bool is_expression,WORD length,LPTSTR text,GlobalStruct(DerefType) *deref,GlobalStruct(ExprTokenType) *postfix"
  ,BreakPoint := "INT id,BYTE type,BYTE state,bool temporary"
  ,Line:="BYTE mActionType,mArgc,WORD mFileIndex,UINT mLineNumber,GlobalStruct(ArgStruct) *mArg,PTR *mAttribute,GlobalStruct(Line) *mPrevLine,*mNextLine,*mRelatedLine,*mParentLine,GlobalStruct(BreakPoint) *mBreakPoint"
  ,Label:="LPTSTR mName,GlobalStruct(Line) *mJumpToLine,GlobalStruct(Label) *mPrevLabel,*mNextLabel"
    ,TextStream:="DWORD mFlags;DWORD mLength;DWORD mLastRead;UINT mCodePage;GlobalStruct(CPINFO) mCodePageInfo;TCHAR mLastWriteChar;{LPBYTE mPos;LPSTR mPosA;LPWSTR  mPosW};{LPBYTE mBuffer;LPSTR mBufferA;LPWSTR mBufferW}"
    ,LoopReadFileStruct:="GlobalStruct(TextStream) *mReadFile;GlobalStruct(TextStream) *mWriteFile;TCHAR mWriteFileName[260];TCHAR mCurrentLine[65536]"
    ,WIN32_FIND_DATA:="DWORD dwFileAttributes;GlobalStruct(FILETIME) ftCreationTime;GlobalStruct(FILETIME) ftLastAccessTime;GlobalStruct(FILETIME) ftLastWriteTime;DWORD nFileSizeHigh;DWORD nFileSizeLow;DWORD dwReserved0;DWORD dwReserved1;TCHAR cFileName[260];TCHAR cAlternateFileName[14]"
    ,FontType:="TCHAR name[64];bool italic;bool underline;bool strikeout;int point_size;int weight;DWORD quality;HFONT hfont"
    ,GuiType:="LPTSTR mName;HWND mHwnd;HWND mStatusBarHwnd;HWND mOwner;UInt mControlCount;UInt mControlCapacity;GlobalStruct(GuiControlType) *mControl;UInt mDefaultButtonIndex;ULONG mReferenceCount;GlobalStruct(Label) *mLabelForClose;GlobalStruct(Label) *mLabelForEscape;GlobalStruct(Label) *mLabelForSize;GlobalStruct(Label) *mLabelForDropFiles;GlobalStruct(Label) *mLabelForContextMenu;bool mLabelForCloseIsRunning;bool mLabelForEscapeIsRunning;bool mLabelForSizeIsRunning;bool mLabelsHaveBeenSet;DWORD mStyle;DWORD mExStyle;bool mInRadioGroup;bool mUseTheme;TCHAR mDelimiter;GlobalStruct(GuiControlType) *mCurrentListView;GlobalStruct(GuiControlType) *mCurrentTreeView;int mCurrentFontIndex;DWORD mCurrentColor;DWORD mBackgroundColorWin;DWORD mBackgroundColorCtl;HBRUSH mBackgroundBrushWin;HBRUSH mBackgroundBrushCtl;HDROP mHdrop;HICON mIconEligibleForDestruction;HICON mIconEligibleForDestructionSmall;HACCEL mAccel;int mMarginX;int mMarginY;int mPrevX;int mPrevY;int mPrevWidth;int mPrevHeight;int mMaxExtentRight;int mMaxExtentDown;int mSectionX;int mSectionY;int mMaxExtentRightSection;int mMaxExtentDownSection;LONG mMinWidth;LONG mMinHeight;LONG mMaxWidth;LONG mMaxHeight;BYTE mTabControlCount;BYTE mCurrentTabControlIndex;UInt mCurrentTabIndex;bool mGuiShowHasNeverBeenDone;bool mFirstActivation;bool mShowIsInProgress;bool mDestroyWindowHasBeenCalled;bool mControlWidthWasSetByContents;bool mUsesDPIScaling;GlobalStruct(FontType) *sFont;int sFontCount;HWND sTreeWithEditInProgress"
    ,GuiControlType:="HWND hwnd;BYTE type;BYTE attrib;BYTE tab_control_index;BYTE tab_index;GlobalStruct(Var) *output_var;GlobalStruct(Label) *jump_to_label"
	,HotkeyCriterion:="BYTE Type;GlobalStruct(Line) *ExprLine;LPTSTR WinTitle,WinText;GlobalStruct(HotkeyCriterion) *NextCriterion;"
    ,global_struct:="__int64 mLoopIteration;GlobalStruct(WIN32_FIND_DATA) *mLoopFile;GlobalStruct(RegItemStruct) *mLoopRegItem;GlobalStruct(LoopReadFileStruct) *mLoopReadFile;LPTSTR mLoopField;GlobalStruct(HotkeyCriterion) *HotCriterion;UInt TitleMatchMode;int UninterruptedLineCount,Priority;DWORD LastError;UInt GuiEvent;UINT_PTR EventInfo;GlobalStruct(POINT) GuiPoint;GlobalStruct(GuiType) *GuiWindow;GlobalStruct(GuiType) *GuiDefaultWindow;GlobalStruct(GuiType) *DialogOwner;UInt GuiControlIndex;int WinDelay;int ControlDelay;int KeyDelay;int KeyDelayPlay;int PressDuration;int PressDurationPlay;int MouseDelay;int MouseDelayPlay;GlobalStruct(Func) *CurrentFunc;GlobalStruct(Func) *CurrentFuncGosub;GlobalStruct(Label) *CurrentLabel;HWND hWndLastUsed;int MsgBoxResult;HWND DialogHWND;DWORD RegView;UInt SendMode;DWORD PeekFrequency;DWORD ThreadStartTime;int UninterruptibleDuration;DWORD CalledByIsDialogMessageOrDispatchMsg;bool CalledByIsDialogMessageOrDispatch;bool TitleFindFast;bool DetectHiddenWindows;bool DetectHiddenText;bool AllowThreadToBeInterrupted;bool AllowTimers;bool ThreadIsCritical;BYTE DefaultMouseSpeed;UShort CoordMode;BYTE StringCaseSense;bool StoreCapslockMode;BYTE SendLevel;bool MsgBoxTimedOut;bool IsPaused;bool ListLinesIsEnabled;UINT Encoding;GlobalStruct(ExprTokenType) *ThrownToken;GlobalStruct(Line) *ExcptLine;GlobalStruct(DerefType) *ExcptDeref;bool InTryBlock"
    ,g:=Struct(global_struct)
    return g[]:=A_GlobalStruct,g
}