class PFilename extends Flimsydata.Provider {

	; Assoziationen zu 'Dokument'
	static data := [[ "Adelsbrief"
		, "Adelsdiplom"
		, "Aktennotiz"
		, "Aktienurkunde"
		, "Aktienzertifikat"
		, "Anfuegung"
		, "Anhang"
		, "Anlage"
		, "Archivale"
		, "Arztbrief"
		, "Aufzeichnung"
		, "Aussendung"
		, "Autograf"
		, "Autograph"
		, "Bayerischer Geograph"
		, "Befundbericht"
		, "Beleg"
		, "Bemerkung"
		, "Bericht"
		, "Bescheid"
		, "Buchung"
		, "Bulletin"
		, "Bussenzettel"
		, "Chronik"
		, "Communiquee"
		, "Diplom"
		, "Diplomurkunde"
		, "Dokument"
		, "Einreiseerlaubnis"
		, "Einzahlungsschein"
		, "Entlassungsbrief"
		, "Erlagschein"
		, "Fahrausweis"
		, "Fuehrerschein"
		, "Geschichte"
		, "Handelspapier"
		, "Kolophon"
		, "Kommunikee"
		, "Konnossement"
		, "Kurrende"
		, "L-Schein"
		, "Letzter_Wille"
		, "Manuskript"
		, "NV-Bescheinigung"
		, "Nachlassdokument"
		, "Nichtveranlagungsbescheinigung"
		, "Ostfraenkische_Voelkertafel"
		, "Passvermerk"
		, "Presseaussendung"
		, "Presseerklaerung"
		, "Rapport"
		, "Rundbrief"
		, "Rundschreiben"
		, "Schlussformel"
		, "Schriftstueck"
		, "Seeladeschein"
		, "Strafmandat"
		, "Strafzettel"
		, "Unterlage"
		, "Urkunde"
		, "Verfasseranmerkung"
		, "Visum"
		, "Waffenpass"
		, "Waffenschein"
		, "Waffentragbewilligung"
		, "Wertpapier"
		, "Wertschrift"
		, "letztwillige Verfuegung"
		, "nicht lebendes Objekt"
		, "unbelebtes Objekt"
		, "Ueberweisungsschein" ]]
}

