class PFoldername extends Flimsydata.Provider {

	; Assoziationen zu 'Information'
	static data := [[ "Abstraktion"
		, "Ammenmaerchen"
		, "Anzeichen"
		, "Auflistung"
		, "Aufschneiderei"
		, "Aufstellung"
		, "Aufzaehlung"
		, "Ausgangsdaten"
		, "Auskunft"
		, "Auskunftsschalter"
		, "Basisinformationen"
		, "Bekanntmachung"
		, "Bericht"
		, "Berichterstattung"
		, "Bibliothek"
		, "Bluff"
		, "Botschaft"
		, "Buecherei"
		, "Daten"
		, "Datenansammlung"
		, "Datenmaterial"
		, "Datenschema"
		, "Datenuebertragung"
		, "Fakten"
		, "Grunddaten"
		, "Hinweisschild"
		, "Hinweistafel"
		, "Information"
		, "Informationstafel"
		, "Informationsuebertragung"
		, "Karte"
		, "Kommunikationsdaten"
		, "Landkarte"
		, "Metadaten"
		, "Metainformationen"
		, "Nachrichtengehalt"
		, "Nachrichteninhalt"
		, "Omen"
		, "Ordnungsprinzip"
		, "Plan"
		, "Schalter"
		, "Schema"
		, "Statistik"
		, "System"
		, "Totalerhebung"
		, "Verbindungsdaten"
		, "Verkehrsdaten"
		, "Vollerhebung"
		, "Vorbedeutung"
		, "Wissen"
		, "doppelt"
		, "mehrfach"
		, "pleonastisch" ]]
}
